In [66]:
import pandas as pd
import os
from datetime import datetime
from meteostat import Point, Monthly

# ---------------------------------------------------------
# 1. AYARLAR
# ---------------------------------------------------------

file_path = 'worldcities.csv'
log_file_path = 'hatali_sehirler_log.txt'

# Avrupa Ülkeleri Listesi (ISO2 Kodları - worldcities.csv 'iso2' kolonu ile eşleşir)
europe_codes = [
    'TR', 'RU', 'DE', 'FR', 'GB', 'IT', 'ES', 'UA', 'PL', 'RO', 
    'NL', 'BE', 'CZ', 'GR', 'PT', 'SE', 'HU', 'AT', 'BY', 'CH', 
    'BG', 'RS', 'DK', 'FI', 'SK', 'NO', 'IE', 'HR', 'MD', 'BA', 
    'AL', 'LT', 'MK', 'SI', 'LV', 'EE', 'ME', 'LU', 'MT', 'IS', 
    'AD', 'MC', 'LI', 'SM', 'VA', 'XK'
]

# Tarih Aralığı
start = datetime(2012, 1, 1)
end = datetime.now()

# ---------------------------------------------------------
# 2. LOGLAMA FONKSİYONU
# ---------------------------------------------------------
def log_error(city_row, error_message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # CSV'deki kolon isimlerine göre loglama
    log_line = f"{timestamp} | ID: {city_row['id']} | City: {city_row['city']} | Country: {city_row['iso2']} | Error: {error_message}\n"
    
    try:
        with open(log_file_path, "a", encoding="utf-8") as f:
            f.write(log_line)
    except Exception as e:
        print(f"Log dosyasına yazılamadı: {e}")

# ---------------------------------------------------------
# 3. VERİYİ OKUMA VE İŞLEME
# ---------------------------------------------------------

# Log dosyasını sıfırla
with open(log_file_path, "w", encoding="utf-8") as f:
    f.write(f"--- İŞLEM BAŞLANGICI: {datetime.now()} ---\n")
    f.write("Log Formatı: ZAMAN | ID | ŞEHİR | ÜLKE KODU | HATA\n")
    f.write("-" * 80 + "\n")

all_weather_data = []

if not os.path.exists(file_path):
    print(f"HATA: Dosya bulunamadı: {file_path}")
else:
    print(f"CSV okunuyor: {file_path}...")
    
    # CSV dosyasını Pandas ile oku
    df_cities = pd.read_csv(file_path)
    
    # Sadece Avrupa ülkelerini (europe_codes içindekileri) filtrele
    # iso2 kolonu ülke kodlarını tutuyor
    europe_cities = df_cities[df_cities['iso2'].isin(europe_codes)].copy()
    
    total_cities = len(europe_cities)
    print(f"Toplam Şehir Sayısı (Dünya): {len(df_cities)}")
    print(f"Filtrelenen Avrupa Şehir Sayısı: {total_cities}")
    print("Veri çekme işlemi başlıyor...\n")

    count = 0
    success_count = 0
    
    # Filtrelenmiş DataFrame üzerinde döngü
    for index, row in europe_cities.iterrows():
        try:
            # CSV kolon isimleri: city, lat, lng, iso2, id
            lat = row['lat']
            lng = row['lng'] # Görselde 'lng' olarak görünüyor
            city_name = row['city']
            country_iso = row['iso2']
            city_id = row['id']

            # Meteostat Point oluştur
            location = Point(lat, lng)
            
            # Veriyi çek
            data = Monthly(location, start, end)
            data = data.fetch()

            if not data.empty:
                # Meta verileri ekle
                data['city_id'] = city_id
                data['city_name'] = city_name
                data['country'] = country_iso
                data['lat'] = lat
                data['lng'] = lng
                
                # İndeksi sütuna çevir (time sütunu oluşur)
                data.reset_index(inplace=True)
                
                # İstenen sütunları seç
                selected_cols = data[['time', 'city_id', 'city_name', 'country', 'tavg', 'tmin', 'tmax', 'lat', 'lng']]
                all_weather_data.append(selected_cols)
                
                success_count += 1
            else:
                # Meteostat istasyon bulamadı
                log_error(row, "Meteostat verisi boş (Empty Data)")

        except Exception as e:
            # Beklenmeyen bir hata
            log_error(row, f"Hata: {str(e)}")
        
        count += 1
        # İlerleme durumunu göster (Her 50 şehirde bir)
        if count % 50 == 0:
            print(f"İlerleme: {count}/{total_cities} şehir tarandı. (Başarılı: {success_count})")

    # ---------------------------------------------------------
    # 4. SONUCU GÖSTERME
    # ---------------------------------------------------------

    print("\n" + "="*50)
    print("İŞLEM TAMAMLANDI")
    print(f"Toplam Taranan: {count}")
    print(f"Başarılı Veri: {success_count}")
    print(f"Hatalar '{log_file_path}' dosyasına kaydedildi.")
    print("="*50)

    if all_weather_data:
        # Tüm verileri birleştir
        final_df = pd.concat(all_weather_data, ignore_index=True)
        
        print("\nSONUÇ DATAFRAME (İLK 20 SATIR):")
        print(final_df.head(20))
        
        print("\nDATAFRAME BİLGİSİ:")
        print(final_df.info())
    else:
        print("Hiçbir veri çekilemedi.")

CSV okunuyor: worldcities.csv...
Toplam Şehir Sayısı (Dünya): 48059
Filtrelenen Avrupa Şehir Sayısı: 13044
Veri çekme işlemi başlıyor...

Warning: Cannot load monthly/08180.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/LHTL0.csv.gz from https://data.meteostat.net/

İlerleme: 50/13044 şehir tarandı. (Başarılı: 50)

Warning: Cannot load monthly/13129.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/08161.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/12425.csv.gz from https://data.meteostat.net/

İlerleme: 100/13044 şehir tarandı. (Başarılı: 99)

Warning: Cannot load monthly/99860.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/EDWD0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/1KBHF.csv.gz from https://data.meteostat.net/

İlerleme: 150/13044 şehir tarandı. (Başarılı: 147)

Warning: Cannot load monthly/10764.csv.gz from https://data.meteostat.net/

İlerleme: 200/13044 şehir tarandı. (Başarılı: 196)

Warning: Cannot load monthly/11722.csv.gz from https://data.meteostat.net/

İlerleme: 250/13044 şehir tarandı. (Başarılı: 243)

Warning: Cannot load monthly/98S13.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SCU42.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/99854.csv.gz from https://data.meteostat.net/

İlerleme: 300/13044 şehir tarandı. (Başarılı: 293)

Warning: Cannot load monthly/13015.csv.gz from https://data.meteostat.net/

İlerleme: 350/13044 şehir tarandı. (Başarılı: 342)

Warning: Cannot load monthly/13354.csv.gz from https://data.meteostat.net/

İlerleme: 400/13044 şehir tarandı. (Başarılı: 387)

Warning: Cannot load monthly/03952.csv.gz from https://data.meteostat.net/

İlerleme: 450/13044 şehir tarandı. (Başarılı: 436)

Warning: Cannot load monthly/LIQD0.csv.gz from https://data.meteostat.net/

İlerleme: 500/13044 şehir tarandı. (Başarılı: 483)
İlerleme: 550/13044 şehir tarandı. (Başarılı: 528)

Warning: Cannot load monthly/13334.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/YL10H.csv.gz from https://data.meteostat.net/

İlerleme: 600/13044 şehir tarandı. (Başarılı: 572)
İlerleme: 650/13044 şehir tarandı. (Başarılı: 617)
İlerleme: 700/13044 şehir tarandı. (Başarılı: 660)

Warning: Cannot load monthly/J8UNY.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/5H5ZH.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/ZE56B.csv.gz from https://data.meteostat.net/

İlerleme: 750/13044 şehir tarandı. (Başarılı: 702)
İlerleme: 800/13044 şehir tarandı. (Başarılı: 743)

Warning: Cannot load monthly/ZQYIH.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/V74W5.csv.gz from https://data.meteostat.net/

İlerleme: 850/13044 şehir tarandı. (Başarılı: 788)

Warning: Cannot load monthly/WA325.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/69667.csv.gz from https://data.meteostat.net/

İlerleme: 900/13044 şehir tarandı. (Başarılı: 832)

Warning: Cannot load monthly/12106.csv.gz from https://data.meteostat.net/

İlerleme: 950/13044 şehir tarandı. (Başarılı: 872)

Warning: Cannot load monthly/11544.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/1Z630.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/XIK8S.csv.gz from https://data.meteostat.net/

İlerleme: 1000/13044 şehir tarandı. (Başarılı: 914)

Warning: Cannot load monthly/07148.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/11543.csv.gz from https://data.meteostat.net/

İlerleme: 1050/13044 şehir tarandı. (Başarılı: 955)
İlerleme: 1100/13044 şehir tarandı. (Başarılı: 999)
İlerleme: 1150/13044 şehir tarandı. (Başarılı: 1046)

Warning: Cannot load monthly/03964.csv.gz from https://data.meteostat.net/

İlerleme: 1200/13044 şehir tarandı. (Başarılı: 1086)

Warning: Cannot load monthly/AUV78.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/EDHX0.csv.gz from https://data.meteostat.net/

İlerleme: 1250/13044 şehir tarandı. (Başarılı: 1123)
İlerleme: 1300/13044 şehir tarandı. (Başarılı: 1165)

Warning: Cannot load monthly/10127.csv.gz from https://data.meteostat.net/

İlerleme: 1350/13044 şehir tarandı. (Başarılı: 1206)

Warning: Cannot load monthly/EDEF0.csv.gz from https://data.meteostat.net/

İlerleme: 1400/13044 şehir tarandı. (Başarılı: 1252)

Warning: Cannot load monthly/RF7QG.csv.gz from https://data.meteostat.net/

İlerleme: 1450/13044 şehir tarandı. (Başarılı: 1298)
İlerleme: 1500/13044 şehir tarandı. (Başarılı: 1344)

Warning: Cannot load monthly/99850.csv.gz from https://data.meteostat.net/

İlerleme: 1550/13044 şehir tarandı. (Başarılı: 1391)
İlerleme: 1600/13044 şehir tarandı. (Başarılı: 1436)
İlerleme: 1650/13044 şehir tarandı. (Başarılı: 1480)
İlerleme: 1700/13044 şehir tarandı. (Başarılı: 1522)

Warning: Cannot load monthly/93WXE.csv.gz from https://data.meteostat.net/

İlerleme: 1750/13044 şehir tarandı. (Başarılı: 1560)
İlerleme: 1800/13044 şehir tarandı. (Başarılı: 1600)
İlerleme: 1850/13044 şehir tarandı. (Başarılı: 1640)
İlerleme: 1900/13044 şehir tarandı. (Başarılı: 1683)

Warning: Cannot load monthly/08094.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/MKJP2.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/8C3QY.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/0FZ2W.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/OX0S8.csv.gz from https://data.meteostat.net/

İlerleme: 1950/13044 şehir tarandı. (Başarılı: 1723)

Warning: Cannot load monthly/SX2ER.csv.gz from https://data.meteostat.net/

İlerleme: 2000/13044 şehir tarandı. (Başarılı: 1765)
İlerleme: 2050/13044 şehir tarandı. (Başarılı: 1808)
İlerleme: 2100/13044 şehir tarandı. (Başarılı: 1849)
İlerleme: 2150/13044 şehir tarandı. (Başarılı: 1893)
İlerleme: 2200/13044 şehir tarandı. (Başarılı: 1935)

Warning: Cannot load monthly/LSNM4.csv.gz from https://data.meteostat.net/

İlerleme: 2250/13044 şehir tarandı. (Başarılı: 1977)
İlerleme: 2300/13044 şehir tarandı. (Başarılı: 2021)
İlerleme: 2350/13044 şehir tarandı. (Başarılı: 2061)

Warning: Cannot load monthly/U8EGK.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/LFYL0.csv.gz from https://data.meteostat.net/

İlerleme: 2400/13044 şehir tarandı. (Başarılı: 2107)
İlerleme: 2450/13044 şehir tarandı. (Başarılı: 2152)
İlerleme: 2500/13044 şehir tarandı. (Başarılı: 2197)
İlerleme: 2550/13044 şehir tarandı. (Başarılı: 2238)
İlerleme: 2600/13044 şehir tarandı. (Başarılı: 2282)

Warning: Cannot load monthly/UH8VM.csv.gz from https://data.meteostat.net/

İlerleme: 2650/13044 şehir tarandı. (Başarılı: 2322)

Warning: Cannot load monthly/WMKV0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/REIIM.csv.gz from https://data.meteostat.net/

İlerleme: 2700/13044 şehir tarandı. (Başarılı: 2366)
İlerleme: 2750/13044 şehir tarandı. (Başarılı: 2410)
İlerleme: 2800/13044 şehir tarandı. (Başarılı: 2454)
İlerleme: 2850/13044 şehir tarandı. (Başarılı: 2498)
İlerleme: 2900/13044 şehir tarandı. (Başarılı: 2540)
İlerleme: 2950/13044 şehir tarandı. (Başarılı: 2582)
İlerleme: 3000/13044 şehir tarandı. (Başarılı: 2624)

Warning: Cannot load monthly/E6BKJ.csv.gz from https://data.meteostat.net/

İlerleme: 3050/13044 şehir tarandı. (Başarılı: 2667)
İlerleme: 3100/13044 şehir tarandı. (Başarılı: 2711)

Warning: Cannot load monthly/ENHA0.csv.gz from https://data.meteostat.net/

İlerleme: 3150/13044 şehir tarandı. (Başarılı: 2750)
İlerleme: 3200/13044 şehir tarandı. (Başarılı: 2798)
İlerleme: 3250/13044 şehir tarandı. (Başarılı: 2837)
İlerleme: 3300/13044 şehir tarandı. (Başarılı: 2877)
İlerleme: 3350/13044 şehir tarandı. (Başarılı: 2914)
İlerleme: 3400/13044 şehir tarandı. (Başarılı: 2957)
İlerleme: 3450/13044 şehir tarandı. (Başarılı: 3004)
İlerleme: 3500/13044 şehir tarandı. (Başarılı: 3048)
İlerleme: 3550/13044 şehir tarandı. (Başarılı: 3089)

Warning: Cannot load monthly/Z8TCC.csv.gz from https://data.meteostat.net/

İlerleme: 3600/13044 şehir tarandı. (Başarılı: 3130)
İlerleme: 3650/13044 şehir tarandı. (Başarılı: 3172)

Warning: Cannot load monthly/L9UY7.csv.gz from https://data.meteostat.net/

İlerleme: 3700/13044 şehir tarandı. (Başarılı: 3215)

Warning: Cannot load monthly/MNSCZ.csv.gz from https://data.meteostat.net/

İlerleme: 3750/13044 şehir tarandı. (Başarılı: 3259)
İlerleme: 3800/13044 şehir tarandı. (Başarılı: 3305)
İlerleme: 3850/13044 şehir tarandı. (Başarılı: 3345)
İlerleme: 3900/13044 şehir tarandı. (Başarılı: 3388)

Warning: Cannot load monthly/LD2IV.csv.gz from https://data.meteostat.net/

İlerleme: 3950/13044 şehir tarandı. (Başarılı: 3434)
İlerleme: 4000/13044 şehir tarandı. (Başarılı: 3477)

Warning: Cannot load monthly/3UTUU.csv.gz from https://data.meteostat.net/

İlerleme: 4050/13044 şehir tarandı. (Başarılı: 3522)
İlerleme: 4100/13044 şehir tarandı. (Başarılı: 3561)
İlerleme: 4150/13044 şehir tarandı. (Başarılı: 3600)

Warning: Cannot load monthly/CM649.csv.gz from https://data.meteostat.net/

İlerleme: 4200/13044 şehir tarandı. (Başarılı: 3639)
İlerleme: 4250/13044 şehir tarandı. (Başarılı: 3684)

Warning: Cannot load monthly/T82KX.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/7I3IW.csv.gz from https://data.meteostat.net/

İlerleme: 4300/13044 şehir tarandı. (Başarılı: 3726)
İlerleme: 4350/13044 şehir tarandı. (Başarılı: 3769)
İlerleme: 4400/13044 şehir tarandı. (Başarılı: 3813)
İlerleme: 4450/13044 şehir tarandı. (Başarılı: 3856)
İlerleme: 4500/13044 şehir tarandı. (Başarılı: 3898)

Warning: Cannot load monthly/AW1DH.csv.gz from https://data.meteostat.net/

İlerleme: 4550/13044 şehir tarandı. (Başarılı: 3939)
İlerleme: 4600/13044 şehir tarandı. (Başarılı: 3981)
İlerleme: 4650/13044 şehir tarandı. (Başarılı: 4022)
İlerleme: 4700/13044 şehir tarandı. (Başarılı: 4063)
İlerleme: 4750/13044 şehir tarandı. (Başarılı: 4106)

Warning: Cannot load monthly/8HD2L.csv.gz from https://data.meteostat.net/

İlerleme: 4800/13044 şehir tarandı. (Başarılı: 4149)

Warning: Cannot load monthly/6D2QF.csv.gz from https://data.meteostat.net/

İlerleme: 4850/13044 şehir tarandı. (Başarılı: 4191)

Warning: Cannot load monthly/07657.csv.gz from https://data.meteostat.net/

İlerleme: 4900/13044 şehir tarandı. (Başarılı: 4233)
İlerleme: 4950/13044 şehir tarandı. (Başarılı: 4277)
İlerleme: 5000/13044 şehir tarandı. (Başarılı: 4321)
İlerleme: 5050/13044 şehir tarandı. (Başarılı: 4363)

Warning: Cannot load monthly/QPF0R.csv.gz from https://data.meteostat.net/

İlerleme: 5100/13044 şehir tarandı. (Başarılı: 4405)
İlerleme: 5150/13044 şehir tarandı. (Başarılı: 4449)
İlerleme: 5200/13044 şehir tarandı. (Başarılı: 4490)
İlerleme: 5250/13044 şehir tarandı. (Başarılı: 4524)
İlerleme: 5300/13044 şehir tarandı. (Başarılı: 4570)
İlerleme: 5350/13044 şehir tarandı. (Başarılı: 4613)
İlerleme: 5400/13044 şehir tarandı. (Başarılı: 4657)
İlerleme: 5450/13044 şehir tarandı. (Başarılı: 4701)
İlerleme: 5500/13044 şehir tarandı. (Başarılı: 4745)

Warning: Cannot load monthly/PVJ0Z.csv.gz from https://data.meteostat.net/

İlerleme: 5550/13044 şehir tarandı. (Başarılı: 4793)
İlerleme: 5600/13044 şehir tarandı. (Başarılı: 4838)

Warning: Cannot load monthly/2DVS4.csv.gz from https://data.meteostat.net/

İlerleme: 5650/13044 şehir tarandı. (Başarılı: 4879)

Warning: Cannot load monthly/5Q3O4.csv.gz from https://data.meteostat.net/

İlerleme: 5700/13044 şehir tarandı. (Başarılı: 4922)
İlerleme: 5750/13044 şehir tarandı. (Başarılı: 4967)

Warning: Cannot load monthly/ZMTDM.csv.gz from https://data.meteostat.net/

İlerleme: 5800/13044 şehir tarandı. (Başarılı: 5012)

Warning: Cannot load monthly/IBND6.csv.gz from https://data.meteostat.net/

İlerleme: 5850/13044 şehir tarandı. (Başarılı: 5053)
İlerleme: 5900/13044 şehir tarandı. (Başarılı: 5096)
İlerleme: 5950/13044 şehir tarandı. (Başarılı: 5140)
İlerleme: 6000/13044 şehir tarandı. (Başarılı: 5183)

Warning: Cannot load monthly/65937.csv.gz from https://data.meteostat.net/

İlerleme: 6050/13044 şehir tarandı. (Başarılı: 5225)
İlerleme: 6100/13044 şehir tarandı. (Başarılı: 5268)
İlerleme: 6150/13044 şehir tarandı. (Başarılı: 5305)
İlerleme: 6200/13044 şehir tarandı. (Başarılı: 5348)
İlerleme: 6250/13044 şehir tarandı. (Başarılı: 5395)
İlerleme: 6300/13044 şehir tarandı. (Başarılı: 5435)
İlerleme: 6350/13044 şehir tarandı. (Başarılı: 5473)
İlerleme: 6400/13044 şehir tarandı. (Başarılı: 5514)

Warning: Cannot load monthly/OOV7U.csv.gz from https://data.meteostat.net/

İlerleme: 6450/13044 şehir tarandı. (Başarılı: 5557)
İlerleme: 6500/13044 şehir tarandı. (Başarılı: 5598)
İlerleme: 6550/13044 şehir tarandı. (Başarılı: 5640)

Warning: Cannot load monthly/CUEN5.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/LAS2M.csv.gz from https://data.meteostat.net/

İlerleme: 6600/13044 şehir tarandı. (Başarılı: 5677)
İlerleme: 6650/13044 şehir tarandı. (Başarılı: 5719)
İlerleme: 6700/13044 şehir tarandı. (Başarılı: 5761)
İlerleme: 6750/13044 şehir tarandı. (Başarılı: 5807)
İlerleme: 6800/13044 şehir tarandı. (Başarılı: 5847)
İlerleme: 6850/13044 şehir tarandı. (Başarılı: 5890)

Warning: Cannot load monthly/VYMRN.csv.gz from https://data.meteostat.net/

İlerleme: 6900/13044 şehir tarandı. (Başarılı: 5933)

Warning: Cannot load monthly/L9Q0M.csv.gz from https://data.meteostat.net/

İlerleme: 6950/13044 şehir tarandı. (Başarılı: 5976)

Warning: Cannot load monthly/P00KI.csv.gz from https://data.meteostat.net/

İlerleme: 7000/13044 şehir tarandı. (Başarılı: 6023)

Warning: Cannot load monthly/99YFU.csv.gz from https://data.meteostat.net/

İlerleme: 7050/13044 şehir tarandı. (Başarılı: 6064)
İlerleme: 7100/13044 şehir tarandı. (Başarılı: 6107)
İlerleme: 7150/13044 şehir tarandı. (Başarılı: 6150)
İlerleme: 7200/13044 şehir tarandı. (Başarılı: 6194)
İlerleme: 7250/13044 şehir tarandı. (Başarılı: 6238)
İlerleme: 7300/13044 şehir tarandı. (Başarılı: 6276)
İlerleme: 7350/13044 şehir tarandı. (Başarılı: 6314)
İlerleme: 7400/13044 şehir tarandı. (Başarılı: 6358)
İlerleme: 7450/13044 şehir tarandı. (Başarılı: 6400)
İlerleme: 7500/13044 şehir tarandı. (Başarılı: 6437)
İlerleme: 7550/13044 şehir tarandı. (Başarılı: 6482)

Warning: Cannot load monthly/E2LTV.csv.gz from https://data.meteostat.net/

İlerleme: 7600/13044 şehir tarandı. (Başarılı: 6526)
İlerleme: 7650/13044 şehir tarandı. (Başarılı: 6571)
İlerleme: 7700/13044 şehir tarandı. (Başarılı: 6612)

Warning: Cannot load monthly/068GX.csv.gz from https://data.meteostat.net/

İlerleme: 7750/13044 şehir tarandı. (Başarılı: 6656)
İlerleme: 7800/13044 şehir tarandı. (Başarılı: 6699)
İlerleme: 7850/13044 şehir tarandı. (Başarılı: 6743)
İlerleme: 7900/13044 şehir tarandı. (Başarılı: 6790)
İlerleme: 7950/13044 şehir tarandı. (Başarılı: 6830)
İlerleme: 8000/13044 şehir tarandı. (Başarılı: 6874)
İlerleme: 8050/13044 şehir tarandı. (Başarılı: 6919)
İlerleme: 8100/13044 şehir tarandı. (Başarılı: 6965)
İlerleme: 8150/13044 şehir tarandı. (Başarılı: 7008)
İlerleme: 8200/13044 şehir tarandı. (Başarılı: 7054)

Warning: Cannot load monthly/NW8SC.csv.gz from https://data.meteostat.net/

İlerleme: 8250/13044 şehir tarandı. (Başarılı: 7090)
İlerleme: 8300/13044 şehir tarandı. (Başarılı: 7131)
İlerleme: 8350/13044 şehir tarandı. (Başarılı: 7177)
İlerleme: 8400/13044 şehir tarandı. (Başarılı: 7219)

Warning: Cannot load monthly/03970.csv.gz from https://data.meteostat.net/

İlerleme: 8450/13044 şehir tarandı. (Başarılı: 7261)
İlerleme: 8500/13044 şehir tarandı. (Başarılı: 7299)
İlerleme: 8550/13044 şehir tarandı. (Başarılı: 7340)
İlerleme: 8600/13044 şehir tarandı. (Başarılı: 7386)

Warning: Cannot load monthly/4TH97.csv.gz from https://data.meteostat.net/

İlerleme: 8650/13044 şehir tarandı. (Başarılı: 7431)
İlerleme: 8700/13044 şehir tarandı. (Başarılı: 7470)
İlerleme: 8750/13044 şehir tarandı. (Başarılı: 7513)
İlerleme: 8800/13044 şehir tarandı. (Başarılı: 7553)
İlerleme: 8850/13044 şehir tarandı. (Başarılı: 7599)
İlerleme: 8900/13044 şehir tarandı. (Başarılı: 7642)
İlerleme: 8950/13044 şehir tarandı. (Başarılı: 7685)
İlerleme: 9000/13044 şehir tarandı. (Başarılı: 7728)
İlerleme: 9050/13044 şehir tarandı. (Başarılı: 7774)
İlerleme: 9100/13044 şehir tarandı. (Başarılı: 7816)
İlerleme: 9150/13044 şehir tarandı. (Başarılı: 7859)
İlerleme: 9200/13044 şehir tarandı. (Başarılı: 7902)
İlerleme: 9250/13044 şehir tarandı. (Başarılı: 7944)
İlerleme: 9300/13044 şehir tarandı. (Başarılı: 7986)
İlerleme: 9350/13044 şehir tarandı. (Başarılı: 8031)
İlerleme: 9400/13044 şehir tarandı. (Başarılı: 8077)
İlerleme: 9450/13044 şehir tarandı. (Başarılı: 8123)
İlerleme: 9500/13044 şehir tarandı. (Başarılı: 8163)
İlerleme: 9550/13044 şehir tarandı. (Başarılı: 8202)
İlerleme: 9600/13044 şehir tarandı. (Başarılı: 8247)
İlerleme: 9650/13044 şehir tarandı. (Başarılı: 8293)
İlerleme: 9700/13044 şehir tarandı. (Başarılı: 8339)
İlerleme: 9750/13044 şehir tarandı. (Başarılı: 8383)
İlerleme: 9800/13044 şehir tarandı. (Başarılı: 8425)
İlerleme: 9850/13044 şehir tarandı. (Başarılı: 8468)
İlerleme: 9900/13044 şehir tarandı. (Başarılı: 8510)

Warning: Cannot load monthly/GULNV.csv.gz from https://data.meteostat.net/

İlerleme: 9950/13044 şehir tarandı. (Başarılı: 8550)
İlerleme: 10000/13044 şehir tarandı. (Başarılı: 8587)

Warning: Cannot load monthly/RKW4H.csv.gz from https://data.meteostat.net/

İlerleme: 10050/13044 şehir tarandı. (Başarılı: 8631)
İlerleme: 10100/13044 şehir tarandı. (Başarılı: 8677)

Warning: Cannot load monthly/OE1SL.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/47R4B.csv.gz from https://data.meteostat.net/

İlerleme: 10150/13044 şehir tarandı. (Başarılı: 8719)
İlerleme: 10200/13044 şehir tarandı. (Başarılı: 8762)
İlerleme: 10250/13044 şehir tarandı. (Başarılı: 8805)
İlerleme: 10300/13044 şehir tarandı. (Başarılı: 8840)

Warning: Cannot load monthly/13005.csv.gz from https://data.meteostat.net/

İlerleme: 10350/13044 şehir tarandı. (Başarılı: 8883)
İlerleme: 10400/13044 şehir tarandı. (Başarılı: 8929)
İlerleme: 10450/13044 şehir tarandı. (Başarılı: 8973)
İlerleme: 10500/13044 şehir tarandı. (Başarılı: 9012)
İlerleme: 10550/13044 şehir tarandı. (Başarılı: 9056)
İlerleme: 10600/13044 şehir tarandı. (Başarılı: 9099)
İlerleme: 10650/13044 şehir tarandı. (Başarılı: 9144)
İlerleme: 10700/13044 şehir tarandı. (Başarılı: 9182)
İlerleme: 10750/13044 şehir tarandı. (Başarılı: 9227)
İlerleme: 10800/13044 şehir tarandı. (Başarılı: 9265)
İlerleme: 10850/13044 şehir tarandı. (Başarılı: 9307)
İlerleme: 10900/13044 şehir tarandı. (Başarılı: 9347)
İlerleme: 10950/13044 şehir tarandı. (Başarılı: 9389)
İlerleme: 11000/13044 şehir tarandı. (Başarılı: 9430)
İlerleme: 11050/13044 şehir tarandı. (Başarılı: 9471)
İlerleme: 11100/13044 şehir tarandı. (Başarılı: 9514)
İlerleme: 11150/13044 şehir tarandı. (Başarılı: 9556)
İlerleme: 11200/13044 şehir tarandı. (Başarılı: 9599)
İlerleme: 11250/13044 şehir tarandı. (Başarılı: 9641)
İlerleme: 11300/13044 şehir tarandı. (Başarılı: 9681)
İlerleme: 11350/13044 şehir tarandı. (Başarılı: 9721)
İlerleme: 11400/13044 şehir tarandı. (Başarılı: 9763)
İlerleme: 11450/13044 şehir tarandı. (Başarılı: 9810)
İlerleme: 11500/13044 şehir tarandı. (Başarılı: 9851)
İlerleme: 11550/13044 şehir tarandı. (Başarılı: 9895)
İlerleme: 11600/13044 şehir tarandı. (Başarılı: 9939)
İlerleme: 11650/13044 şehir tarandı. (Başarılı: 9982)
İlerleme: 11700/13044 şehir tarandı. (Başarılı: 10021)
İlerleme: 11750/13044 şehir tarandı. (Başarılı: 10063)
İlerleme: 11800/13044 şehir tarandı. (Başarılı: 10105)
İlerleme: 11850/13044 şehir tarandı. (Başarılı: 10146)
İlerleme: 11900/13044 şehir tarandı. (Başarılı: 10189)
İlerleme: 11950/13044 şehir tarandı. (Başarılı: 10233)
İlerleme: 12000/13044 şehir tarandı. (Başarılı: 10279)
İlerleme: 12050/13044 şehir tarandı. (Başarılı: 10325)
İlerleme: 12100/13044 şehir tarandı. (Başarılı: 10369)
İlerleme: 12150/13044 şehir tarandı. (Başarılı: 10414)
İlerleme: 12200/13044 şehir tarandı. (Başarılı: 10457)
İlerleme: 12250/13044 şehir tarandı. (Başarılı: 10500)
İlerleme: 12300/13044 şehir tarandı. (Başarılı: 10548)
İlerleme: 12350/13044 şehir tarandı. (Başarılı: 10590)

Warning: Cannot load monthly/XAC63.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/JMAAI.csv.gz from https://data.meteostat.net/

İlerleme: 12400/13044 şehir tarandı. (Başarılı: 10634)
İlerleme: 12450/13044 şehir tarandı. (Başarılı: 10672)
İlerleme: 12500/13044 şehir tarandı. (Başarılı: 10713)
İlerleme: 12550/13044 şehir tarandı. (Başarılı: 10754)
İlerleme: 12600/13044 şehir tarandı. (Başarılı: 10799)
İlerleme: 12650/13044 şehir tarandı. (Başarılı: 10839)
İlerleme: 12700/13044 şehir tarandı. (Başarılı: 10887)
İlerleme: 12750/13044 şehir tarandı. (Başarılı: 10930)
İlerleme: 12800/13044 şehir tarandı. (Başarılı: 10974)
İlerleme: 12850/13044 şehir tarandı. (Başarılı: 11017)
İlerleme: 12900/13044 şehir tarandı. (Başarılı: 11063)
İlerleme: 12950/13044 şehir tarandı. (Başarılı: 11109)
İlerleme: 13000/13044 şehir tarandı. (Başarılı: 11136)

==================================================
İŞLEM TAMAMLANDI
Toplam Taranan: 13044
Başarılı Veri: 11165
Hatalar 'hatali_sehirler_log.txt' dosyasına kaydedildi.
==================================================

SONUÇ DATAFRAME (İLK 20 SATIR):
         time     city_id city_name country  tavg  tmin  tmax      lat  \
0  2012-01-01  1643318494    Moscow      RU  -6.8  -8.9  -4.5  55.7506
1  2012-02-01  1643318494    Moscow      RU -11.7 -14.8  -8.6  55.7506
2  2012-03-01  1643318494    Moscow      RU  -3.1  -6.4   0.0  55.7506
3  2012-04-01  1643318494    Moscow      RU   8.2   3.7  13.0  55.7506
4  2012-05-01  1643318494    Moscow      RU  15.1   9.4  20.9  55.7506
5  2012-06-01  1643318494    Moscow      RU  17.1  12.2  22.0  55.7506
6  2012-07-01  1643318494    Moscow      RU  20.9  15.6  26.1  55.7506
7  2012-08-01  1643318494    Moscow      RU  17.7  13.5  22.6  55.7506
8  2012-09-01  1643318494    Moscow      RU  12.9   8.7  17.5  55.7506
9  2012-10-01  1643318494    Moscow      RU   6.5   3.9   9.3  55.7506
10 2012-11-01  1643318494    Moscow      RU   1.6  -0.3   3.4  55.7506
11 2012-12-01  1643318494    Moscow      RU  -8.6 -11.1  -6.1  55.7506
12 2013-01-01  1643318494    Moscow      RU  -8.5 -10.8  -6.5  55.7506
13 2013-02-01  1643318494    Moscow      RU  -3.5  -6.3  -0.9  55.7506
14 2013-03-01  1643318494    Moscow      RU  -6.6 -10.9  -2.2  55.7506
15 2013-04-01  1643318494    Moscow      RU   6.1   1.4  10.6  55.7506
16 2013-05-01  1643318494    Moscow      RU  16.9  11.6  22.3  55.7506
17 2013-06-01  1643318494    Moscow      RU  19.8  14.2  25.4  55.7506
18 2013-07-01  1643318494    Moscow      RU  18.9  14.5  23.6  55.7506
19 2013-08-01  1643318494    Moscow      RU  18.3  13.4  23.8  55.7506

        lng
0   37.6175
1   37.6175
2   37.6175
3   37.6175
4   37.6175
5   37.6175
6   37.6175
7   37.6175
8   37.6175
9   37.6175
10  37.6175
11  37.6175
12  37.6175
13  37.6175
14  37.6175
15  37.6175
16  37.6175
17  37.6175
18  37.6175
19  37.6175

DATAFRAME BİLGİSİ:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1700023 entries, 0 to 1700022
Data columns (total 9 columns):
 #   Column     Dtype
---  ------     -----
 0   time       datetime64[ns]
 1   city_id    int64
 2   city_name  object
 3   country    object
 4   tavg       Float64
 5   tmin       Float64
 6   tmax       Float64
 7   lat        float64
 8   lng        float64
dtypes: Float64(3), datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 121.6+ MB
None

In [68]:
final_df.to_csv("final.csv", index=False)

In [69]:
final_df

,time,city_id,city_name,country,tavg,tmin,tmax,lat,lng
0,2012-01-01,1643318494,Moscow,RU,-6.8,-8.9,-4.5,55.7506,37.6175
1,2012-02-01,1643318494,Moscow,RU,-11.7,-14.8,-8.6,55.7506,37.6175
2,2012-03-01,1643318494,Moscow,RU,-3.1,-6.4,0.0,55.7506,37.6175
3,2012-04-01,1643318494,Moscow,RU,8.2,3.7,13.0,55.7506,37.6175
4,2012-05-01,1643318494,Moscow,RU,15.1,9.4,20.9,55.7506,37.6175
...,...,...,...,...,...,...,...,...,...
1700018,2025-05-01,1705477555,Zavrč,SI,14.7,8.9,20.1,46.3917,16.0497
1700019,2025-06-01,1705477555,Zavrč,SI,22.8,15.1,29.0,46.3917,16.0497
1700020,2025-07-01,1705477555,Zavrč,SI,22.3,16.0,28.2,46.3917,16.0497
1700021,2025-08-01,1705477555,Zavrč,SI,21.5,14.8,27.9,46.3917,16.0497
1700022,2025-09-01,1705477555,Zavrč,SI,17.7,13.9,22.0,46.3917,16.0497

In [70]:
import pandas as pd
import os
from datetime import datetime
from meteostat import Point, Monthly

# ---------------------------------------------------------
# 1. AYARLAR
# ---------------------------------------------------------

file_path = 'worldcities.csv'
log_file_path = 'hatali_sehirler_log.txt'
output_csv_path = 'tum_dunya_hava_verileri.csv' # Sonuçların kaydedileceği dosya

# Tarih Aralığı
start = datetime(2012, 1, 1)
end = datetime.now()

# ---------------------------------------------------------
# 2. LOGLAMA FONKSİYONU
# ---------------------------------------------------------
def log_error(city_row, error_message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # CSV'deki kolon isimlerine göre loglama
    log_line = f"{timestamp} | ID: {city_row['id']} | City: {city_row['city']} | Country: {city_row['iso2']} | Error: {error_message}\n"
    
    try:
        with open(log_file_path, "a", encoding="utf-8") as f:
            f.write(log_line)
    except Exception as e:
        print(f"Log dosyasına yazılamadı: {e}")

# ---------------------------------------------------------
# 3. VERİYİ OKUMA VE İŞLEME
# ---------------------------------------------------------

# Log dosyasını sıfırla
with open(log_file_path, "w", encoding="utf-8") as f:
    f.write(f"--- İŞLEM BAŞLANGICI: {datetime.now()} ---\n")
    f.write("Log Formatı: ZAMAN | ID | ŞEHİR | ÜLKE KODU | HATA\n")
    f.write("-" * 80 + "\n")

all_weather_data = []

if not os.path.exists(file_path):
    print(f"HATA: Dosya bulunamadı: {file_path}")
else:
    print(f"CSV okunuyor: {file_path}...")
    
    # CSV dosyasını Pandas ile oku
    df_cities = pd.read_csv(file_path)
    
    # FİLTRELEME İŞLEMİ KALDIRILDI
    # Doğrudan tüm veri seti üzerinde çalışacağız
    
    total_cities = len(df_cities)
    print(f"Toplam Şehir Sayısı (Tüm Dünya): {total_cities}")
    print("Veri çekme işlemi başlıyor... (Bu işlem uzun sürebilir)\n")

    count = 0
    success_count = 0
    
    # Tüm DataFrame üzerinde döngü
    for index, row in df_cities.iterrows():
        try:
            # CSV kolon isimleri: city, lat, lng, iso2, id
            lat = row['lat']
            lng = row['lng'] 
            city_name = row['city']
            country_iso = row['iso2']
            city_id = row['id']

            # Meteostat Point oluştur
            location = Point(lat, lng)
            
            # Veriyi çek
            data = Monthly(location, start, end)
            data = data.fetch()

            if not data.empty:
                # Meta verileri ekle
                data['city_id'] = city_id
                data['city_name'] = city_name
                data['country'] = country_iso
                data['lat'] = lat
                data['lng'] = lng
                
                # İndeksi sütuna çevir (time sütunu oluşur)
                data.reset_index(inplace=True)
                
                # İstenen sütunları seç
                selected_cols = data[['time', 'city_id', 'city_name', 'country', 'tavg', 'tmin', 'tmax', 'lat', 'lng']]
                all_weather_data.append(selected_cols)
                
                success_count += 1
            else:
                # Meteostat istasyon bulamadı
                log_error(row, "Meteostat verisi boş (Empty Data)")

        except Exception as e:
            # Beklenmeyen bir hata
            log_error(row, f"Hata: {str(e)}")
        
        count += 1
        
        # İlerleme durumunu göster (Her 100 şehirde bir yazdıralım, liste uzun olduğu için)
        if count % 100 == 0:
            print(f"İlerleme: {count}/{total_cities} şehir tarandı. (Başarılı: {success_count})")

    # ---------------------------------------------------------
    # 4. SONUCU GÖSTERME VE KAYDETME
    # ---------------------------------------------------------

    print("\n" + "="*50)
    print("İŞLEM TAMAMLANDI")
    print(f"Toplam Taranan: {count}")
    print(f"Başarılı Veri (Şehir Bazlı): {success_count}")
    print(f"Hatalar '{log_file_path}' dosyasına kaydedildi.")
    print("="*50)

    if all_weather_data:
        # Tüm verileri birleştir
        final_df = pd.concat(all_weather_data, ignore_index=True)
        
        print("\nSONUÇ DATAFRAME (İLK 20 SATIR):")
        print(final_df.head(20))
        
        print("\nDATAFRAME BİLGİSİ:")
        print(final_df.info())

        # Veriyi CSV olarak kaydet (Çok önemli, çünkü veri çok büyük olacak)
        print(f"\nVeriler '{output_csv_path}' dosyasına kaydediliyor...")
        final_df.to_csv(output_csv_path, index=False)
        print("Kayıt işlemi başarılı.")
        
    else:
        print("Hiçbir veri çekilemedi.")

CSV okunuyor: worldcities.csv...
Toplam Şehir Sayısı (Tüm Dünya): 48059
Veri çekme işlemi başlıyor... (Bu işlem uzun sürebilir)

Warning: Cannot load monthly/RKSK0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/VVGL0.csv.gz from https://data.meteostat.net/

İlerleme: 100/48059 şehir tarandı. (Başarılı: 82)

Warning: Cannot load monthly/40947.csv.gz from https://data.meteostat.net/

İlerleme: 200/48059 şehir tarandı. (Başarılı: 144)

Warning: Cannot load monthly/CWCS0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/CWVZ0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/84125.csv.gz from https://data.meteostat.net/

İlerleme: 300/48059 şehir tarandı. (Başarılı: 217)
İlerleme: 400/48059 şehir tarandı. (Başarılı: 285)

Warning: Cannot load monthly/67774.csv.gz from https://data.meteostat.net/

İlerleme: 500/48059 şehir tarandı. (Başarılı: 363)

Warning: Cannot load monthly/ZMUB0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/44291.csv.gz from https://data.meteostat.net/

İlerleme: 600/48059 şehir tarandı. (Başarılı: 435)

Warning: Cannot load monthly/40770.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/37545.csv.gz from https://data.meteostat.net/

İlerleme: 700/48059 şehir tarandı. (Başarılı: 499)

Warning: Cannot load monthly/67587.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40621.csv.gz from https://data.meteostat.net/

İlerleme: 800/48059 şehir tarandı. (Başarılı: 574)

Warning: Cannot load monthly/64076.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/ZSZS0.csv.gz from https://data.meteostat.net/

İlerleme: 900/48059 şehir tarandı. (Başarılı: 646)

Warning: Cannot load monthly/KZAB0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/CWLU0.csv.gz from https://data.meteostat.net/

İlerleme: 1000/48059 şehir tarandı. (Başarılı: 713)

Warning: Cannot load monthly/40670.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/87696.csv.gz from https://data.meteostat.net/

İlerleme: 1100/48059 şehir tarandı. (Başarılı: 784)
İlerleme: 1200/48059 şehir tarandı. (Başarılı: 860)

Warning: Cannot load monthly/98639.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/41443.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/96783.csv.gz from https://data.meteostat.net/

İlerleme: 1300/48059 şehir tarandı. (Başarılı: 931)

Warning: Cannot load monthly/76050.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40676.csv.gz from https://data.meteostat.net/

İlerleme: 1400/48059 şehir tarandı. (Başarılı: 1008)

Warning: Cannot load monthly/66305.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40680.csv.gz from https://data.meteostat.net/

İlerleme: 1500/48059 şehir tarandı. (Başarılı: 1087)
İlerleme: 1600/48059 şehir tarandı. (Başarılı: 1170)
İlerleme: 1700/48059 şehir tarandı. (Başarılı: 1251)
İlerleme: 1800/48059 şehir tarandı. (Başarılı: 1325)

Warning: Cannot load monthly/40672.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/98436.csv.gz from https://data.meteostat.net/

İlerleme: 1900/48059 şehir tarandı. (Başarılı: 1389)

Warning: Cannot load monthly/40611.csv.gz from https://data.meteostat.net/

İlerleme: 2000/48059 şehir tarandı. (Başarılı: 1469)

Warning: Cannot load monthly/RPUN0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RKJU0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/47192.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/98329.csv.gz from https://data.meteostat.net/

İlerleme: 2100/48059 şehir tarandı. (Başarılı: 1551)

Warning: Cannot load monthly/98746.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/66140.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/60128.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/MMHC0.csv.gz from https://data.meteostat.net/

İlerleme: 2200/48059 şehir tarandı. (Başarılı: 1632)

Warning: Cannot load monthly/K44N0.csv.gz from https://data.meteostat.net/

İlerleme: 2300/48059 şehir tarandı. (Başarılı: 1712)
İlerleme: 2400/48059 şehir tarandı. (Başarılı: 1794)
İlerleme: 2500/48059 şehir tarandı. (Başarılı: 1863)

Warning: Cannot load monthly/40953.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/47706.csv.gz from https://data.meteostat.net/

İlerleme: 2600/48059 şehir tarandı. (Başarılı: 1943)

Warning: Cannot load monthly/69304.csv.gz from https://data.meteostat.net/

İlerleme: 2700/48059 şehir tarandı. (Başarılı: 2018)
İlerleme: 2800/48059 şehir tarandı. (Başarılı: 2097)

Warning: Cannot load monthly/HEAM0.csv.gz from https://data.meteostat.net/

İlerleme: 2900/48059 şehir tarandı. (Başarılı: 2160)
İlerleme: 3000/48059 şehir tarandı. (Başarılı: 2234)

Warning: Cannot load monthly/WIPK0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40674.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RKJM0.csv.gz from https://data.meteostat.net/

İlerleme: 3100/48059 şehir tarandı. (Başarılı: 2313)

Warning: Cannot load monthly/47100.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RKTV0.csv.gz from https://data.meteostat.net/

İlerleme: 3200/48059 şehir tarandı. (Başarılı: 2387)

Warning: Cannot load monthly/VVDL0.csv.gz from https://data.meteostat.net/

İlerleme: 3300/48059 şehir tarandı. (Başarılı: 2463)

Warning: Cannot load monthly/46747.csv.gz from https://data.meteostat.net/

İlerleme: 3400/48059 şehir tarandı. (Başarılı: 2535)

Warning: Cannot load monthly/RPVC0.csv.gz from https://data.meteostat.net/

İlerleme: 3500/48059 şehir tarandı. (Başarılı: 2621)

Warning: Cannot load monthly/62955.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/64062.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SBGU0.csv.gz from https://data.meteostat.net/

İlerleme: 3600/48059 şehir tarandı. (Başarılı: 2694)

Warning: Cannot load monthly/93172.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/MNLN0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/83375.csv.gz from https://data.meteostat.net/

İlerleme: 3700/48059 şehir tarandı. (Başarılı: 2774)
İlerleme: 3800/48059 şehir tarandı. (Başarılı: 2844)
İlerleme: 3900/48059 şehir tarandı. (Başarılı: 2914)
İlerleme: 4000/48059 şehir tarandı. (Başarılı: 2988)
İlerleme: 4100/48059 şehir tarandı. (Başarılı: 3061)

Warning: Cannot load monthly/71594.csv.gz from https://data.meteostat.net/

İlerleme: 4200/48059 şehir tarandı. (Başarılı: 3136)

Warning: Cannot load monthly/78439.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/HSMD0.csv.gz from https://data.meteostat.net/

İlerleme: 4300/48059 şehir tarandı. (Başarılı: 3210)
İlerleme: 4400/48059 şehir tarandı. (Başarılı: 3284)
İlerleme: 4500/48059 şehir tarandı. (Başarılı: 3356)
İlerleme: 4600/48059 şehir tarandı. (Başarılı: 3431)
İlerleme: 4700/48059 şehir tarandı. (Başarılı: 3508)

Warning: Cannot load monthly/WATL0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/OIKJ0.csv.gz from https://data.meteostat.net/

İlerleme: 4800/48059 şehir tarandı. (Başarılı: 3574)

Warning: Cannot load monthly/60492.csv.gz from https://data.meteostat.net/

İlerleme: 4900/48059 şehir tarandı. (Başarılı: 3640)
İlerleme: 5000/48059 şehir tarandı. (Başarılı: 3709)
İlerleme: 5100/48059 şehir tarandı. (Başarılı: 3773)

Warning: Cannot load monthly/OIIA0.csv.gz from https://data.meteostat.net/

İlerleme: 5200/48059 şehir tarandı. (Başarılı: 3842)

Warning: Cannot load monthly/69542.csv.gz from https://data.meteostat.net/

İlerleme: 5300/48059 şehir tarandı. (Başarılı: 3917)

Warning: Cannot load monthly/80077.csv.gz from https://data.meteostat.net/

İlerleme: 5400/48059 şehir tarandı. (Başarılı: 3989)
İlerleme: 5500/48059 şehir tarandı. (Başarılı: 4061)
İlerleme: 5600/48059 şehir tarandı. (Başarılı: 4128)
İlerleme: 5700/48059 şehir tarandı. (Başarılı: 4197)

Warning: Cannot load monthly/40564.csv.gz from https://data.meteostat.net/

İlerleme: 5800/48059 şehir tarandı. (Başarılı: 4266)
İlerleme: 5900/48059 şehir tarandı. (Başarılı: 4333)
İlerleme: 6000/48059 şehir tarandı. (Başarılı: 4406)

Warning: Cannot load monthly/DAAQ0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/94027.csv.gz from https://data.meteostat.net/

İlerleme: 6100/48059 şehir tarandı. (Başarılı: 4473)

Warning: Cannot load monthly/59362.csv.gz from https://data.meteostat.net/

İlerleme: 6200/48059 şehir tarandı. (Başarılı: 4539)

Warning: Cannot load monthly/SBCN0.csv.gz from https://data.meteostat.net/

İlerleme: 6300/48059 şehir tarandı. (Başarılı: 4608)

Warning: Cannot load monthly/83554.csv.gz from https://data.meteostat.net/

İlerleme: 6400/48059 şehir tarandı. (Başarılı: 4678)

Warning: Cannot load monthly/69535.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RPVN0.csv.gz from https://data.meteostat.net/

İlerleme: 6500/48059 şehir tarandı. (Başarılı: 4754)
İlerleme: 6600/48059 şehir tarandı. (Başarılı: 4828)
İlerleme: 6700/48059 şehir tarandı. (Başarılı: 4887)
İlerleme: 6800/48059 şehir tarandı. (Başarılı: 4951)
İlerleme: 6900/48059 şehir tarandı. (Başarılı: 5012)

Warning: Cannot load monthly/78447.csv.gz from https://data.meteostat.net/

İlerleme: 7000/48059 şehir tarandı. (Başarılı: 5083)
İlerleme: 7100/48059 şehir tarandı. (Başarılı: 5148)
İlerleme: 7200/48059 şehir tarandı. (Başarılı: 5213)
İlerleme: 7300/48059 şehir tarandı. (Başarılı: 5276)
İlerleme: 7400/48059 şehir tarandı. (Başarılı: 5347)

Warning: Cannot load monthly/64014.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/MMLC0.csv.gz from https://data.meteostat.net/

İlerleme: 7500/48059 şehir tarandı. (Başarılı: 5414)

Warning: Cannot load monthly/83033.csv.gz from https://data.meteostat.net/

İlerleme: 7600/48059 şehir tarandı. (Başarılı: 5480)
İlerleme: 7700/48059 şehir tarandı. (Başarılı: 5553)
İlerleme: 7800/48059 şehir tarandı. (Başarılı: 5628)
İlerleme: 7900/48059 şehir tarandı. (Başarılı: 5697)
İlerleme: 8000/48059 şehir tarandı. (Başarılı: 5769)

Warning: Cannot load monthly/80318.csv.gz from https://data.meteostat.net/

İlerleme: 8100/48059 şehir tarandı. (Başarılı: 5842)
İlerleme: 8200/48059 şehir tarandı. (Başarılı: 5909)

Warning: Cannot load monthly/KQCQ0.csv.gz from https://data.meteostat.net/

İlerleme: 8300/48059 şehir tarandı. (Başarılı: 5978)
İlerleme: 8400/48059 şehir tarandı. (Başarılı: 6040)

Warning: Cannot load monthly/SPEQ0.csv.gz from https://data.meteostat.net/

İlerleme: 8500/48059 şehir tarandı. (Başarılı: 6106)

Warning: Cannot load monthly/KQB70.csv.gz from https://data.meteostat.net/

İlerleme: 8600/48059 şehir tarandı. (Başarılı: 6170)

Warning: Cannot load monthly/64146.csv.gz from https://data.meteostat.net/

İlerleme: 8700/48059 şehir tarandı. (Başarılı: 6231)

Warning: Cannot load monthly/63329.csv.gz from https://data.meteostat.net/

İlerleme: 8800/48059 şehir tarandı. (Başarılı: 6302)

Warning: Cannot load monthly/98526.csv.gz from https://data.meteostat.net/

İlerleme: 8900/48059 şehir tarandı. (Başarılı: 6371)
İlerleme: 9000/48059 şehir tarandı. (Başarılı: 6433)
İlerleme: 9100/48059 şehir tarandı. (Başarılı: 6506)

Warning: Cannot load monthly/46735.csv.gz from https://data.meteostat.net/

İlerleme: 9200/48059 şehir tarandı. (Başarılı: 6580)

Warning: Cannot load monthly/RORE0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RPMW0.csv.gz from https://data.meteostat.net/

İlerleme: 9300/48059 şehir tarandı. (Başarılı: 6648)
İlerleme: 9400/48059 şehir tarandı. (Başarılı: 6715)
İlerleme: 9500/48059 şehir tarandı. (Başarılı: 6782)
İlerleme: 9600/48059 şehir tarandı. (Başarılı: 6844)

Warning: Cannot load monthly/86135.csv.gz from https://data.meteostat.net/

İlerleme: 9700/48059 şehir tarandı. (Başarılı: 6904)
İlerleme: 9800/48059 şehir tarandı. (Başarılı: 6972)
İlerleme: 9900/48059 şehir tarandı. (Başarılı: 7034)
İlerleme: 10000/48059 şehir tarandı. (Başarılı: 7104)
İlerleme: 10100/48059 şehir tarandı. (Başarılı: 7164)
İlerleme: 10200/48059 şehir tarandı. (Başarılı: 7226)
İlerleme: 10300/48059 şehir tarandı. (Başarılı: 7296)

Warning: Cannot load monthly/64034.csv.gz from https://data.meteostat.net/

İlerleme: 10400/48059 şehir tarandı. (Başarılı: 7365)
İlerleme: 10500/48059 şehir tarandı. (Başarılı: 7430)

Warning: Cannot load monthly/93246.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/93247.csv.gz from https://data.meteostat.net/

İlerleme: 10600/48059 şehir tarandı. (Başarılı: 7481)
İlerleme: 10700/48059 şehir tarandı. (Başarılı: 7542)
İlerleme: 10800/48059 şehir tarandı. (Başarılı: 7606)
İlerleme: 10900/48059 şehir tarandı. (Başarılı: 7668)
İlerleme: 11000/48059 şehir tarandı. (Başarılı: 7732)
İlerleme: 11100/48059 şehir tarandı. (Başarılı: 7799)
İlerleme: 11200/48059 şehir tarandı. (Başarılı: 7868)
İlerleme: 11300/48059 şehir tarandı. (Başarılı: 7936)
İlerleme: 11400/48059 şehir tarandı. (Başarılı: 7996)
İlerleme: 11500/48059 şehir tarandı. (Başarılı: 8070)
İlerleme: 11600/48059 şehir tarandı. (Başarılı: 8135)
İlerleme: 11700/48059 şehir tarandı. (Başarılı: 8197)
İlerleme: 11800/48059 şehir tarandı. (Başarılı: 8264)

Warning: Cannot load monthly/FAVY0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40637.csv.gz from https://data.meteostat.net/

İlerleme: 11900/48059 şehir tarandı. (Başarılı: 8338)
İlerleme: 12000/48059 şehir tarandı. (Başarılı: 8402)

Warning: Cannot load monthly/40634.csv.gz from https://data.meteostat.net/

İlerleme: 12100/48059 şehir tarandı. (Başarılı: 8466)

Warning: Cannot load monthly/HKIS0.csv.gz from https://data.meteostat.net/

İlerleme: 12200/48059 şehir tarandı. (Başarılı: 8531)

Warning: Cannot load monthly/62940.csv.gz from https://data.meteostat.net/

İlerleme: 12300/48059 şehir tarandı. (Başarılı: 8596)
İlerleme: 12400/48059 şehir tarandı. (Başarılı: 8661)

Warning: Cannot load monthly/94787.csv.gz from https://data.meteostat.net/

İlerleme: 12500/48059 şehir tarandı. (Başarılı: 8725)
İlerleme: 12600/48059 şehir tarandı. (Başarılı: 8791)
İlerleme: 12700/48059 şehir tarandı. (Başarılı: 8863)
İlerleme: 12800/48059 şehir tarandı. (Başarılı: 8928)

Warning: Cannot load monthly/60270.csv.gz from https://data.meteostat.net/

İlerleme: 12900/48059 şehir tarandı. (Başarılı: 8990)

Warning: Cannot load monthly/CWVE0.csv.gz from https://data.meteostat.net/

İlerleme: 13000/48059 şehir tarandı. (Başarılı: 9050)
İlerleme: 13100/48059 şehir tarandı. (Başarılı: 9111)
İlerleme: 13200/48059 şehir tarandı. (Başarılı: 9179)
İlerleme: 13300/48059 şehir tarandı. (Başarılı: 9241)
İlerleme: 13400/48059 şehir tarandı. (Başarılı: 9306)
İlerleme: 13500/48059 şehir tarandı. (Başarılı: 9373)
İlerleme: 13600/48059 şehir tarandı. (Başarılı: 9443)

Warning: Cannot load monthly/61873.csv.gz from https://data.meteostat.net/

İlerleme: 13700/48059 şehir tarandı. (Başarılı: 9497)
İlerleme: 13800/48059 şehir tarandı. (Başarılı: 9552)
İlerleme: 13900/48059 şehir tarandı. (Başarılı: 9612)
İlerleme: 14000/48059 şehir tarandı. (Başarılı: 9671)
İlerleme: 14100/48059 şehir tarandı. (Başarılı: 9737)
İlerleme: 14200/48059 şehir tarandı. (Başarılı: 9804)
İlerleme: 14300/48059 şehir tarandı. (Başarılı: 9876)
İlerleme: 14400/48059 şehir tarandı. (Başarılı: 9936)
İlerleme: 14500/48059 şehir tarandı. (Başarılı: 10002)
İlerleme: 14600/48059 şehir tarandı. (Başarılı: 10064)
İlerleme: 14700/48059 şehir tarandı. (Başarılı: 10125)
İlerleme: 14800/48059 şehir tarandı. (Başarılı: 10192)
İlerleme: 14900/48059 şehir tarandı. (Başarılı: 10258)
İlerleme: 15000/48059 şehir tarandı. (Başarılı: 10320)

Warning: Cannot load monthly/91742.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/91739.csv.gz from https://data.meteostat.net/

İlerleme: 15100/48059 şehir tarandı. (Başarılı: 10387)
İlerleme: 15200/48059 şehir tarandı. (Başarılı: 10458)
İlerleme: 15300/48059 şehir tarandı. (Başarılı: 10526)
İlerleme: 15400/48059 şehir tarandı. (Başarılı: 10590)

Warning: Cannot load monthly/43413.csv.gz from https://data.meteostat.net/

İlerleme: 15500/48059 şehir tarandı. (Başarılı: 10648)
İlerleme: 15600/48059 şehir tarandı. (Başarılı: 10717)

Warning: Cannot load monthly/78451.csv.gz from https://data.meteostat.net/

İlerleme: 15700/48059 şehir tarandı. (Başarılı: 10782)
İlerleme: 15800/48059 şehir tarandı. (Başarılı: 10849)
İlerleme: 15900/48059 şehir tarandı. (Başarılı: 10905)
İlerleme: 16000/48059 şehir tarandı. (Başarılı: 10963)

Warning: Cannot load monthly/KQOW0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SATM0.csv.gz from https://data.meteostat.net/

İlerleme: 16100/48059 şehir tarandı. (Başarılı: 11023)
İlerleme: 16200/48059 şehir tarandı. (Başarılı: 11079)
İlerleme: 16300/48059 şehir tarandı. (Başarılı: 11149)

Warning: Cannot load monthly/86223.csv.gz from https://data.meteostat.net/

İlerleme: 16400/48059 şehir tarandı. (Başarılı: 11208)
İlerleme: 16500/48059 şehir tarandı. (Başarılı: 11268)
İlerleme: 16600/48059 şehir tarandı. (Başarılı: 11339)
İlerleme: 16700/48059 şehir tarandı. (Başarılı: 11406)
İlerleme: 16800/48059 şehir tarandı. (Başarılı: 11476)
İlerleme: 16900/48059 şehir tarandı. (Başarılı: 11536)
İlerleme: 17000/48059 şehir tarandı. (Başarılı: 11606)

Warning: Cannot load monthly/78652.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40604.csv.gz from https://data.meteostat.net/

İlerleme: 17100/48059 şehir tarandı. (Başarılı: 11669)
İlerleme: 17200/48059 şehir tarandı. (Başarılı: 11720)
İlerleme: 17300/48059 şehir tarandı. (Başarılı: 11793)
İlerleme: 17400/48059 şehir tarandı. (Başarılı: 11854)

Warning: Cannot load monthly/CWIU0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/CWIA0.csv.gz from https://data.meteostat.net/

İlerleme: 17500/48059 şehir tarandı. (Başarılı: 11919)
İlerleme: 17600/48059 şehir tarandı. (Başarılı: 11978)

Warning: Cannot load monthly/60200.csv.gz from https://data.meteostat.net/

İlerleme: 17700/48059 şehir tarandı. (Başarılı: 12033)
İlerleme: 17800/48059 şehir tarandı. (Başarılı: 12101)

Warning: Cannot load monthly/46759.csv.gz from https://data.meteostat.net/

İlerleme: 17900/48059 şehir tarandı. (Başarılı: 12169)
İlerleme: 18000/48059 şehir tarandı. (Başarılı: 12232)

Warning: Cannot load monthly/K2CB0.csv.gz from https://data.meteostat.net/

İlerleme: 18100/48059 şehir tarandı. (Başarılı: 12300)
İlerleme: 18200/48059 şehir tarandı. (Başarılı: 12371)
İlerleme: 18300/48059 şehir tarandı. (Başarılı: 12436)
İlerleme: 18400/48059 şehir tarandı. (Başarılı: 12502)
İlerleme: 18500/48059 şehir tarandı. (Başarılı: 12563)
İlerleme: 18600/48059 şehir tarandı. (Başarılı: 12635)
İlerleme: 18700/48059 şehir tarandı. (Başarılı: 12704)

Warning: Cannot load monthly/40642.csv.gz from https://data.meteostat.net/

İlerleme: 18800/48059 şehir tarandı. (Başarılı: 12760)
İlerleme: 18900/48059 şehir tarandı. (Başarılı: 12827)
İlerleme: 19000/48059 şehir tarandı. (Başarılı: 12893)
İlerleme: 19100/48059 şehir tarandı. (Başarılı: 12961)

Warning: Cannot load monthly/72558.csv.gz from https://data.meteostat.net/

İlerleme: 19200/48059 şehir tarandı. (Başarılı: 13025)

Warning: Cannot load monthly/64015.csv.gz from https://data.meteostat.net/

İlerleme: 19300/48059 şehir tarandı. (Başarılı: 13087)

Warning: Cannot load monthly/KQVE0.csv.gz from https://data.meteostat.net/

İlerleme: 19400/48059 şehir tarandı. (Başarılı: 13149)
İlerleme: 19500/48059 şehir tarandı. (Başarılı: 13215)
İlerleme: 19600/48059 şehir tarandı. (Başarılı: 13271)
İlerleme: 19700/48059 şehir tarandı. (Başarılı: 13340)
İlerleme: 19800/48059 şehir tarandı. (Başarılı: 13403)
İlerleme: 19900/48059 şehir tarandı. (Başarılı: 13465)

Warning: Cannot load monthly/44224.csv.gz from https://data.meteostat.net/

İlerleme: 20000/48059 şehir tarandı. (Başarılı: 13531)
İlerleme: 20100/48059 şehir tarandı. (Başarılı: 13597)
İlerleme: 20200/48059 şehir tarandı. (Başarılı: 13661)
İlerleme: 20300/48059 şehir tarandı. (Başarılı: 13731)
İlerleme: 20400/48059 şehir tarandı. (Başarılı: 13799)
İlerleme: 20500/48059 şehir tarandı. (Başarılı: 13869)
İlerleme: 20600/48059 şehir tarandı. (Başarılı: 13937)

Warning: Cannot load monthly/VLVV0.csv.gz from https://data.meteostat.net/

İlerleme: 20700/48059 şehir tarandı. (Başarılı: 13998)
İlerleme: 20800/48059 şehir tarandı. (Başarılı: 14066)
İlerleme: 20900/48059 şehir tarandı. (Başarılı: 14128)
İlerleme: 21000/48059 şehir tarandı. (Başarılı: 14193)
İlerleme: 21100/48059 şehir tarandı. (Başarılı: 14265)

Warning: Cannot load monthly/81208.csv.gz from https://data.meteostat.net/

İlerleme: 21200/48059 şehir tarandı. (Başarılı: 14326)
İlerleme: 21300/48059 şehir tarandı. (Başarılı: 14395)
İlerleme: 21400/48059 şehir tarandı. (Başarılı: 14451)
İlerleme: 21500/48059 şehir tarandı. (Başarılı: 14512)
İlerleme: 21600/48059 şehir tarandı. (Başarılı: 14576)
İlerleme: 21700/48059 şehir tarandı. (Başarılı: 14644)
İlerleme: 21800/48059 şehir tarandı. (Başarılı: 14710)
İlerleme: 21900/48059 şehir tarandı. (Başarılı: 14775)
İlerleme: 22000/48059 şehir tarandı. (Başarılı: 14846)
İlerleme: 22100/48059 şehir tarandı. (Başarılı: 14914)
İlerleme: 22200/48059 şehir tarandı. (Başarılı: 14975)
İlerleme: 22300/48059 şehir tarandı. (Başarılı: 15041)
İlerleme: 22400/48059 şehir tarandı. (Başarılı: 15107)
İlerleme: 22500/48059 şehir tarandı. (Başarılı: 15169)
İlerleme: 22600/48059 şehir tarandı. (Başarılı: 15241)

Warning: Cannot load monthly/SESC0.csv.gz from https://data.meteostat.net/

İlerleme: 22700/48059 şehir tarandı. (Başarılı: 15305)
İlerleme: 22800/48059 şehir tarandı. (Başarılı: 15372)
İlerleme: 22900/48059 şehir tarandı. (Başarılı: 15445)
İlerleme: 23000/48059 şehir tarandı. (Başarılı: 15510)
İlerleme: 23100/48059 şehir tarandı. (Başarılı: 15582)
İlerleme: 23200/48059 şehir tarandı. (Başarılı: 15639)
İlerleme: 23300/48059 şehir tarandı. (Başarılı: 15710)
İlerleme: 23400/48059 şehir tarandı. (Başarılı: 15774)
İlerleme: 23500/48059 şehir tarandı. (Başarılı: 15842)
İlerleme: 23600/48059 şehir tarandı. (Başarılı: 15912)
İlerleme: 23700/48059 şehir tarandı. (Başarılı: 15977)
İlerleme: 23800/48059 şehir tarandı. (Başarılı: 16049)

Warning: Cannot load monthly/40629.csv.gz from https://data.meteostat.net/

İlerleme: 23900/48059 şehir tarandı. (Başarılı: 16109)

Warning: Cannot load monthly/68040.csv.gz from https://data.meteostat.net/

İlerleme: 24000/48059 şehir tarandı. (Başarılı: 16169)
İlerleme: 24100/48059 şehir tarandı. (Başarılı: 16236)
İlerleme: 24200/48059 şehir tarandı. (Başarılı: 16316)

Warning: Cannot load monthly/61891.csv.gz from https://data.meteostat.net/

İlerleme: 24300/48059 şehir tarandı. (Başarılı: 16389)
İlerleme: 24400/48059 şehir tarandı. (Başarılı: 16463)
İlerleme: 24500/48059 şehir tarandı. (Başarılı: 16531)

Warning: Cannot load monthly/94085.csv.gz from https://data.meteostat.net/

İlerleme: 24600/48059 şehir tarandı. (Başarılı: 16601)
İlerleme: 24700/48059 şehir tarandı. (Başarılı: 16666)

Warning: Cannot load monthly/40976.csv.gz from https://data.meteostat.net/

İlerleme: 24800/48059 şehir tarandı. (Başarılı: 16726)
İlerleme: 24900/48059 şehir tarandı. (Başarılı: 16794)
İlerleme: 25000/48059 şehir tarandı. (Başarılı: 16856)
İlerleme: 25100/48059 şehir tarandı. (Başarılı: 16926)
İlerleme: 25200/48059 şehir tarandı. (Başarılı: 16996)

Warning: Cannot load monthly/86296.csv.gz from https://data.meteostat.net/

İlerleme: 25300/48059 şehir tarandı. (Başarılı: 17062)
İlerleme: 25400/48059 şehir tarandı. (Başarılı: 17127)
İlerleme: 25500/48059 şehir tarandı. (Başarılı: 17196)
İlerleme: 25600/48059 şehir tarandı. (Başarılı: 17263)
İlerleme: 25700/48059 şehir tarandı. (Başarılı: 17333)

Warning: Cannot load monthly/SCSR0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SAVD0.csv.gz from https://data.meteostat.net/

İlerleme: 25800/48059 şehir tarandı. (Başarılı: 17399)
İlerleme: 25900/48059 şehir tarandı. (Başarılı: 17471)
İlerleme: 26000/48059 şehir tarandı. (Başarılı: 17544)

Warning: Cannot load monthly/61886.csv.gz from https://data.meteostat.net/

İlerleme: 26100/48059 şehir tarandı. (Başarılı: 17611)
İlerleme: 26200/48059 şehir tarandı. (Başarılı: 17679)
İlerleme: 26300/48059 şehir tarandı. (Başarılı: 17742)

Warning: Cannot load monthly/KTDO0.csv.gz from https://data.meteostat.net/

İlerleme: 26400/48059 şehir tarandı. (Başarılı: 17821)
İlerleme: 26500/48059 şehir tarandı. (Başarılı: 17890)
İlerleme: 26600/48059 şehir tarandı. (Başarılı: 17953)
İlerleme: 26700/48059 şehir tarandı. (Başarılı: 18025)
İlerleme: 26800/48059 şehir tarandı. (Başarılı: 18097)
İlerleme: 26900/48059 şehir tarandı. (Başarılı: 18155)
İlerleme: 27000/48059 şehir tarandı. (Başarılı: 18225)
İlerleme: 27100/48059 şehir tarandı. (Başarılı: 18284)
İlerleme: 27200/48059 şehir tarandı. (Başarılı: 18349)
İlerleme: 27300/48059 şehir tarandı. (Başarılı: 18413)
İlerleme: 27400/48059 şehir tarandı. (Başarılı: 18487)

Warning: Cannot load monthly/RJDO0.csv.gz from https://data.meteostat.net/

İlerleme: 27500/48059 şehir tarandı. (Başarılı: 18550)
İlerleme: 27600/48059 şehir tarandı. (Başarılı: 18622)
İlerleme: 27700/48059 şehir tarandı. (Başarılı: 18684)

Warning: Cannot load monthly/KRJD0.csv.gz from https://data.meteostat.net/

İlerleme: 27800/48059 şehir tarandı. (Başarılı: 18756)

Warning: Cannot load monthly/72784.csv.gz from https://data.meteostat.net/

İlerleme: 27900/48059 şehir tarandı. (Başarılı: 18826)

Warning: Cannot load monthly/63476.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/K5T60.csv.gz from https://data.meteostat.net/

İlerleme: 28000/48059 şehir tarandı. (Başarılı: 18900)
İlerleme: 28100/48059 şehir tarandı. (Başarılı: 18957)
İlerleme: 28200/48059 şehir tarandı. (Başarılı: 19021)
İlerleme: 28300/48059 şehir tarandı. (Başarılı: 19083)

Warning: Cannot load monthly/41382.csv.gz from https://data.meteostat.net/

İlerleme: 28400/48059 şehir tarandı. (Başarılı: 19149)
İlerleme: 28500/48059 şehir tarandı. (Başarılı: 19218)

Warning: Cannot load monthly/KQIW0.csv.gz from https://data.meteostat.net/

İlerleme: 28600/48059 şehir tarandı. (Başarılı: 19287)
İlerleme: 28700/48059 şehir tarandı. (Başarılı: 19354)

Warning: Cannot load monthly/72305.csv.gz from https://data.meteostat.net/

İlerleme: 28800/48059 şehir tarandı. (Başarılı: 19422)
İlerleme: 28900/48059 şehir tarandı. (Başarılı: 19491)
İlerleme: 29000/48059 şehir tarandı. (Başarılı: 19557)

Warning: Cannot load monthly/94784.csv.gz from https://data.meteostat.net/

İlerleme: 29100/48059 şehir tarandı. (Başarılı: 19626)

Warning: Cannot load monthly/61878.csv.gz from https://data.meteostat.net/

İlerleme: 29200/48059 şehir tarandı. (Başarılı: 19701)
İlerleme: 29300/48059 şehir tarandı. (Başarılı: 19772)
İlerleme: 29400/48059 şehir tarandı. (Başarılı: 19822)
İlerleme: 29500/48059 şehir tarandı. (Başarılı: 19894)
İlerleme: 29600/48059 şehir tarandı. (Başarılı: 19965)
İlerleme: 29700/48059 şehir tarandı. (Başarılı: 20031)
İlerleme: 29800/48059 şehir tarandı. (Başarılı: 20100)
İlerleme: 29900/48059 şehir tarandı. (Başarılı: 20164)
İlerleme: 30000/48059 şehir tarandı. (Başarılı: 20229)
İlerleme: 30100/48059 şehir tarandı. (Başarılı: 20293)
İlerleme: 30200/48059 şehir tarandı. (Başarılı: 20363)

Warning: Cannot load monthly/VTPL0.csv.gz from https://data.meteostat.net/

İlerleme: 30300/48059 şehir tarandı. (Başarılı: 20431)
İlerleme: 30400/48059 şehir tarandı. (Başarılı: 20494)
İlerleme: 30500/48059 şehir tarandı. (Başarılı: 20557)
İlerleme: 30600/48059 şehir tarandı. (Başarılı: 20626)
İlerleme: 30700/48059 şehir tarandı. (Başarılı: 20698)

Warning: Cannot load monthly/FMNO0.csv.gz from https://data.meteostat.net/

İlerleme: 30800/48059 şehir tarandı. (Başarılı: 20744)

Warning: Cannot load monthly/71124.csv.gz from https://data.meteostat.net/

İlerleme: 30900/48059 şehir tarandı. (Başarılı: 20808)
İlerleme: 31000/48059 şehir tarandı. (Başarılı: 20882)
İlerleme: 31100/48059 şehir tarandı. (Başarılı: 20943)

Warning: Cannot load monthly/FAES0.csv.gz from https://data.meteostat.net/

İlerleme: 31200/48059 şehir tarandı. (Başarılı: 21012)
İlerleme: 31300/48059 şehir tarandı. (Başarılı: 21082)
İlerleme: 31400/48059 şehir tarandı. (Başarılı: 21152)
İlerleme: 31500/48059 şehir tarandı. (Başarılı: 21221)
İlerleme: 31600/48059 şehir tarandı. (Başarılı: 21290)
İlerleme: 31700/48059 şehir tarandı. (Başarılı: 21363)
İlerleme: 31800/48059 şehir tarandı. (Başarılı: 21433)
İlerleme: 31900/48059 şehir tarandı. (Başarılı: 21507)
İlerleme: 32000/48059 şehir tarandı. (Başarılı: 21571)
İlerleme: 32100/48059 şehir tarandı. (Başarılı: 21643)
İlerleme: 32200/48059 şehir tarandı. (Başarılı: 21719)
İlerleme: 32300/48059 şehir tarandı. (Başarılı: 21790)
İlerleme: 32400/48059 şehir tarandı. (Başarılı: 21852)
İlerleme: 32500/48059 şehir tarandı. (Başarılı: 21905)

Warning: Cannot load monthly/CWKA0.csv.gz from https://data.meteostat.net/

İlerleme: 32600/48059 şehir tarandı. (Başarılı: 21974)
İlerleme: 32700/48059 şehir tarandı. (Başarılı: 22042)
İlerleme: 32800/48059 şehir tarandı. (Başarılı: 22113)
İlerleme: 32900/48059 şehir tarandı. (Başarılı: 22178)
İlerleme: 33000/48059 şehir tarandı. (Başarılı: 22247)
İlerleme: 33100/48059 şehir tarandı. (Başarılı: 22312)

Warning: Cannot load monthly/FALC0.csv.gz from https://data.meteostat.net/

İlerleme: 33200/48059 şehir tarandı. (Başarılı: 22375)
İlerleme: 33300/48059 şehir tarandı. (Başarılı: 22444)
İlerleme: 33400/48059 şehir tarandı. (Başarılı: 22507)
İlerleme: 33500/48059 şehir tarandı. (Başarılı: 22576)
İlerleme: 33600/48059 şehir tarandı. (Başarılı: 22658)
İlerleme: 33700/48059 şehir tarandı. (Başarılı: 22730)
İlerleme: 33800/48059 şehir tarandı. (Başarılı: 22804)
İlerleme: 33900/48059 şehir tarandı. (Başarılı: 22872)
İlerleme: 34000/48059 şehir tarandı. (Başarılı: 22941)
İlerleme: 34100/48059 şehir tarandı. (Başarılı: 23010)
İlerleme: 34200/48059 şehir tarandı. (Başarılı: 23070)
İlerleme: 34300/48059 şehir tarandı. (Başarılı: 23125)
İlerleme: 34400/48059 şehir tarandı. (Başarılı: 23194)
İlerleme: 34500/48059 şehir tarandı. (Başarılı: 23264)
İlerleme: 34600/48059 şehir tarandı. (Başarılı: 23330)
İlerleme: 34700/48059 şehir tarandı. (Başarılı: 23401)

Warning: Cannot load monthly/FAMR0.csv.gz from https://data.meteostat.net/

İlerleme: 34800/48059 şehir tarandı. (Başarılı: 23461)
İlerleme: 34900/48059 şehir tarandı. (Başarılı: 23531)
İlerleme: 35000/48059 şehir tarandı. (Başarılı: 23593)
İlerleme: 35100/48059 şehir tarandı. (Başarılı: 23661)
İlerleme: 35200/48059 şehir tarandı. (Başarılı: 23723)
İlerleme: 35300/48059 şehir tarandı. (Başarılı: 23801)
İlerleme: 35400/48059 şehir tarandı. (Başarılı: 23866)
İlerleme: 35500/48059 şehir tarandı. (Başarılı: 23933)
İlerleme: 35600/48059 şehir tarandı. (Başarılı: 24002)
İlerleme: 35700/48059 şehir tarandı. (Başarılı: 24069)

Warning: Cannot load monthly/VTCB0.csv.gz from https://data.meteostat.net/

İlerleme: 35800/48059 şehir tarandı. (Başarılı: 24135)
İlerleme: 35900/48059 şehir tarandı. (Başarılı: 24208)
İlerleme: 36000/48059 şehir tarandı. (Başarılı: 24275)
İlerleme: 36100/48059 şehir tarandı. (Başarılı: 24346)
İlerleme: 36200/48059 şehir tarandı. (Başarılı: 24410)

Warning: Cannot load monthly/FMMU0.csv.gz from https://data.meteostat.net/

İlerleme: 36300/48059 şehir tarandı. (Başarılı: 24464)

Warning: Cannot load monthly/FABN0.csv.gz from https://data.meteostat.net/

İlerleme: 36400/48059 şehir tarandı. (Başarılı: 24530)
İlerleme: 36500/48059 şehir tarandı. (Başarılı: 24599)
İlerleme: 36600/48059 şehir tarandı. (Başarılı: 24670)
İlerleme: 36700/48059 şehir tarandı. (Başarılı: 24732)
İlerleme: 36800/48059 şehir tarandı. (Başarılı: 24801)
İlerleme: 36900/48059 şehir tarandı. (Başarılı: 24870)
İlerleme: 37000/48059 şehir tarandı. (Başarılı: 24934)

Warning: Cannot load monthly/66130.csv.gz from https://data.meteostat.net/

İlerleme: 37100/48059 şehir tarandı. (Başarılı: 25002)
İlerleme: 37200/48059 şehir tarandı. (Başarılı: 25068)
İlerleme: 37300/48059 şehir tarandı. (Başarılı: 25135)
İlerleme: 37400/48059 şehir tarandı. (Başarılı: 25189)
İlerleme: 37500/48059 şehir tarandı. (Başarılı: 25264)
İlerleme: 37600/48059 şehir tarandı. (Başarılı: 25327)
İlerleme: 37700/48059 şehir tarandı. (Başarılı: 25404)

Warning: Cannot load monthly/71268.csv.gz from https://data.meteostat.net/

İlerleme: 37800/48059 şehir tarandı. (Başarılı: 25476)
İlerleme: 37900/48059 şehir tarandı. (Başarılı: 25542)
İlerleme: 38000/48059 şehir tarandı. (Başarılı: 25611)
İlerleme: 38100/48059 şehir tarandı. (Başarılı: 25685)
İlerleme: 38200/48059 şehir tarandı. (Başarılı: 25755)
İlerleme: 38300/48059 şehir tarandı. (Başarılı: 25815)
İlerleme: 38400/48059 şehir tarandı. (Başarılı: 25879)
İlerleme: 38500/48059 şehir tarandı. (Başarılı: 25953)
İlerleme: 38600/48059 şehir tarandı. (Başarılı: 26017)
İlerleme: 38700/48059 şehir tarandı. (Başarılı: 26063)
İlerleme: 38800/48059 şehir tarandı. (Başarılı: 26123)
İlerleme: 38900/48059 şehir tarandı. (Başarılı: 26184)
İlerleme: 39000/48059 şehir tarandı. (Başarılı: 26249)
İlerleme: 39100/48059 şehir tarandı. (Başarılı: 26317)
İlerleme: 39200/48059 şehir tarandı. (Başarılı: 26385)
İlerleme: 39300/48059 şehir tarandı. (Başarılı: 26442)
İlerleme: 39400/48059 şehir tarandı. (Başarılı: 26508)

Warning: Cannot load monthly/KCZD0.csv.gz from https://data.meteostat.net/

İlerleme: 39500/48059 şehir tarandı. (Başarılı: 26581)
İlerleme: 39600/48059 şehir tarandı. (Başarılı: 26649)
İlerleme: 39700/48059 şehir tarandı. (Başarılı: 26718)

Warning: Cannot load monthly/PAJV0.csv.gz from https://data.meteostat.net/

İlerleme: 39800/48059 şehir tarandı. (Başarılı: 26786)
İlerleme: 39900/48059 şehir tarandı. (Başarılı: 26837)
İlerleme: 40000/48059 şehir tarandı. (Başarılı: 26898)
İlerleme: 40100/48059 şehir tarandı. (Başarılı: 26967)
İlerleme: 40200/48059 şehir tarandı. (Başarılı: 27043)
İlerleme: 40300/48059 şehir tarandı. (Başarılı: 27115)
İlerleme: 40400/48059 şehir tarandı. (Başarılı: 27179)
İlerleme: 40500/48059 şehir tarandı. (Başarılı: 27242)
İlerleme: 40600/48059 şehir tarandı. (Başarılı: 27305)
İlerleme: 40700/48059 şehir tarandı. (Başarılı: 27373)
İlerleme: 40800/48059 şehir tarandı. (Başarılı: 27439)
İlerleme: 40900/48059 şehir tarandı. (Başarılı: 27516)
İlerleme: 41000/48059 şehir tarandı. (Başarılı: 27571)
İlerleme: 41100/48059 şehir tarandı. (Başarılı: 27642)
İlerleme: 41200/48059 şehir tarandı. (Başarılı: 27705)
İlerleme: 41300/48059 şehir tarandı. (Başarılı: 27774)
İlerleme: 41400/48059 şehir tarandı. (Başarılı: 27846)
İlerleme: 41500/48059 şehir tarandı. (Başarılı: 27910)
İlerleme: 41600/48059 şehir tarandı. (Başarılı: 27943)
İlerleme: 41700/48059 şehir tarandı. (Başarılı: 28009)
İlerleme: 41800/48059 şehir tarandı. (Başarılı: 28079)
İlerleme: 41900/48059 şehir tarandı. (Başarılı: 28138)

Warning: Cannot load monthly/40946.csv.gz from https://data.meteostat.net/

İlerleme: 42000/48059 şehir tarandı. (Başarılı: 28208)
İlerleme: 42100/48059 şehir tarandı. (Başarılı: 28274)
İlerleme: 42200/48059 şehir tarandı. (Başarılı: 28339)
İlerleme: 42300/48059 şehir tarandı. (Başarılı: 28401)
İlerleme: 42400/48059 şehir tarandı. (Başarılı: 28462)
İlerleme: 42500/48059 şehir tarandı. (Başarılı: 28532)
İlerleme: 42600/48059 şehir tarandı. (Başarılı: 28602)
İlerleme: 42700/48059 şehir tarandı. (Başarılı: 28668)
İlerleme: 42800/48059 şehir tarandı. (Başarılı: 28739)
İlerleme: 42900/48059 şehir tarandı. (Başarılı: 28800)
İlerleme: 43000/48059 şehir tarandı. (Başarılı: 28864)
İlerleme: 43100/48059 şehir tarandı. (Başarılı: 28932)
İlerleme: 43200/48059 şehir tarandı. (Başarılı: 28995)
İlerleme: 43300/48059 şehir tarandı. (Başarılı: 29059)
İlerleme: 43400/48059 şehir tarandı. (Başarılı: 29116)
İlerleme: 43500/48059 şehir tarandı. (Başarılı: 29187)
İlerleme: 43600/48059 şehir tarandı. (Başarılı: 29253)
İlerleme: 43700/48059 şehir tarandı. (Başarılı: 29317)
İlerleme: 43800/48059 şehir tarandı. (Başarılı: 29385)

Warning: Cannot load monthly/MPNU0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/MPCI0.csv.gz from https://data.meteostat.net/

İlerleme: 43900/48059 şehir tarandı. (Başarılı: 29454)
İlerleme: 44000/48059 şehir tarandı. (Başarılı: 29522)
İlerleme: 44100/48059 şehir tarandı. (Başarılı: 29587)
İlerleme: 44200/48059 şehir tarandı. (Başarılı: 29647)
İlerleme: 44300/48059 şehir tarandı. (Başarılı: 29719)
İlerleme: 44400/48059 şehir tarandı. (Başarılı: 29786)
İlerleme: 44500/48059 şehir tarandı. (Başarılı: 29853)
İlerleme: 44600/48059 şehir tarandı. (Başarılı: 29930)
İlerleme: 44700/48059 şehir tarandı. (Başarılı: 29989)

Warning: Cannot load monthly/PAUO0.csv.gz from https://data.meteostat.net/

İlerleme: 44800/48059 şehir tarandı. (Başarılı: 30031)
İlerleme: 44900/48059 şehir tarandı. (Başarılı: 30101)
İlerleme: 45000/48059 şehir tarandı. (Başarılı: 30167)
İlerleme: 45100/48059 şehir tarandı. (Başarılı: 30238)
İlerleme: 45200/48059 şehir tarandı. (Başarılı: 30307)
İlerleme: 45300/48059 şehir tarandı. (Başarılı: 30372)
İlerleme: 45400/48059 şehir tarandı. (Başarılı: 30444)
İlerleme: 45500/48059 şehir tarandı. (Başarılı: 30520)
İlerleme: 45600/48059 şehir tarandı. (Başarılı: 30584)
İlerleme: 45700/48059 şehir tarandı. (Başarılı: 30649)
İlerleme: 45800/48059 şehir tarandı. (Başarılı: 30723)
İlerleme: 45900/48059 şehir tarandı. (Başarılı: 30792)
İlerleme: 46000/48059 şehir tarandı. (Başarılı: 30863)
İlerleme: 46100/48059 şehir tarandı. (Başarılı: 30939)
İlerleme: 46200/48059 şehir tarandı. (Başarılı: 31010)
İlerleme: 46300/48059 şehir tarandı. (Başarılı: 31080)
İlerleme: 46400/48059 şehir tarandı. (Başarılı: 31147)
İlerleme: 46500/48059 şehir tarandı. (Başarılı: 31209)
İlerleme: 46600/48059 şehir tarandı. (Başarılı: 31272)

Warning: Cannot load monthly/94527.csv.gz from https://data.meteostat.net/

İlerleme: 46700/48059 şehir tarandı. (Başarılı: 31342)

Warning: Cannot load monthly/94869.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/94044.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/FYMH0.csv.gz from https://data.meteostat.net/

İlerleme: 46800/48059 şehir tarandı. (Başarılı: 31408)
İlerleme: 46900/48059 şehir tarandı. (Başarılı: 31474)

Warning: Cannot load monthly/FAKP0.csv.gz from https://data.meteostat.net/

İlerleme: 47000/48059 şehir tarandı. (Başarılı: 31543)
İlerleme: 47100/48059 şehir tarandı. (Başarılı: 31610)

Warning: Cannot load monthly/68038.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SAWM0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/PGTI0.csv.gz from https://data.meteostat.net/

İlerleme: 47200/48059 şehir tarandı. (Başarılı: 31672)
İlerleme: 47300/48059 şehir tarandı. (Başarılı: 31737)

Warning: Cannot load monthly/HSNA0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SAVR0.csv.gz from https://data.meteostat.net/

İlerleme: 47400/48059 şehir tarandı. (Başarılı: 31803)

Warning: Cannot load monthly/91740.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/91737.csv.gz from https://data.meteostat.net/

İlerleme: 47500/48059 şehir tarandı. (Başarılı: 31874)

Warning: Cannot load monthly/FYBG0.csv.gz from https://data.meteostat.net/

İlerleme: 47600/48059 şehir tarandı. (Başarılı: 31944)
İlerleme: 47700/48059 şehir tarandı. (Başarılı: 32022)

Warning: Cannot load monthly/94482.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/04310.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SPAS0.csv.gz from https://data.meteostat.net/

İlerleme: 47800/48059 şehir tarandı. (Başarılı: 32067)
İlerleme: 47900/48059 şehir tarandı. (Başarılı: 32121)

Warning: Cannot load monthly/FTTZ0.csv.gz from https://data.meteostat.net/

İlerleme: 48000/48059 şehir tarandı. (Başarılı: 32179)

==================================================
İŞLEM TAMAMLANDI
Toplam Taranan: 48059
Başarılı Veri (Şehir Bazlı): 32207
Hatalar 'hatali_sehirler_log.txt' dosyasına kaydedildi.
==================================================

SONUÇ DATAFRAME (İLK 20 SATIR):
         time     city_id city_name country  tavg  tmin  tmax     lat  \
0  2012-01-01  1392685764     Tokyo      JP   4.8   1.8   8.3  35.687
1  2012-02-01  1392685764     Tokyo      JP   5.4   2.2   9.1  35.687
2  2012-03-01  1392685764     Tokyo      JP   8.8   5.3  12.5  35.687
3  2012-04-01  1392685764     Tokyo      JP  14.5  11.0  18.5  35.687
4  2012-05-01  1392685764     Tokyo      JP  19.6  16.1  23.6  35.687
5  2012-06-01  1392685764     Tokyo      JP  21.4  18.6  24.8  35.687
6  2012-07-01  1392685764     Tokyo      JP  26.4  23.5  30.1  35.687
7  2012-08-01  1392685764     Tokyo      JP  29.1  26.3  33.1  35.687
8  2012-09-01  1392685764     Tokyo      JP  26.2  23.3  29.8  35.687
9  2012-10-01  1392685764     Tokyo      JP  19.4  16.2  23.0  35.687
10 2012-11-01  1392685764     Tokyo      JP  12.7   9.6  16.3  35.687
11 2012-12-01  1392685764     Tokyo      JP   7.3   3.8  11.2  35.687
12 2013-01-01  1392685764     Tokyo      JP   5.5   1.8   9.6  35.687
13 2013-02-01  1392685764     Tokyo      JP   6.2   2.7  10.3  35.687
14 2013-03-01  1392685764     Tokyo      JP  12.1   7.9  16.4  35.687
15 2013-04-01  1392685764     Tokyo      JP  15.2  10.8  19.2  35.687
16 2013-05-01  1392685764     Tokyo      JP  19.8  16.0  24.1  35.687
17 2013-06-01  1392685764     Tokyo      JP  22.9  20.0  26.5  35.687
18 2013-07-01  1392685764     Tokyo      JP  27.3  24.2  31.4  35.687
19 2013-08-01  1392685764     Tokyo      JP  29.2  26.0  33.2  35.687

         lng
0   139.7495
1   139.7495
2   139.7495
3   139.7495
4   139.7495
5   139.7495
6   139.7495
7   139.7495
8   139.7495
9   139.7495
10  139.7495
11  139.7495
12  139.7495
13  139.7495
14  139.7495
15  139.7495
16  139.7495
17  139.7495
18  139.7495
19  139.7495

DATAFRAME BİLGİSİ:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4456085 entries, 0 to 4456084
Data columns (total 9 columns):
 #   Column     Dtype
---  ------     -----
 0   time       datetime64[ns]
 1   city_id    int64
 2   city_name  object
 3   country    object
 4   tavg       Float64
 5   tmin       Float64
 6   tmax       Float64
 7   lat        float64
 8   lng        float64
dtypes: Float64(3), datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 318.7+ MB
None

Veriler 'tum_dunya_hava_verileri.csv' dosyasına kaydediliyor...
Kayıt işlemi başarılı.

In [22]:
import pandas as pd
import os
from datetime import datetime
from meteostat import Point, Monthly
from meteostat import Stations

polatli = Point(39.5842, 32.1472)

In [23]:
stations = Stations()
stations = stations.nearby(39.5842, 32.1472)
station = stations.fetch(1)

print(station)

                     name country region    wmo  icao  latitude  longitude  \
id
17129  Ankara / Etimesgut      TR    ANK  17129  LTAD     39.95    32.6833

       elevation         timezone hourly_start hourly_end daily_start  \
id
17129      799.0  Europe/Istanbul   1945-01-31 2025-11-22  1945-02-08

       daily_end monthly_start monthly_end      distance
id
17129 2022-04-24    1945-01-01  2021-01-01  61269.530269

In [16]:
polatli

In [24]:
start = datetime(2000, 1, 1)
end = datetime(2025, 12, 31)

# Get Monthly data
data = Monthly(station, start, end)

In [25]:
data = data.fetch()
data

            tavg  tmin  tmax  prcp  wspd    pres  tsun
time
2000-06-01  19.2  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
2000-07-01  25.7  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
2000-08-01  22.8  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
2000-09-01  18.2  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
2000-12-01   1.1  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
...          ...   ...   ...   ...   ...     ...   ...
2025-05-01  16.7   9.3  23.6  70.2  <NA>  1013.3  <NA>
2025-06-01  22.1  13.6  29.2  14.4  <NA>  1015.3  <NA>
2025-07-01  27.1  18.6  34.6   0.9  <NA>  1010.4  <NA>
2025-08-01  26.0  18.7  32.7   5.8  <NA>  1012.9  <NA>
2025-09-01  19.4  12.3  26.5  17.4  <NA>  1017.2  <NA>

[237 rows x 7 columns]

In [26]:
data

            tavg  tmin  tmax  prcp  wspd    pres  tsun
time
2000-06-01  19.2  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
2000-07-01  25.7  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
2000-08-01  22.8  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
2000-09-01  18.2  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
2000-12-01   1.1  <NA>  <NA>  <NA>  <NA>    <NA>  <NA>
...          ...   ...   ...   ...   ...     ...   ...
2025-05-01  16.7   9.3  23.6  70.2  <NA>  1013.3  <NA>
2025-06-01  22.1  13.6  29.2  14.4  <NA>  1015.3  <NA>
2025-07-01  27.1  18.6  34.6   0.9  <NA>  1010.4  <NA>
2025-08-01  26.0  18.7  32.7   5.8  <NA>  1012.9  <NA>
2025-09-01  19.4  12.3  26.5  17.4  <NA>  1017.2  <NA>

[237 rows x 7 columns]

In [27]:
import pandas as pd
import os
import re
from datetime import datetime
from meteostat import Stations, Monthly

# ---------------------------------------------------------
# 1. AYARLAR
# ---------------------------------------------------------

file_path = 'worldcities.csv'
log_file_path = 'hatali_sehirler_log.txt'      # Eski log + yeni hatalar
output_csv_path = 'hatali_sehirler_hava_verileri.csv'

# Tarih Aralığı
start = datetime(2012, 1, 1)
end = datetime.now()

# ---------------------------------------------------------
# 2. ESKİ LOGDAN HATALI ŞEHİR ID'LERİNİ ÇEK
# ---------------------------------------------------------
error_ids = set()

if not os.path.exists(log_file_path):
    print(f"HATA: Hatalı şehirler log dosyası bulunamadı: {log_file_path}")
    raise SystemExit

with open(log_file_path, "r", encoding="utf-8") as f:
    for line in f:
        m = re.search(r"ID:\s*(\d+)", line)
        if m:
            error_ids.add(int(m.group(1)))

if not error_ids:
    print("Log dosyasında hiç ID bulunamadı. Çıkılıyor.")
    raise SystemExit

print(f"Log dosyasından alınan hatalı şehir sayısı: {len(error_ids)}")

# ---------------------------------------------------------
# 3. LOGLAMA FONKSİYONU (YENİ ÇALIŞMA İÇİN)
# ---------------------------------------------------------
def log_error(city_row, error_message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_line = (
        f"{timestamp} | ID: {city_row['id']} | City: {city_row['city']} "
        f"| Country: {city_row['iso2']} | Error: {error_message}\n"
    )
    try:
        with open(log_file_path, "a", encoding="utf-8") as f:
            f.write(log_line)
    except Exception as e:
        print(f"Log dosyasına yazılamadı: {e}")

# Eski logun üstüne yazmak istiyorsan burayı kullan;
# sadece eklemek istersen bu kısmı sil.
with open(log_file_path, "w", encoding="utf-8") as f:
    f.write(f"--- YENİ HATALI ŞEHİRLER İŞLEM BAŞLANGICI: {datetime.now()} ---\n")
    f.write("Log Formatı: ZAMAN | ID | ŞEHİR | ÜLKE KODU | HATA\n")
    f.write("-" * 80 + "\n")

# ---------------------------------------------------------
# 4. CSV'Yİ OKU VE SADECE HATALI ŞEHİRLERİ SEÇ
# ---------------------------------------------------------
if not os.path.exists(file_path):
    print(f"HATA: Dosya bulunamadı: {file_path}")
    raise SystemExit

print(f"CSV okunuyor: {file_path}...")
df_cities = pd.read_csv(file_path)

# id türlerini hizala
df_cities['id'] = df_cities['id'].astype(int)

df_error_cities = df_cities[df_cities['id'].isin(error_ids)].copy()

if df_error_cities.empty:
    print("worldcities.csv içinde logdaki ID'lere karşılık gelen şehir bulunamadı.")
    raise SystemExit

total_cities = len(df_error_cities)
print(f"Toplam işlenecek hatalı şehir sayısı: {total_cities}")
print("Veri çekme işlemi başlıyor...\n")

# ---------------------------------------------------------
# 5. METEOSTAT'TAN VERİ ÇEKME (STATION / LOCATION İLE)
# ---------------------------------------------------------
all_weather_data = []
count = 0
success_count = 0

for index, row in df_error_cities.iterrows():
    try:
        lat = row['lat']
        lng = row['lng']
        city_name = row['city']
        country_iso = row['iso2']
        city_id = row['id']

        # En yakın istasyonları bul
        stations = Stations()
        stations = stations.nearby(lat, lng)

        # Tek bir istasyon seç (en yakın)
        station = stations.fetch(1)

        if station.empty:
            log_error(row, "Yakın istasyon bulunamadı")
            continue

        # station DataFrame'ini location olarak kullan
        data = Monthly(station, start, end)
        data = data.fetch()

        if not data.empty:
            # İstasyon ID'si (index) – ilk satır
            station_id = station.index[0]

            data['station_id'] = station_id
            data['city_id'] = city_id
            data['city_name'] = city_name
            data['country'] = country_iso
            data['lat'] = lat
            data['lng'] = lng

            # time index'ini sütuna çevir
            data.reset_index(inplace=True)

            selected_cols = data[
                ['time', 'station_id', 'city_id', 'city_name', 'country',
                 'tavg', 'tmin', 'tmax', 'lat', 'lng']
            ]
            all_weather_data.append(selected_cols)
            success_count += 1
        else:
            log_error(row, "Meteostat verisi boş (Empty Data - station)")

    except Exception as e:
        log_error(row, f"Hata: {str(e)}")

    count += 1

    if count % 20 == 0 or count == total_cities:
        print(f"İlerleme: {count}/{total_cities} şehir tarandı. (Başarılı: {success_count})")

# ---------------------------------------------------------
# 6. SONUCU KAYDET
# ---------------------------------------------------------
print("\n" + "="*50)
print("HATALI ŞEHİRLER İŞLEMİ TAMAMLANDI")
print(f"Toplam Taranan (Hatalı): {count}")
print(f"Başarılı Veri (Şehir Bazlı): {success_count}")
print(f"Hatalar '{log_file_path}' dosyasına kaydedildi.")
print("="*50)

if all_weather_data:
    final_df = pd.concat(all_weather_data, ignore_index=True)
    print("\nİlk 20 satır:")
    print(final_df.head(20))
    print("\nDataFrame bilgisi:")
    print(final_df.info())

    print(f"\nVeriler '{output_csv_path}' dosyasına kaydediliyor...")
    final_df.to_csv(output_csv_path, index=False)
    print("Kayıt işlemi başarılı.")
else:
    print("Hiçbir şehir için veri çekilemedi.")

Log dosyasından alınan hatalı şehir sayısı: 15852
CSV okunuyor: worldcities.csv...
Toplam işlenecek hatalı şehir sayısı: 15852
Veri çekme işlemi başlıyor...

İlerleme: 20/15852 şehir tarandı. (Başarılı: 20)
İlerleme: 40/15852 şehir tarandı. (Başarılı: 40)
İlerleme: 60/15852 şehir tarandı. (Başarılı: 60)
İlerleme: 80/15852 şehir tarandı. (Başarılı: 80)
İlerleme: 100/15852 şehir tarandı. (Başarılı: 100)
İlerleme: 120/15852 şehir tarandı. (Başarılı: 120)
İlerleme: 140/15852 şehir tarandı. (Başarılı: 140)
İlerleme: 160/15852 şehir tarandı. (Başarılı: 160)
İlerleme: 180/15852 şehir tarandı. (Başarılı: 178)
İlerleme: 200/15852 şehir tarandı. (Başarılı: 198)
İlerleme: 220/15852 şehir tarandı. (Başarılı: 218)
İlerleme: 240/15852 şehir tarandı. (Başarılı: 237)
İlerleme: 260/15852 şehir tarandı. (Başarılı: 257)
İlerleme: 280/15852 şehir tarandı. (Başarılı: 276)
İlerleme: 300/15852 şehir tarandı. (Başarılı: 296)
İlerleme: 320/15852 şehir tarandı. (Başarılı: 316)
İlerleme: 340/15852 şehir tarandı. (Başarılı: 335)
İlerleme: 360/15852 şehir tarandı. (Başarılı: 354)
İlerleme: 380/15852 şehir tarandı. (Başarılı: 373)
İlerleme: 400/15852 şehir tarandı. (Başarılı: 392)
İlerleme: 420/15852 şehir tarandı. (Başarılı: 412)
İlerleme: 440/15852 şehir tarandı. (Başarılı: 431)
İlerleme: 460/15852 şehir tarandı. (Başarılı: 449)
İlerleme: 480/15852 şehir tarandı. (Başarılı: 466)
İlerleme: 500/15852 şehir tarandı. (Başarılı: 486)
İlerleme: 520/15852 şehir tarandı. (Başarılı: 504)
İlerleme: 540/15852 şehir tarandı. (Başarılı: 520)
İlerleme: 560/15852 şehir tarandı. (Başarılı: 538)
İlerleme: 580/15852 şehir tarandı. (Başarılı: 557)
İlerleme: 600/15852 şehir tarandı. (Başarılı: 577)
İlerleme: 620/15852 şehir tarandı. (Başarılı: 595)
İlerleme: 640/15852 şehir tarandı. (Başarılı: 615)
İlerleme: 660/15852 şehir tarandı. (Başarılı: 634)
İlerleme: 680/15852 şehir tarandı. (Başarılı: 653)
İlerleme: 700/15852 şehir tarandı. (Başarılı: 672)
İlerleme: 720/15852 şehir tarandı. (Başarılı: 692)
İlerleme: 740/15852 şehir tarandı. (Başarılı: 711)
İlerleme: 760/15852 şehir tarandı. (Başarılı: 730)
İlerleme: 780/15852 şehir tarandı. (Başarılı: 748)
İlerleme: 800/15852 şehir tarandı. (Başarılı: 765)
İlerleme: 820/15852 şehir tarandı. (Başarılı: 783)
İlerleme: 840/15852 şehir tarandı. (Başarılı: 802)
İlerleme: 860/15852 şehir tarandı. (Başarılı: 822)
İlerleme: 880/15852 şehir tarandı. (Başarılı: 838)
İlerleme: 900/15852 şehir tarandı. (Başarılı: 856)
İlerleme: 920/15852 şehir tarandı. (Başarılı: 874)
İlerleme: 940/15852 şehir tarandı. (Başarılı: 894)
İlerleme: 960/15852 şehir tarandı. (Başarılı: 912)
İlerleme: 980/15852 şehir tarandı. (Başarılı: 932)
İlerleme: 1000/15852 şehir tarandı. (Başarılı: 950)
İlerleme: 1020/15852 şehir tarandı. (Başarılı: 968)
İlerleme: 1040/15852 şehir tarandı. (Başarılı: 988)
İlerleme: 1060/15852 şehir tarandı. (Başarılı: 1008)
İlerleme: 1080/15852 şehir tarandı. (Başarılı: 1026)
İlerleme: 1100/15852 şehir tarandı. (Başarılı: 1043)
İlerleme: 1120/15852 şehir tarandı. (Başarılı: 1063)
İlerleme: 1140/15852 şehir tarandı. (Başarılı: 1081)
İlerleme: 1160/15852 şehir tarandı. (Başarılı: 1099)
İlerleme: 1180/15852 şehir tarandı. (Başarılı: 1118)
İlerleme: 1200/15852 şehir tarandı. (Başarılı: 1138)
İlerleme: 1220/15852 şehir tarandı. (Başarılı: 1155)
İlerleme: 1240/15852 şehir tarandı. (Başarılı: 1174)

Warning: Cannot load monthly/84405.csv.gz from https://data.meteostat.net/

İlerleme: 1260/15852 şehir tarandı. (Başarılı: 1192)
İlerleme: 1280/15852 şehir tarandı. (Başarılı: 1212)
İlerleme: 1300/15852 şehir tarandı. (Başarılı: 1230)
İlerleme: 1320/15852 şehir tarandı. (Başarılı: 1249)
İlerleme: 1340/15852 şehir tarandı. (Başarılı: 1268)
İlerleme: 1360/15852 şehir tarandı. (Başarılı: 1286)
İlerleme: 1380/15852 şehir tarandı. (Başarılı: 1305)
İlerleme: 1400/15852 şehir tarandı. (Başarılı: 1323)
İlerleme: 1420/15852 şehir tarandı. (Başarılı: 1338)
İlerleme: 1440/15852 şehir tarandı. (Başarılı: 1356)
İlerleme: 1460/15852 şehir tarandı. (Başarılı: 1376)
İlerleme: 1480/15852 şehir tarandı. (Başarılı: 1394)
İlerleme: 1500/15852 şehir tarandı. (Başarılı: 1413)
İlerleme: 1520/15852 şehir tarandı. (Başarılı: 1432)
İlerleme: 1540/15852 şehir tarandı. (Başarılı: 1451)
İlerleme: 1560/15852 şehir tarandı. (Başarılı: 1471)
İlerleme: 1580/15852 şehir tarandı. (Başarılı: 1488)
İlerleme: 1600/15852 şehir tarandı. (Başarılı: 1507)
İlerleme: 1620/15852 şehir tarandı. (Başarılı: 1526)
İlerleme: 1640/15852 şehir tarandı. (Başarılı: 1545)
İlerleme: 1660/15852 şehir tarandı. (Başarılı: 1564)
İlerleme: 1680/15852 şehir tarandı. (Başarılı: 1583)
İlerleme: 1700/15852 şehir tarandı. (Başarılı: 1602)
İlerleme: 1720/15852 şehir tarandı. (Başarılı: 1621)
İlerleme: 1740/15852 şehir tarandı. (Başarılı: 1641)
İlerleme: 1760/15852 şehir tarandı. (Başarılı: 1659)
İlerleme: 1780/15852 şehir tarandı. (Başarılı: 1679)
İlerleme: 1800/15852 şehir tarandı. (Başarılı: 1698)
İlerleme: 1820/15852 şehir tarandı. (Başarılı: 1715)
İlerleme: 1840/15852 şehir tarandı. (Başarılı: 1731)
İlerleme: 1860/15852 şehir tarandı. (Başarılı: 1751)
İlerleme: 1880/15852 şehir tarandı. (Başarılı: 1767)
İlerleme: 1900/15852 şehir tarandı. (Başarılı: 1783)
İlerleme: 1920/15852 şehir tarandı. (Başarılı: 1802)
İlerleme: 1940/15852 şehir tarandı. (Başarılı: 1821)
İlerleme: 1960/15852 şehir tarandı. (Başarılı: 1841)
İlerleme: 1980/15852 şehir tarandı. (Başarılı: 1860)
İlerleme: 2000/15852 şehir tarandı. (Başarılı: 1879)
İlerleme: 2020/15852 şehir tarandı. (Başarılı: 1899)
İlerleme: 2040/15852 şehir tarandı. (Başarılı: 1917)
İlerleme: 2060/15852 şehir tarandı. (Başarılı: 1935)
İlerleme: 2080/15852 şehir tarandı. (Başarılı: 1953)
İlerleme: 2100/15852 şehir tarandı. (Başarılı: 1969)
İlerleme: 2120/15852 şehir tarandı. (Başarılı: 1989)
İlerleme: 2140/15852 şehir tarandı. (Başarılı: 2009)
İlerleme: 2160/15852 şehir tarandı. (Başarılı: 2028)
İlerleme: 2180/15852 şehir tarandı. (Başarılı: 2048)
İlerleme: 2200/15852 şehir tarandı. (Başarılı: 2066)

Warning: Cannot load monthly/44242.csv.gz from https://data.meteostat.net/

İlerleme: 2220/15852 şehir tarandı. (Başarılı: 2085)
İlerleme: 2240/15852 şehir tarandı. (Başarılı: 2104)
İlerleme: 2260/15852 şehir tarandı. (Başarılı: 2121)
İlerleme: 2280/15852 şehir tarandı. (Başarılı: 2141)
İlerleme: 2300/15852 şehir tarandı. (Başarılı: 2160)
İlerleme: 2320/15852 şehir tarandı. (Başarılı: 2177)
İlerleme: 2340/15852 şehir tarandı. (Başarılı: 2197)
İlerleme: 2360/15852 şehir tarandı. (Başarılı: 2216)
İlerleme: 2380/15852 şehir tarandı. (Başarılı: 2234)
İlerleme: 2400/15852 şehir tarandı. (Başarılı: 2253)
İlerleme: 2420/15852 şehir tarandı. (Başarılı: 2269)
İlerleme: 2440/15852 şehir tarandı. (Başarılı: 2286)
İlerleme: 2460/15852 şehir tarandı. (Başarılı: 2303)
İlerleme: 2480/15852 şehir tarandı. (Başarılı: 2319)
İlerleme: 2500/15852 şehir tarandı. (Başarılı: 2336)
İlerleme: 2520/15852 şehir tarandı. (Başarılı: 2355)
İlerleme: 2540/15852 şehir tarandı. (Başarılı: 2374)
İlerleme: 2560/15852 şehir tarandı. (Başarılı: 2393)
İlerleme: 2580/15852 şehir tarandı. (Başarılı: 2411)
İlerleme: 2600/15852 şehir tarandı. (Başarılı: 2428)
İlerleme: 2620/15852 şehir tarandı. (Başarılı: 2447)
İlerleme: 2640/15852 şehir tarandı. (Başarılı: 2466)
İlerleme: 2660/15852 şehir tarandı. (Başarılı: 2483)
İlerleme: 2680/15852 şehir tarandı. (Başarılı: 2502)
İlerleme: 2700/15852 şehir tarandı. (Başarılı: 2520)
İlerleme: 2720/15852 şehir tarandı. (Başarılı: 2538)
İlerleme: 2740/15852 şehir tarandı. (Başarılı: 2558)
İlerleme: 2760/15852 şehir tarandı. (Başarılı: 2576)

Warning: Cannot load monthly/HKMK0.csv.gz from https://data.meteostat.net/

İlerleme: 2780/15852 şehir tarandı. (Başarılı: 2594)
İlerleme: 2800/15852 şehir tarandı. (Başarılı: 2612)
İlerleme: 2820/15852 şehir tarandı. (Başarılı: 2630)
İlerleme: 2840/15852 şehir tarandı. (Başarılı: 2649)
İlerleme: 2860/15852 şehir tarandı. (Başarılı: 2665)
İlerleme: 2880/15852 şehir tarandı. (Başarılı: 2685)
İlerleme: 2900/15852 şehir tarandı. (Başarılı: 2704)
İlerleme: 2920/15852 şehir tarandı. (Başarılı: 2724)
İlerleme: 2940/15852 şehir tarandı. (Başarılı: 2743)
İlerleme: 2960/15852 şehir tarandı. (Başarılı: 2762)
İlerleme: 2980/15852 şehir tarandı. (Başarılı: 2781)
İlerleme: 3000/15852 şehir tarandı. (Başarılı: 2801)
İlerleme: 3020/15852 şehir tarandı. (Başarılı: 2820)
İlerleme: 3040/15852 şehir tarandı. (Başarılı: 2838)
İlerleme: 3060/15852 şehir tarandı. (Başarılı: 2857)
İlerleme: 3080/15852 şehir tarandı. (Başarılı: 2876)
İlerleme: 3100/15852 şehir tarandı. (Başarılı: 2895)

Warning: Cannot load monthly/OYAS0.csv.gz from https://data.meteostat.net/

İlerleme: 3120/15852 şehir tarandı. (Başarılı: 2912)
İlerleme: 3140/15852 şehir tarandı. (Başarılı: 2931)
İlerleme: 3160/15852 şehir tarandı. (Başarılı: 2951)
İlerleme: 3180/15852 şehir tarandı. (Başarılı: 2969)
İlerleme: 3200/15852 şehir tarandı. (Başarılı: 2988)
İlerleme: 3220/15852 şehir tarandı. (Başarılı: 3008)
İlerleme: 3240/15852 şehir tarandı. (Başarılı: 3025)
İlerleme: 3260/15852 şehir tarandı. (Başarılı: 3043)
İlerleme: 3280/15852 şehir tarandı. (Başarılı: 3062)
İlerleme: 3300/15852 şehir tarandı. (Başarılı: 3080)
İlerleme: 3320/15852 şehir tarandı. (Başarılı: 3100)
İlerleme: 3340/15852 şehir tarandı. (Başarılı: 3118)
İlerleme: 3360/15852 şehir tarandı. (Başarılı: 3138)
İlerleme: 3380/15852 şehir tarandı. (Başarılı: 3157)
İlerleme: 3400/15852 şehir tarandı. (Başarılı: 3175)
İlerleme: 3420/15852 şehir tarandı. (Başarılı: 3195)
İlerleme: 3440/15852 şehir tarandı. (Başarılı: 3215)
İlerleme: 3460/15852 şehir tarandı. (Başarılı: 3233)
İlerleme: 3480/15852 şehir tarandı. (Başarılı: 3253)
İlerleme: 3500/15852 şehir tarandı. (Başarılı: 3271)
İlerleme: 3520/15852 şehir tarandı. (Başarılı: 3290)
İlerleme: 3540/15852 şehir tarandı. (Başarılı: 3310)
İlerleme: 3560/15852 şehir tarandı. (Başarılı: 3329)
İlerleme: 3580/15852 şehir tarandı. (Başarılı: 3348)
İlerleme: 3600/15852 şehir tarandı. (Başarılı: 3367)
İlerleme: 3620/15852 şehir tarandı. (Başarılı: 3386)
İlerleme: 3640/15852 şehir tarandı. (Başarılı: 3405)
İlerleme: 3660/15852 şehir tarandı. (Başarılı: 3422)
İlerleme: 3680/15852 şehir tarandı. (Başarılı: 3441)
İlerleme: 3700/15852 şehir tarandı. (Başarılı: 3461)
İlerleme: 3720/15852 şehir tarandı. (Başarılı: 3480)
İlerleme: 3740/15852 şehir tarandı. (Başarılı: 3500)
İlerleme: 3760/15852 şehir tarandı. (Başarılı: 3519)
İlerleme: 3780/15852 şehir tarandı. (Başarılı: 3538)
İlerleme: 3800/15852 şehir tarandı. (Başarılı: 3556)
İlerleme: 3820/15852 şehir tarandı. (Başarılı: 3575)
İlerleme: 3840/15852 şehir tarandı. (Başarılı: 3594)
İlerleme: 3860/15852 şehir tarandı. (Başarılı: 3609)
İlerleme: 3880/15852 şehir tarandı. (Başarılı: 3628)
İlerleme: 3900/15852 şehir tarandı. (Başarılı: 3647)
İlerleme: 3920/15852 şehir tarandı. (Başarılı: 3666)
İlerleme: 3940/15852 şehir tarandı. (Başarılı: 3686)
İlerleme: 3960/15852 şehir tarandı. (Başarılı: 3705)
İlerleme: 3980/15852 şehir tarandı. (Başarılı: 3725)
İlerleme: 4000/15852 şehir tarandı. (Başarılı: 3743)
İlerleme: 4020/15852 şehir tarandı. (Başarılı: 3762)
İlerleme: 4040/15852 şehir tarandı. (Başarılı: 3782)
İlerleme: 4060/15852 şehir tarandı. (Başarılı: 3801)
İlerleme: 4080/15852 şehir tarandı. (Başarılı: 3820)
İlerleme: 4100/15852 şehir tarandı. (Başarılı: 3839)
İlerleme: 4120/15852 şehir tarandı. (Başarılı: 3858)
İlerleme: 4140/15852 şehir tarandı. (Başarılı: 3875)
İlerleme: 4160/15852 şehir tarandı. (Başarılı: 3893)
İlerleme: 4180/15852 şehir tarandı. (Başarılı: 3910)
İlerleme: 4200/15852 şehir tarandı. (Başarılı: 3929)
İlerleme: 4220/15852 şehir tarandı. (Başarılı: 3947)
İlerleme: 4240/15852 şehir tarandı. (Başarılı: 3966)
İlerleme: 4260/15852 şehir tarandı. (Başarılı: 3985)
İlerleme: 4280/15852 şehir tarandı. (Başarılı: 4002)
İlerleme: 4300/15852 şehir tarandı. (Başarılı: 4019)
İlerleme: 4320/15852 şehir tarandı. (Başarılı: 4039)
İlerleme: 4340/15852 şehir tarandı. (Başarılı: 4057)
İlerleme: 4360/15852 şehir tarandı. (Başarılı: 4077)
İlerleme: 4380/15852 şehir tarandı. (Başarılı: 4095)
İlerleme: 4400/15852 şehir tarandı. (Başarılı: 4114)
İlerleme: 4420/15852 şehir tarandı. (Başarılı: 4133)
İlerleme: 4440/15852 şehir tarandı. (Başarılı: 4152)
İlerleme: 4460/15852 şehir tarandı. (Başarılı: 4172)
İlerleme: 4480/15852 şehir tarandı. (Başarılı: 4192)
İlerleme: 4500/15852 şehir tarandı. (Başarılı: 4211)
İlerleme: 4520/15852 şehir tarandı. (Başarılı: 4230)
İlerleme: 4540/15852 şehir tarandı. (Başarılı: 4249)
İlerleme: 4560/15852 şehir tarandı. (Başarılı: 4269)
İlerleme: 4580/15852 şehir tarandı. (Başarılı: 4289)
İlerleme: 4600/15852 şehir tarandı. (Başarılı: 4307)
İlerleme: 4620/15852 şehir tarandı. (Başarılı: 4327)
İlerleme: 4640/15852 şehir tarandı. (Başarılı: 4347)
İlerleme: 4660/15852 şehir tarandı. (Başarılı: 4366)
İlerleme: 4680/15852 şehir tarandı. (Başarılı: 4380)
İlerleme: 4700/15852 şehir tarandı. (Başarılı: 4397)
İlerleme: 4720/15852 şehir tarandı. (Başarılı: 4414)
İlerleme: 4740/15852 şehir tarandı. (Başarılı: 4434)
İlerleme: 4760/15852 şehir tarandı. (Başarılı: 4454)
İlerleme: 4780/15852 şehir tarandı. (Başarılı: 4474)
İlerleme: 4800/15852 şehir tarandı. (Başarılı: 4494)
İlerleme: 4820/15852 şehir tarandı. (Başarılı: 4514)
İlerleme: 4840/15852 şehir tarandı. (Başarılı: 4531)
İlerleme: 4860/15852 şehir tarandı. (Başarılı: 4551)
İlerleme: 4880/15852 şehir tarandı. (Başarılı: 4571)
İlerleme: 4900/15852 şehir tarandı. (Başarılı: 4588)
İlerleme: 4920/15852 şehir tarandı. (Başarılı: 4607)
İlerleme: 4940/15852 şehir tarandı. (Başarılı: 4627)
İlerleme: 4960/15852 şehir tarandı. (Başarılı: 4647)
İlerleme: 4980/15852 şehir tarandı. (Başarılı: 4666)
İlerleme: 5000/15852 şehir tarandı. (Başarılı: 4682)
İlerleme: 5020/15852 şehir tarandı. (Başarılı: 4701)
İlerleme: 5040/15852 şehir tarandı. (Başarılı: 4718)
İlerleme: 5060/15852 şehir tarandı. (Başarılı: 4735)
İlerleme: 5080/15852 şehir tarandı. (Başarılı: 4754)
İlerleme: 5100/15852 şehir tarandı. (Başarılı: 4774)
İlerleme: 5120/15852 şehir tarandı. (Başarılı: 4794)
İlerleme: 5140/15852 şehir tarandı. (Başarılı: 4814)
İlerleme: 5160/15852 şehir tarandı. (Başarılı: 4832)
İlerleme: 5180/15852 şehir tarandı. (Başarılı: 4851)
İlerleme: 5200/15852 şehir tarandı. (Başarılı: 4871)
İlerleme: 5220/15852 şehir tarandı. (Başarılı: 4890)
İlerleme: 5240/15852 şehir tarandı. (Başarılı: 4909)
İlerleme: 5260/15852 şehir tarandı. (Başarılı: 4928)
İlerleme: 5280/15852 şehir tarandı. (Başarılı: 4948)
İlerleme: 5300/15852 şehir tarandı. (Başarılı: 4968)
İlerleme: 5320/15852 şehir tarandı. (Başarılı: 4988)
İlerleme: 5340/15852 şehir tarandı. (Başarılı: 5007)
İlerleme: 5360/15852 şehir tarandı. (Başarılı: 5024)
İlerleme: 5380/15852 şehir tarandı. (Başarılı: 5044)
İlerleme: 5400/15852 şehir tarandı. (Başarılı: 5063)
İlerleme: 5420/15852 şehir tarandı. (Başarılı: 5080)
İlerleme: 5440/15852 şehir tarandı. (Başarılı: 5099)
İlerleme: 5460/15852 şehir tarandı. (Başarılı: 5118)
İlerleme: 5480/15852 şehir tarandı. (Başarılı: 5137)
İlerleme: 5500/15852 şehir tarandı. (Başarılı: 5156)
İlerleme: 5520/15852 şehir tarandı. (Başarılı: 5174)
İlerleme: 5540/15852 şehir tarandı. (Başarılı: 5193)
İlerleme: 5560/15852 şehir tarandı. (Başarılı: 5212)
İlerleme: 5580/15852 şehir tarandı. (Başarılı: 5231)
İlerleme: 5600/15852 şehir tarandı. (Başarılı: 5250)
İlerleme: 5620/15852 şehir tarandı. (Başarılı: 5268)
İlerleme: 5640/15852 şehir tarandı. (Başarılı: 5287)
İlerleme: 5660/15852 şehir tarandı. (Başarılı: 5307)
İlerleme: 5680/15852 şehir tarandı. (Başarılı: 5324)
İlerleme: 5700/15852 şehir tarandı. (Başarılı: 5342)
İlerleme: 5720/15852 şehir tarandı. (Başarılı: 5362)

Warning: Cannot load monthly/VLKG0.csv.gz from https://data.meteostat.net/

İlerleme: 5740/15852 şehir tarandı. (Başarılı: 5381)
İlerleme: 5760/15852 şehir tarandı. (Başarılı: 5400)
İlerleme: 5780/15852 şehir tarandı. (Başarılı: 5420)
İlerleme: 5800/15852 şehir tarandı. (Başarılı: 5438)
İlerleme: 5820/15852 şehir tarandı. (Başarılı: 5458)
İlerleme: 5840/15852 şehir tarandı. (Başarılı: 5477)
İlerleme: 5860/15852 şehir tarandı. (Başarılı: 5495)
İlerleme: 5880/15852 şehir tarandı. (Başarılı: 5514)
İlerleme: 5900/15852 şehir tarandı. (Başarılı: 5534)
İlerleme: 5920/15852 şehir tarandı. (Başarılı: 5554)
İlerleme: 5940/15852 şehir tarandı. (Başarılı: 5574)
İlerleme: 5960/15852 şehir tarandı. (Başarılı: 5593)
İlerleme: 5980/15852 şehir tarandı. (Başarılı: 5612)
İlerleme: 6000/15852 şehir tarandı. (Başarılı: 5630)
İlerleme: 6020/15852 şehir tarandı. (Başarılı: 5649)
İlerleme: 6040/15852 şehir tarandı. (Başarılı: 5667)
İlerleme: 6060/15852 şehir tarandı. (Başarılı: 5685)
İlerleme: 6080/15852 şehir tarandı. (Başarılı: 5704)
İlerleme: 6100/15852 şehir tarandı. (Başarılı: 5723)
İlerleme: 6120/15852 şehir tarandı. (Başarılı: 5742)
İlerleme: 6140/15852 şehir tarandı. (Başarılı: 5762)
İlerleme: 6160/15852 şehir tarandı. (Başarılı: 5782)
İlerleme: 6180/15852 şehir tarandı. (Başarılı: 5799)
İlerleme: 6200/15852 şehir tarandı. (Başarılı: 5818)
İlerleme: 6220/15852 şehir tarandı. (Başarılı: 5836)
İlerleme: 6240/15852 şehir tarandı. (Başarılı: 5855)
İlerleme: 6260/15852 şehir tarandı. (Başarılı: 5875)
İlerleme: 6280/15852 şehir tarandı. (Başarılı: 5891)
İlerleme: 6300/15852 şehir tarandı. (Başarılı: 5910)
İlerleme: 6320/15852 şehir tarandı. (Başarılı: 5929)
İlerleme: 6340/15852 şehir tarandı. (Başarılı: 5948)
İlerleme: 6360/15852 şehir tarandı. (Başarılı: 5967)
İlerleme: 6380/15852 şehir tarandı. (Başarılı: 5987)
İlerleme: 6400/15852 şehir tarandı. (Başarılı: 6007)
İlerleme: 6420/15852 şehir tarandı. (Başarılı: 6025)
İlerleme: 6440/15852 şehir tarandı. (Başarılı: 6044)
İlerleme: 6460/15852 şehir tarandı. (Başarılı: 6064)
İlerleme: 6480/15852 şehir tarandı. (Başarılı: 6083)
İlerleme: 6500/15852 şehir tarandı. (Başarılı: 6103)
İlerleme: 6520/15852 şehir tarandı. (Başarılı: 6123)
İlerleme: 6540/15852 şehir tarandı. (Başarılı: 6142)
İlerleme: 6560/15852 şehir tarandı. (Başarılı: 6161)

Warning: Cannot load monthly/97114.csv.gz from https://data.meteostat.net/

İlerleme: 6580/15852 şehir tarandı. (Başarılı: 6180)
İlerleme: 6600/15852 şehir tarandı. (Başarılı: 6200)
İlerleme: 6620/15852 şehir tarandı. (Başarılı: 6219)
İlerleme: 6640/15852 şehir tarandı. (Başarılı: 6238)
İlerleme: 6660/15852 şehir tarandı. (Başarılı: 6257)
İlerleme: 6680/15852 şehir tarandı. (Başarılı: 6273)
İlerleme: 6700/15852 şehir tarandı. (Başarılı: 6293)
İlerleme: 6720/15852 şehir tarandı. (Başarılı: 6312)
İlerleme: 6740/15852 şehir tarandı. (Başarılı: 6331)
İlerleme: 6760/15852 şehir tarandı. (Başarılı: 6349)
İlerleme: 6780/15852 şehir tarandı. (Başarılı: 6368)
İlerleme: 6800/15852 şehir tarandı. (Başarılı: 6387)
İlerleme: 6820/15852 şehir tarandı. (Başarılı: 6406)
İlerleme: 6840/15852 şehir tarandı. (Başarılı: 6423)
İlerleme: 6860/15852 şehir tarandı. (Başarılı: 6442)
İlerleme: 6880/15852 şehir tarandı. (Başarılı: 6462)
İlerleme: 6900/15852 şehir tarandı. (Başarılı: 6481)
İlerleme: 6920/15852 şehir tarandı. (Başarılı: 6501)
İlerleme: 6940/15852 şehir tarandı. (Başarılı: 6520)
İlerleme: 6960/15852 şehir tarandı. (Başarılı: 6538)
İlerleme: 6980/15852 şehir tarandı. (Başarılı: 6556)
İlerleme: 7000/15852 şehir tarandı. (Başarılı: 6575)
İlerleme: 7020/15852 şehir tarandı. (Başarılı: 6595)
İlerleme: 7040/15852 şehir tarandı. (Başarılı: 6614)
İlerleme: 7060/15852 şehir tarandı. (Başarılı: 6634)
İlerleme: 7080/15852 şehir tarandı. (Başarılı: 6654)
İlerleme: 7100/15852 şehir tarandı. (Başarılı: 6672)
İlerleme: 7120/15852 şehir tarandı. (Başarılı: 6692)
İlerleme: 7140/15852 şehir tarandı. (Başarılı: 6712)
İlerleme: 7160/15852 şehir tarandı. (Başarılı: 6729)
İlerleme: 7180/15852 şehir tarandı. (Başarılı: 6749)
İlerleme: 7200/15852 şehir tarandı. (Başarılı: 6767)
İlerleme: 7220/15852 şehir tarandı. (Başarılı: 6787)
İlerleme: 7240/15852 şehir tarandı. (Başarılı: 6806)
İlerleme: 7260/15852 şehir tarandı. (Başarılı: 6825)
İlerleme: 7280/15852 şehir tarandı. (Başarılı: 6843)
İlerleme: 7300/15852 şehir tarandı. (Başarılı: 6862)
İlerleme: 7320/15852 şehir tarandı. (Başarılı: 6880)
İlerleme: 7340/15852 şehir tarandı. (Başarılı: 6899)
İlerleme: 7360/15852 şehir tarandı. (Başarılı: 6919)
İlerleme: 7380/15852 şehir tarandı. (Başarılı: 6937)
İlerleme: 7400/15852 şehir tarandı. (Başarılı: 6954)
İlerleme: 7420/15852 şehir tarandı. (Başarılı: 6974)
İlerleme: 7440/15852 şehir tarandı. (Başarılı: 6992)
İlerleme: 7460/15852 şehir tarandı. (Başarılı: 7010)
İlerleme: 7480/15852 şehir tarandı. (Başarılı: 7029)
İlerleme: 7500/15852 şehir tarandı. (Başarılı: 7049)
İlerleme: 7520/15852 şehir tarandı. (Başarılı: 7069)
İlerleme: 7540/15852 şehir tarandı. (Başarılı: 7088)
İlerleme: 7560/15852 şehir tarandı. (Başarılı: 7107)
İlerleme: 7580/15852 şehir tarandı. (Başarılı: 7127)
İlerleme: 7600/15852 şehir tarandı. (Başarılı: 7146)
İlerleme: 7620/15852 şehir tarandı. (Başarılı: 7166)
İlerleme: 7640/15852 şehir tarandı. (Başarılı: 7186)
İlerleme: 7660/15852 şehir tarandı. (Başarılı: 7206)
İlerleme: 7680/15852 şehir tarandı. (Başarılı: 7226)
İlerleme: 7700/15852 şehir tarandı. (Başarılı: 7246)
İlerleme: 7720/15852 şehir tarandı. (Başarılı: 7264)
İlerleme: 7740/15852 şehir tarandı. (Başarılı: 7283)
İlerleme: 7760/15852 şehir tarandı. (Başarılı: 7302)
İlerleme: 7780/15852 şehir tarandı. (Başarılı: 7322)
İlerleme: 7800/15852 şehir tarandı. (Başarılı: 7342)
İlerleme: 7820/15852 şehir tarandı. (Başarılı: 7360)
İlerleme: 7840/15852 şehir tarandı. (Başarılı: 7379)
İlerleme: 7860/15852 şehir tarandı. (Başarılı: 7396)
İlerleme: 7880/15852 şehir tarandı. (Başarılı: 7416)
İlerleme: 7900/15852 şehir tarandı. (Başarılı: 7434)
İlerleme: 7920/15852 şehir tarandı. (Başarılı: 7452)
İlerleme: 7940/15852 şehir tarandı. (Başarılı: 7469)
İlerleme: 7960/15852 şehir tarandı. (Başarılı: 7488)
İlerleme: 7980/15852 şehir tarandı. (Başarılı: 7507)
İlerleme: 8000/15852 şehir tarandı. (Başarılı: 7527)
İlerleme: 8020/15852 şehir tarandı. (Başarılı: 7547)
İlerleme: 8040/15852 şehir tarandı. (Başarılı: 7567)
İlerleme: 8060/15852 şehir tarandı. (Başarılı: 7586)
İlerleme: 8080/15852 şehir tarandı. (Başarılı: 7605)
İlerleme: 8100/15852 şehir tarandı. (Başarılı: 7624)
İlerleme: 8120/15852 şehir tarandı. (Başarılı: 7643)
İlerleme: 8140/15852 şehir tarandı. (Başarılı: 7662)
İlerleme: 8160/15852 şehir tarandı. (Başarılı: 7681)
İlerleme: 8180/15852 şehir tarandı. (Başarılı: 7701)

Warning: Cannot load monthly/FYOK0.csv.gz from https://data.meteostat.net/

İlerleme: 8200/15852 şehir tarandı. (Başarılı: 7718)
İlerleme: 8220/15852 şehir tarandı. (Başarılı: 7736)
İlerleme: 8240/15852 şehir tarandı. (Başarılı: 7756)
İlerleme: 8260/15852 şehir tarandı. (Başarılı: 7774)
İlerleme: 8280/15852 şehir tarandı. (Başarılı: 7793)
İlerleme: 8300/15852 şehir tarandı. (Başarılı: 7813)
İlerleme: 8320/15852 şehir tarandı. (Başarılı: 7832)
İlerleme: 8340/15852 şehir tarandı. (Başarılı: 7852)
İlerleme: 8360/15852 şehir tarandı. (Başarılı: 7871)
İlerleme: 8380/15852 şehir tarandı. (Başarılı: 7891)
İlerleme: 8400/15852 şehir tarandı. (Başarılı: 7909)
İlerleme: 8420/15852 şehir tarandı. (Başarılı: 7929)
İlerleme: 8440/15852 şehir tarandı. (Başarılı: 7949)
İlerleme: 8460/15852 şehir tarandı. (Başarılı: 7969)
İlerleme: 8480/15852 şehir tarandı. (Başarılı: 7987)
İlerleme: 8500/15852 şehir tarandı. (Başarılı: 8007)
İlerleme: 8520/15852 şehir tarandı. (Başarılı: 8025)
İlerleme: 8540/15852 şehir tarandı. (Başarılı: 8044)
İlerleme: 8560/15852 şehir tarandı. (Başarılı: 8064)
İlerleme: 8580/15852 şehir tarandı. (Başarılı: 8083)
İlerleme: 8600/15852 şehir tarandı. (Başarılı: 8102)
İlerleme: 8620/15852 şehir tarandı. (Başarılı: 8121)
İlerleme: 8640/15852 şehir tarandı. (Başarılı: 8141)
İlerleme: 8660/15852 şehir tarandı. (Başarılı: 8160)
İlerleme: 8680/15852 şehir tarandı. (Başarılı: 8178)
İlerleme: 8700/15852 şehir tarandı. (Başarılı: 8198)
İlerleme: 8720/15852 şehir tarandı. (Başarılı: 8216)
İlerleme: 8740/15852 şehir tarandı. (Başarılı: 8234)
İlerleme: 8760/15852 şehir tarandı. (Başarılı: 8252)
İlerleme: 8780/15852 şehir tarandı. (Başarılı: 8270)
İlerleme: 8800/15852 şehir tarandı. (Başarılı: 8290)
İlerleme: 8820/15852 şehir tarandı. (Başarılı: 8308)
İlerleme: 8840/15852 şehir tarandı. (Başarılı: 8328)
İlerleme: 8860/15852 şehir tarandı. (Başarılı: 8347)
İlerleme: 8880/15852 şehir tarandı. (Başarılı: 8367)
İlerleme: 8900/15852 şehir tarandı. (Başarılı: 8387)
İlerleme: 8920/15852 şehir tarandı. (Başarılı: 8406)
İlerleme: 8940/15852 şehir tarandı. (Başarılı: 8425)
İlerleme: 8960/15852 şehir tarandı. (Başarılı: 8445)
İlerleme: 8980/15852 şehir tarandı. (Başarılı: 8465)
İlerleme: 9000/15852 şehir tarandı. (Başarılı: 8485)
İlerleme: 9020/15852 şehir tarandı. (Başarılı: 8503)
İlerleme: 9040/15852 şehir tarandı. (Başarılı: 8522)
İlerleme: 9060/15852 şehir tarandı. (Başarılı: 8541)
İlerleme: 9080/15852 şehir tarandı. (Başarılı: 8560)
İlerleme: 9100/15852 şehir tarandı. (Başarılı: 8579)
İlerleme: 9120/15852 şehir tarandı. (Başarılı: 8599)
İlerleme: 9140/15852 şehir tarandı. (Başarılı: 8619)
İlerleme: 9160/15852 şehir tarandı. (Başarılı: 8639)
İlerleme: 9180/15852 şehir tarandı. (Başarılı: 8658)
İlerleme: 9200/15852 şehir tarandı. (Başarılı: 8676)
İlerleme: 9220/15852 şehir tarandı. (Başarılı: 8692)
İlerleme: 9240/15852 şehir tarandı. (Başarılı: 8711)
İlerleme: 9260/15852 şehir tarandı. (Başarılı: 8729)
İlerleme: 9280/15852 şehir tarandı. (Başarılı: 8747)
İlerleme: 9300/15852 şehir tarandı. (Başarılı: 8765)
İlerleme: 9320/15852 şehir tarandı. (Başarılı: 8783)
İlerleme: 9340/15852 şehir tarandı. (Başarılı: 8801)
İlerleme: 9360/15852 şehir tarandı. (Başarılı: 8820)
İlerleme: 9380/15852 şehir tarandı. (Başarılı: 8839)
İlerleme: 9400/15852 şehir tarandı. (Başarılı: 8858)
İlerleme: 9420/15852 şehir tarandı. (Başarılı: 8878)
İlerleme: 9440/15852 şehir tarandı. (Başarılı: 8898)
İlerleme: 9460/15852 şehir tarandı. (Başarılı: 8918)
İlerleme: 9480/15852 şehir tarandı. (Başarılı: 8938)
İlerleme: 9500/15852 şehir tarandı. (Başarılı: 8958)
İlerleme: 9520/15852 şehir tarandı. (Başarılı: 8977)
İlerleme: 9540/15852 şehir tarandı. (Başarılı: 8997)
İlerleme: 9560/15852 şehir tarandı. (Başarılı: 9017)
İlerleme: 9580/15852 şehir tarandı. (Başarılı: 9037)
İlerleme: 9600/15852 şehir tarandı. (Başarılı: 9057)
İlerleme: 9620/15852 şehir tarandı. (Başarılı: 9075)
İlerleme: 9640/15852 şehir tarandı. (Başarılı: 9095)
İlerleme: 9660/15852 şehir tarandı. (Başarılı: 9115)
İlerleme: 9680/15852 şehir tarandı. (Başarılı: 9134)
İlerleme: 9700/15852 şehir tarandı. (Başarılı: 9153)
İlerleme: 9720/15852 şehir tarandı. (Başarılı: 9173)
İlerleme: 9740/15852 şehir tarandı. (Başarılı: 9192)
İlerleme: 9760/15852 şehir tarandı. (Başarılı: 9212)
İlerleme: 9780/15852 şehir tarandı. (Başarılı: 9231)
İlerleme: 9800/15852 şehir tarandı. (Başarılı: 9250)
İlerleme: 9820/15852 şehir tarandı. (Başarılı: 9268)
İlerleme: 9840/15852 şehir tarandı. (Başarılı: 9287)
İlerleme: 9860/15852 şehir tarandı. (Başarılı: 9306)
İlerleme: 9880/15852 şehir tarandı. (Başarılı: 9325)
İlerleme: 9900/15852 şehir tarandı. (Başarılı: 9345)
İlerleme: 9920/15852 şehir tarandı. (Başarılı: 9365)
İlerleme: 9940/15852 şehir tarandı. (Başarılı: 9385)
İlerleme: 9960/15852 şehir tarandı. (Başarılı: 9405)
İlerleme: 9980/15852 şehir tarandı. (Başarılı: 9424)
İlerleme: 10000/15852 şehir tarandı. (Başarılı: 9444)
İlerleme: 10020/15852 şehir tarandı. (Başarılı: 9463)
İlerleme: 10040/15852 şehir tarandı. (Başarılı: 9482)
İlerleme: 10060/15852 şehir tarandı. (Başarılı: 9502)
İlerleme: 10080/15852 şehir tarandı. (Başarılı: 9521)
İlerleme: 10100/15852 şehir tarandı. (Başarılı: 9540)
İlerleme: 10120/15852 şehir tarandı. (Başarılı: 9559)
İlerleme: 10140/15852 şehir tarandı. (Başarılı: 9578)
İlerleme: 10160/15852 şehir tarandı. (Başarılı: 9598)
İlerleme: 10180/15852 şehir tarandı. (Başarılı: 9617)
İlerleme: 10200/15852 şehir tarandı. (Başarılı: 9637)
İlerleme: 10220/15852 şehir tarandı. (Başarılı: 9655)
İlerleme: 10240/15852 şehir tarandı. (Başarılı: 9673)
İlerleme: 10260/15852 şehir tarandı. (Başarılı: 9692)
İlerleme: 10280/15852 şehir tarandı. (Başarılı: 9712)
İlerleme: 10300/15852 şehir tarandı. (Başarılı: 9730)
İlerleme: 10320/15852 şehir tarandı. (Başarılı: 9749)
İlerleme: 10340/15852 şehir tarandı. (Başarılı: 9767)
İlerleme: 10360/15852 şehir tarandı. (Başarılı: 9784)
İlerleme: 10380/15852 şehir tarandı. (Başarılı: 9803)
İlerleme: 10400/15852 şehir tarandı. (Başarılı: 9821)
İlerleme: 10420/15852 şehir tarandı. (Başarılı: 9839)
İlerleme: 10440/15852 şehir tarandı. (Başarılı: 9858)
İlerleme: 10460/15852 şehir tarandı. (Başarılı: 9876)
İlerleme: 10480/15852 şehir tarandı. (Başarılı: 9896)
İlerleme: 10500/15852 şehir tarandı. (Başarılı: 9915)
İlerleme: 10520/15852 şehir tarandı. (Başarılı: 9933)
İlerleme: 10540/15852 şehir tarandı. (Başarılı: 9951)
İlerleme: 10560/15852 şehir tarandı. (Başarılı: 9971)
İlerleme: 10580/15852 şehir tarandı. (Başarılı: 9991)
İlerleme: 10600/15852 şehir tarandı. (Başarılı: 10011)
İlerleme: 10620/15852 şehir tarandı. (Başarılı: 10031)
İlerleme: 10640/15852 şehir tarandı. (Başarılı: 10050)
İlerleme: 10660/15852 şehir tarandı. (Başarılı: 10067)
İlerleme: 10680/15852 şehir tarandı. (Başarılı: 10086)
İlerleme: 10700/15852 şehir tarandı. (Başarılı: 10106)
İlerleme: 10720/15852 şehir tarandı. (Başarılı: 10126)
İlerleme: 10740/15852 şehir tarandı. (Başarılı: 10146)
İlerleme: 10760/15852 şehir tarandı. (Başarılı: 10165)
İlerleme: 10780/15852 şehir tarandı. (Başarılı: 10184)
İlerleme: 10800/15852 şehir tarandı. (Başarılı: 10203)
İlerleme: 10820/15852 şehir tarandı. (Başarılı: 10222)
İlerleme: 10840/15852 şehir tarandı. (Başarılı: 10241)
İlerleme: 10860/15852 şehir tarandı. (Başarılı: 10261)
İlerleme: 10880/15852 şehir tarandı. (Başarılı: 10281)
İlerleme: 10900/15852 şehir tarandı. (Başarılı: 10300)
İlerleme: 10920/15852 şehir tarandı. (Başarılı: 10319)
İlerleme: 10940/15852 şehir tarandı. (Başarılı: 10338)
İlerleme: 10960/15852 şehir tarandı. (Başarılı: 10357)
İlerleme: 10980/15852 şehir tarandı. (Başarılı: 10376)
İlerleme: 11000/15852 şehir tarandı. (Başarılı: 10395)
İlerleme: 11020/15852 şehir tarandı. (Başarılı: 10414)
İlerleme: 11040/15852 şehir tarandı. (Başarılı: 10433)
İlerleme: 11060/15852 şehir tarandı. (Başarılı: 10452)
İlerleme: 11080/15852 şehir tarandı. (Başarılı: 10471)
İlerleme: 11100/15852 şehir tarandı. (Başarılı: 10491)
İlerleme: 11120/15852 şehir tarandı. (Başarılı: 10511)
İlerleme: 11140/15852 şehir tarandı. (Başarılı: 10531)
İlerleme: 11160/15852 şehir tarandı. (Başarılı: 10551)
İlerleme: 11180/15852 şehir tarandı. (Başarılı: 10570)
İlerleme: 11200/15852 şehir tarandı. (Başarılı: 10588)
İlerleme: 11220/15852 şehir tarandı. (Başarılı: 10608)
İlerleme: 11240/15852 şehir tarandı. (Başarılı: 10628)
İlerleme: 11260/15852 şehir tarandı. (Başarılı: 10648)
İlerleme: 11280/15852 şehir tarandı. (Başarılı: 10667)
İlerleme: 11300/15852 şehir tarandı. (Başarılı: 10686)
İlerleme: 11320/15852 şehir tarandı. (Başarılı: 10705)
İlerleme: 11340/15852 şehir tarandı. (Başarılı: 10724)
İlerleme: 11360/15852 şehir tarandı. (Başarılı: 10744)
İlerleme: 11380/15852 şehir tarandı. (Başarılı: 10762)
İlerleme: 11400/15852 şehir tarandı. (Başarılı: 10782)
İlerleme: 11420/15852 şehir tarandı. (Başarılı: 10798)
İlerleme: 11440/15852 şehir tarandı. (Başarılı: 10817)
İlerleme: 11460/15852 şehir tarandı. (Başarılı: 10837)
İlerleme: 11480/15852 şehir tarandı. (Başarılı: 10855)
İlerleme: 11500/15852 şehir tarandı. (Başarılı: 10874)
İlerleme: 11520/15852 şehir tarandı. (Başarılı: 10893)
İlerleme: 11540/15852 şehir tarandı. (Başarılı: 10913)
İlerleme: 11560/15852 şehir tarandı. (Başarılı: 10932)
İlerleme: 11580/15852 şehir tarandı. (Başarılı: 10952)
İlerleme: 11600/15852 şehir tarandı. (Başarılı: 10971)
İlerleme: 11620/15852 şehir tarandı. (Başarılı: 10991)
İlerleme: 11640/15852 şehir tarandı. (Başarılı: 11009)
İlerleme: 11660/15852 şehir tarandı. (Başarılı: 11028)
İlerleme: 11680/15852 şehir tarandı. (Başarılı: 11044)
İlerleme: 11700/15852 şehir tarandı. (Başarılı: 11063)
İlerleme: 11720/15852 şehir tarandı. (Başarılı: 11081)
İlerleme: 11740/15852 şehir tarandı. (Başarılı: 11101)
İlerleme: 11760/15852 şehir tarandı. (Başarılı: 11120)
İlerleme: 11780/15852 şehir tarandı. (Başarılı: 11140)
İlerleme: 11800/15852 şehir tarandı. (Başarılı: 11158)
İlerleme: 11820/15852 şehir tarandı. (Başarılı: 11176)
İlerleme: 11840/15852 şehir tarandı. (Başarılı: 11196)
İlerleme: 11860/15852 şehir tarandı. (Başarılı: 11214)
İlerleme: 11880/15852 şehir tarandı. (Başarılı: 11233)
İlerleme: 11900/15852 şehir tarandı. (Başarılı: 11253)
İlerleme: 11920/15852 şehir tarandı. (Başarılı: 11273)
İlerleme: 11940/15852 şehir tarandı. (Başarılı: 11292)
İlerleme: 11960/15852 şehir tarandı. (Başarılı: 11311)
İlerleme: 11980/15852 şehir tarandı. (Başarılı: 11331)
İlerleme: 12000/15852 şehir tarandı. (Başarılı: 11350)
İlerleme: 12020/15852 şehir tarandı. (Başarılı: 11370)
İlerleme: 12040/15852 şehir tarandı. (Başarılı: 11387)
İlerleme: 12060/15852 şehir tarandı. (Başarılı: 11404)
İlerleme: 12080/15852 şehir tarandı. (Başarılı: 11423)
İlerleme: 12100/15852 şehir tarandı. (Başarılı: 11441)
İlerleme: 12120/15852 şehir tarandı. (Başarılı: 11460)
İlerleme: 12140/15852 şehir tarandı. (Başarılı: 11479)
İlerleme: 12160/15852 şehir tarandı. (Başarılı: 11499)
İlerleme: 12180/15852 şehir tarandı. (Başarılı: 11518)
İlerleme: 12200/15852 şehir tarandı. (Başarılı: 11538)
İlerleme: 12220/15852 şehir tarandı. (Başarılı: 11557)

Warning: Cannot load monthly/VYTN0.csv.gz from https://data.meteostat.net/

İlerleme: 12240/15852 şehir tarandı. (Başarılı: 11576)
İlerleme: 12260/15852 şehir tarandı. (Başarılı: 11595)
İlerleme: 12280/15852 şehir tarandı. (Başarılı: 11614)
İlerleme: 12300/15852 şehir tarandı. (Başarılı: 11632)
İlerleme: 12320/15852 şehir tarandı. (Başarılı: 11651)
İlerleme: 12340/15852 şehir tarandı. (Başarılı: 11669)
İlerleme: 12360/15852 şehir tarandı. (Başarılı: 11688)
İlerleme: 12380/15852 şehir tarandı. (Başarılı: 11707)
İlerleme: 12400/15852 şehir tarandı. (Başarılı: 11725)
İlerleme: 12420/15852 şehir tarandı. (Başarılı: 11744)
İlerleme: 12440/15852 şehir tarandı. (Başarılı: 11764)
İlerleme: 12460/15852 şehir tarandı. (Başarılı: 11783)
İlerleme: 12480/15852 şehir tarandı. (Başarılı: 11801)
İlerleme: 12500/15852 şehir tarandı. (Başarılı: 11821)
İlerleme: 12520/15852 şehir tarandı. (Başarılı: 11841)
İlerleme: 12540/15852 şehir tarandı. (Başarılı: 11860)
İlerleme: 12560/15852 şehir tarandı. (Başarılı: 11878)
İlerleme: 12580/15852 şehir tarandı. (Başarılı: 11898)
İlerleme: 12600/15852 şehir tarandı. (Başarılı: 11918)
İlerleme: 12620/15852 şehir tarandı. (Başarılı: 11938)
İlerleme: 12640/15852 şehir tarandı. (Başarılı: 11957)
İlerleme: 12660/15852 şehir tarandı. (Başarılı: 11974)
İlerleme: 12680/15852 şehir tarandı. (Başarılı: 11993)
İlerleme: 12700/15852 şehir tarandı. (Başarılı: 12012)
İlerleme: 12720/15852 şehir tarandı. (Başarılı: 12032)
İlerleme: 12740/15852 şehir tarandı. (Başarılı: 12051)
İlerleme: 12760/15852 şehir tarandı. (Başarılı: 12070)
İlerleme: 12780/15852 şehir tarandı. (Başarılı: 12088)
İlerleme: 12800/15852 şehir tarandı. (Başarılı: 12107)
İlerleme: 12820/15852 şehir tarandı. (Başarılı: 12126)
İlerleme: 12840/15852 şehir tarandı. (Başarılı: 12146)
İlerleme: 12860/15852 şehir tarandı. (Başarılı: 12166)
İlerleme: 12880/15852 şehir tarandı. (Başarılı: 12185)
İlerleme: 12900/15852 şehir tarandı. (Başarılı: 12204)
İlerleme: 12920/15852 şehir tarandı. (Başarılı: 12223)
İlerleme: 12940/15852 şehir tarandı. (Başarılı: 12243)
İlerleme: 12960/15852 şehir tarandı. (Başarılı: 12263)
İlerleme: 12980/15852 şehir tarandı. (Başarılı: 12283)
İlerleme: 13000/15852 şehir tarandı. (Başarılı: 12303)
İlerleme: 13020/15852 şehir tarandı. (Başarılı: 12321)
İlerleme: 13040/15852 şehir tarandı. (Başarılı: 12340)
İlerleme: 13060/15852 şehir tarandı. (Başarılı: 12359)
İlerleme: 13080/15852 şehir tarandı. (Başarılı: 12379)
İlerleme: 13100/15852 şehir tarandı. (Başarılı: 12398)
İlerleme: 13120/15852 şehir tarandı. (Başarılı: 12416)
İlerleme: 13140/15852 şehir tarandı. (Başarılı: 12436)
İlerleme: 13160/15852 şehir tarandı. (Başarılı: 12456)
İlerleme: 13180/15852 şehir tarandı. (Başarılı: 12476)
İlerleme: 13200/15852 şehir tarandı. (Başarılı: 12496)
İlerleme: 13220/15852 şehir tarandı. (Başarılı: 12515)
İlerleme: 13240/15852 şehir tarandı. (Başarılı: 12534)
İlerleme: 13260/15852 şehir tarandı. (Başarılı: 12552)
İlerleme: 13280/15852 şehir tarandı. (Başarılı: 12572)
İlerleme: 13300/15852 şehir tarandı. (Başarılı: 12591)
İlerleme: 13320/15852 şehir tarandı. (Başarılı: 12611)
İlerleme: 13340/15852 şehir tarandı. (Başarılı: 12631)
İlerleme: 13360/15852 şehir tarandı. (Başarılı: 12651)
İlerleme: 13380/15852 şehir tarandı. (Başarılı: 12671)
İlerleme: 13400/15852 şehir tarandı. (Başarılı: 12691)
İlerleme: 13420/15852 şehir tarandı. (Başarılı: 12710)
İlerleme: 13440/15852 şehir tarandı. (Başarılı: 12730)
İlerleme: 13460/15852 şehir tarandı. (Başarılı: 12750)
İlerleme: 13480/15852 şehir tarandı. (Başarılı: 12769)
İlerleme: 13500/15852 şehir tarandı. (Başarılı: 12788)
İlerleme: 13520/15852 şehir tarandı. (Başarılı: 12808)
İlerleme: 13540/15852 şehir tarandı. (Başarılı: 12828)

Warning: Cannot load monthly/MGPC0.csv.gz from https://data.meteostat.net/

İlerleme: 13560/15852 şehir tarandı. (Başarılı: 12846)
İlerleme: 13580/15852 şehir tarandı. (Başarılı: 12866)
İlerleme: 13600/15852 şehir tarandı. (Başarılı: 12885)
İlerleme: 13620/15852 şehir tarandı. (Başarılı: 12905)
İlerleme: 13640/15852 şehir tarandı. (Başarılı: 12925)
İlerleme: 13660/15852 şehir tarandı. (Başarılı: 12945)
İlerleme: 13680/15852 şehir tarandı. (Başarılı: 12964)
İlerleme: 13700/15852 şehir tarandı. (Başarılı: 12983)
İlerleme: 13720/15852 şehir tarandı. (Başarılı: 13002)
İlerleme: 13740/15852 şehir tarandı. (Başarılı: 13020)
İlerleme: 13760/15852 şehir tarandı. (Başarılı: 13037)
İlerleme: 13780/15852 şehir tarandı. (Başarılı: 13056)
İlerleme: 13800/15852 şehir tarandı. (Başarılı: 13075)
İlerleme: 13820/15852 şehir tarandı. (Başarılı: 13094)
İlerleme: 13840/15852 şehir tarandı. (Başarılı: 13114)
İlerleme: 13860/15852 şehir tarandı. (Başarılı: 13134)
İlerleme: 13880/15852 şehir tarandı. (Başarılı: 13153)
İlerleme: 13900/15852 şehir tarandı. (Başarılı: 13173)
İlerleme: 13920/15852 şehir tarandı. (Başarılı: 13193)
İlerleme: 13940/15852 şehir tarandı. (Başarılı: 13211)
İlerleme: 13960/15852 şehir tarandı. (Başarılı: 13230)
İlerleme: 13980/15852 şehir tarandı. (Başarılı: 13249)
İlerleme: 14000/15852 şehir tarandı. (Başarılı: 13269)
İlerleme: 14020/15852 şehir tarandı. (Başarılı: 13289)
İlerleme: 14040/15852 şehir tarandı. (Başarılı: 13308)
İlerleme: 14060/15852 şehir tarandı. (Başarılı: 13327)
İlerleme: 14080/15852 şehir tarandı. (Başarılı: 13346)
İlerleme: 14100/15852 şehir tarandı. (Başarılı: 13365)
İlerleme: 14120/15852 şehir tarandı. (Başarılı: 13384)
İlerleme: 14140/15852 şehir tarandı. (Başarılı: 13404)
İlerleme: 14160/15852 şehir tarandı. (Başarılı: 13424)
İlerleme: 14180/15852 şehir tarandı. (Başarılı: 13443)
İlerleme: 14200/15852 şehir tarandı. (Başarılı: 13463)
İlerleme: 14220/15852 şehir tarandı. (Başarılı: 13483)
İlerleme: 14240/15852 şehir tarandı. (Başarılı: 13502)
İlerleme: 14260/15852 şehir tarandı. (Başarılı: 13522)
İlerleme: 14280/15852 şehir tarandı. (Başarılı: 13542)
İlerleme: 14300/15852 şehir tarandı. (Başarılı: 13560)
İlerleme: 14320/15852 şehir tarandı. (Başarılı: 13580)
İlerleme: 14340/15852 şehir tarandı. (Başarılı: 13600)
İlerleme: 14360/15852 şehir tarandı. (Başarılı: 13618)
İlerleme: 14380/15852 şehir tarandı. (Başarılı: 13637)
İlerleme: 14400/15852 şehir tarandı. (Başarılı: 13657)
İlerleme: 14420/15852 şehir tarandı. (Başarılı: 13675)
İlerleme: 14440/15852 şehir tarandı. (Başarılı: 13695)

Warning: Cannot load monthly/SPVL0.csv.gz from https://data.meteostat.net/

İlerleme: 14460/15852 şehir tarandı. (Başarılı: 13714)
İlerleme: 14480/15852 şehir tarandı. (Başarılı: 13733)
İlerleme: 14500/15852 şehir tarandı. (Başarılı: 13752)
İlerleme: 14520/15852 şehir tarandı. (Başarılı: 13770)
İlerleme: 14540/15852 şehir tarandı. (Başarılı: 13789)
İlerleme: 14560/15852 şehir tarandı. (Başarılı: 13808)
İlerleme: 14580/15852 şehir tarandı. (Başarılı: 13827)
İlerleme: 14600/15852 şehir tarandı. (Başarılı: 13846)
İlerleme: 14620/15852 şehir tarandı. (Başarılı: 13865)
İlerleme: 14640/15852 şehir tarandı. (Başarılı: 13884)
İlerleme: 14660/15852 şehir tarandı. (Başarılı: 13903)
İlerleme: 14680/15852 şehir tarandı. (Başarılı: 13922)
İlerleme: 14700/15852 şehir tarandı. (Başarılı: 13940)
İlerleme: 14720/15852 şehir tarandı. (Başarılı: 13960)
İlerleme: 14740/15852 şehir tarandı. (Başarılı: 13979)
İlerleme: 14760/15852 şehir tarandı. (Başarılı: 13997)
İlerleme: 14780/15852 şehir tarandı. (Başarılı: 14016)
İlerleme: 14800/15852 şehir tarandı. (Başarılı: 14036)
İlerleme: 14820/15852 şehir tarandı. (Başarılı: 14054)
İlerleme: 14840/15852 şehir tarandı. (Başarılı: 14072)
İlerleme: 14860/15852 şehir tarandı. (Başarılı: 14092)
İlerleme: 14880/15852 şehir tarandı. (Başarılı: 14111)
İlerleme: 14900/15852 şehir tarandı. (Başarılı: 14130)
İlerleme: 14920/15852 şehir tarandı. (Başarılı: 14148)
İlerleme: 14940/15852 şehir tarandı. (Başarılı: 14168)
İlerleme: 14960/15852 şehir tarandı. (Başarılı: 14185)
İlerleme: 14980/15852 şehir tarandı. (Başarılı: 14205)
İlerleme: 15000/15852 şehir tarandı. (Başarılı: 14225)
İlerleme: 15020/15852 şehir tarandı. (Başarılı: 14244)
İlerleme: 15040/15852 şehir tarandı. (Başarılı: 14264)
İlerleme: 15060/15852 şehir tarandı. (Başarılı: 14282)

Warning: Cannot load monthly/40480.csv.gz from https://data.meteostat.net/

İlerleme: 15080/15852 şehir tarandı. (Başarılı: 14299)
İlerleme: 15100/15852 şehir tarandı. (Başarılı: 14317)
İlerleme: 15120/15852 şehir tarandı. (Başarılı: 14336)
İlerleme: 15140/15852 şehir tarandı. (Başarılı: 14356)
İlerleme: 15160/15852 şehir tarandı. (Başarılı: 14376)
İlerleme: 15180/15852 şehir tarandı. (Başarılı: 14394)
İlerleme: 15200/15852 şehir tarandı. (Başarılı: 14414)
İlerleme: 15220/15852 şehir tarandı. (Başarılı: 14433)
İlerleme: 15240/15852 şehir tarandı. (Başarılı: 14453)
İlerleme: 15260/15852 şehir tarandı. (Başarılı: 14473)
İlerleme: 15280/15852 şehir tarandı. (Başarılı: 14492)
İlerleme: 15300/15852 şehir tarandı. (Başarılı: 14512)
İlerleme: 15320/15852 şehir tarandı. (Başarılı: 14531)
İlerleme: 15340/15852 şehir tarandı. (Başarılı: 14549)
İlerleme: 15360/15852 şehir tarandı. (Başarılı: 14567)
İlerleme: 15380/15852 şehir tarandı. (Başarılı: 14585)
İlerleme: 15400/15852 şehir tarandı. (Başarılı: 14602)
İlerleme: 15420/15852 şehir tarandı. (Başarılı: 14622)
İlerleme: 15440/15852 şehir tarandı. (Başarılı: 14640)

Warning: Cannot load monthly/FYAS0.csv.gz from https://data.meteostat.net/

İlerleme: 15460/15852 şehir tarandı. (Başarılı: 14658)
İlerleme: 15480/15852 şehir tarandı. (Başarılı: 14678)
İlerleme: 15500/15852 şehir tarandı. (Başarılı: 14697)
İlerleme: 15520/15852 şehir tarandı. (Başarılı: 14714)
İlerleme: 15540/15852 şehir tarandı. (Başarılı: 14734)
İlerleme: 15560/15852 şehir tarandı. (Başarılı: 14752)
İlerleme: 15580/15852 şehir tarandı. (Başarılı: 14769)
İlerleme: 15600/15852 şehir tarandı. (Başarılı: 14787)
İlerleme: 15620/15852 şehir tarandı. (Başarılı: 14806)

Warning: Cannot load monthly/81010.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/25744.csv.gz from https://data.meteostat.net/

İlerleme: 15640/15852 şehir tarandı. (Başarılı: 14823)
İlerleme: 15660/15852 şehir tarandı. (Başarılı: 14842)

Warning: Cannot load monthly/24219.csv.gz from https://data.meteostat.net/

İlerleme: 15680/15852 şehir tarandı. (Başarılı: 14859)
İlerleme: 15700/15852 şehir tarandı. (Başarılı: 14878)
İlerleme: 15720/15852 şehir tarandı. (Başarılı: 14896)
İlerleme: 15740/15852 şehir tarandı. (Başarılı: 14915)
İlerleme: 15760/15852 şehir tarandı. (Başarılı: 14935)
İlerleme: 15780/15852 şehir tarandı. (Başarılı: 14955)
İlerleme: 15800/15852 şehir tarandı. (Başarılı: 14974)

Warning: Cannot load monthly/25017.csv.gz from https://data.meteostat.net/

İlerleme: 15820/15852 şehir tarandı. (Başarılı: 14991)
İlerleme: 15840/15852 şehir tarandı. (Başarılı: 15010)
İlerleme: 15852/15852 şehir tarandı. (Başarılı: 15022)

==================================================
HATALI ŞEHİRLER İŞLEMİ TAMAMLANDI
Toplam Taranan (Hatalı): 15852
Başarılı Veri (Şehir Bazlı): 15022
Hatalar 'hatali_sehirler_log.txt' dosyasına kaydedildi.
==================================================

İlk 20 satır:
         time station_id     city_id city_name country  tavg  tmin  tmax  \
0  2012-01-01      58040  1156086320     Linyi      CN  -1.1  -5.2   4.1
1  2012-02-01      58040  1156086320     Linyi      CN   0.2  -3.6   4.6
2  2012-03-01      58040  1156086320     Linyi      CN   5.5   1.6  10.3
3  2012-04-01      58040  1156086320     Linyi      CN  14.7   9.9  20.1
4  2012-05-01      58040  1156086320     Linyi      CN  20.8  15.5  25.9
5  2012-06-01      58040  1156086320     Linyi      CN  23.6  20.5  27.4
6  2012-07-01      58040  1156086320     Linyi      CN  27.7  24.7  31.1
7  2012-08-01      58040  1156086320     Linyi      CN  25.8  23.2  28.7
8  2012-09-01      58040  1156086320     Linyi      CN  21.1  17.2  25.5
9  2012-10-01      58040  1156086320     Linyi      CN  16.7  11.8  21.9
10 2012-11-01      58040  1156086320     Linyi      CN   7.3   2.8  12.4
11 2012-12-01      58040  1156086320     Linyi      CN   0.2  -3.0   4.0
12 2013-01-01      58040  1156086320     Linyi      CN  -0.5  <NA>   3.6
13 2013-02-01      58040  1156086320     Linyi      CN   2.1  <NA>   5.7
14 2013-03-01      58040  1156086320     Linyi      CN   7.7  <NA>  12.5
15 2013-04-01      58040  1156086320     Linyi      CN  12.7  <NA>  18.8
16 2013-12-01      58040  1156086320     Linyi      CN   1.7  <NA>   7.3
17 2014-01-01      58040  1156086320     Linyi      CN   2.3  <NA>   7.4
18 2014-02-01      58040  1156086320     Linyi      CN   1.6  <NA>   5.2
19 2014-03-01      58040  1156086320     Linyi      CN  10.0  <NA>  15.3

        lat       lng
0   35.1038  118.3564
1   35.1038  118.3564
2   35.1038  118.3564
3   35.1038  118.3564
4   35.1038  118.3564
5   35.1038  118.3564
6   35.1038  118.3564
7   35.1038  118.3564
8   35.1038  118.3564
9   35.1038  118.3564
10  35.1038  118.3564
11  35.1038  118.3564
12  35.1038  118.3564
13  35.1038  118.3564
14  35.1038  118.3564
15  35.1038  118.3564
16  35.1038  118.3564
17  35.1038  118.3564
18  35.1038  118.3564
19  35.1038  118.3564

DataFrame bilgisi:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1483928 entries, 0 to 1483927
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   time        1483928 non-null  datetime64[ns]
 1   station_id  1483928 non-null  object
 2   city_id     1483928 non-null  int64
 3   city_name   1483928 non-null  object
 4   country     1483031 non-null  object
 5   tavg        1462573 non-null  Float64
 6   tmin        1357872 non-null  Float64
 7   tmax        1391139 non-null  Float64
 8   lat         1483928 non-null  float64
 9   lng         1483928 non-null  float64
dtypes: Float64(3), datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 117.5+ MB
None

Veriler 'hatali_sehirler_hava_verileri.csv' dosyasına kaydediliyor...
Kayıt işlemi başarılı.

In [28]:
import pandas as pd
import os

# Dosya isimleri
file_main = "tum_dunya_hava_verileri.csv"
file_error = "hatali_sehirler_hava_verileri.csv"

# Çıkacak birleşik dosya
output_combined = "tum_hava_verileri_birlesik.csv"

# Dosyaların varlığını kontrol et
if not os.path.exists(file_main):
    print(f"HATA: Ana veri dosyası bulunamadı: {file_main}")
    raise SystemExit

if not os.path.exists(file_error):
    print(f"HATA: Hatalı veri dosyası bulunamadı: {file_error}")
    raise SystemExit

print("CSV dosyaları okunuyor...")

# Dosyaları yükle
df_main = pd.read_csv(file_main)
df_error = pd.read_csv(file_error)

print("Birleştiriliyor (concat)...")

# Concat — alt alta birleştir
df_combined = pd.concat([df_main, df_error], ignore_index=True)

print("Toplam satır sayısı:", len(df_combined))

# Son halini kaydet
df_combined.to_csv(output_combined, index=False)

print(f"Başarılı! Birleşik dosya oluşturuldu: {output_combined}")

CSV dosyaları okunuyor...
Birleştiriliyor (concat)...
Toplam satır sayısı: 5940013
Başarılı! Birleşik dosya oluşturuldu: tum_hava_verileri_birlesik.csv

In [29]:
df_combined

,time,city_id,city_name,country,tavg,tmin,tmax,lat,lng,station_id
0,2012-01-01,1392685764,Tokyo,JP,4.8,1.8,8.3,35.6870,139.7495,NaN
1,2012-02-01,1392685764,Tokyo,JP,5.4,2.2,9.1,35.6870,139.7495,NaN
2,2012-03-01,1392685764,Tokyo,JP,8.8,5.3,12.5,35.6870,139.7495,NaN
3,2012-04-01,1392685764,Tokyo,JP,14.5,11.0,18.5,35.6870,139.7495,NaN
4,2012-05-01,1392685764,Tokyo,JP,19.6,16.1,23.6,35.6870,139.7495,NaN
...,...,...,...,...,...,...,...,...,...,...
5940008,2025-06-01,1716206606,Lupane,ZW,15.9,8.4,24.5,-18.9315,27.8070,67853
5940009,2025-07-01,1716206606,Lupane,ZW,16.3,9.1,24.5,-18.9315,27.8070,67853
5940010,2025-08-01,1716206606,Lupane,ZW,18.8,10.0,28.1,-18.9315,27.8070,67853
5940011,2025-09-01,1716206606,Lupane,ZW,24.5,16.2,32.9,-18.9315,27.8070,67853
5940012,2025-10-01,1716206606,Lupane,ZW,25.9,18.7,32.9,-18.9315,27.8070,67853

In [5]:
import pandas as pd
import os
from datetime import datetime
from meteostat import Stations, Monthly

# ---------------------------------------------------------
# 1. AYARLAR
# ---------------------------------------------------------

file_path = 'worldcities.csv'
log_file_path = 'hatali_sehirler_log.txt'
output_csv_path = 'tum_dunya_hava_verileri.csv'  # Sonuçların kaydedileceği dosya

# Tarih Aralığı
start = datetime(1951, 1, 1)
end = datetime.now()

# ---------------------------------------------------------
# 2. LOGLAMA FONKSİYONU
# ---------------------------------------------------------
def log_error(city_row, error_message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # CSV'deki kolon isimlerine göre loglama
    log_line = (
        f"{timestamp} | ID: {city_row['id']} | City: {city_row['city']} | "
        f"Country: {city_row['iso2']} | Error: {error_message}\n"
    )
    
    try:
        with open(log_file_path, "a", encoding="utf-8") as f:
            f.write(log_line)
    except Exception as e:
        print(f"Log dosyasına yazılamadı: {e}")

# ---------------------------------------------------------
# 3. VERİYİ OKUMA VE İŞLEME
# ---------------------------------------------------------

# Log dosyasını sıfırla
with open(log_file_path, "w", encoding="utf-8") as f:
    f.write(f"--- İŞLEM BAŞLANGICI: {datetime.now()} ---\n")
    f.write("Log Formatı: ZAMAN | ID | ŞEHİR | ÜLKE KODU | HATA\n")
    f.write("-" * 80 + "\n")

all_weather_data = []

if not os.path.exists(file_path):
    print(f"HATA: Dosya bulunamadı: {file_path}")
else:
    print(f"CSV okunuyor: {file_path}...")
    
    # CSV dosyasını Pandas ile oku
    df_cities = pd.read_csv(file_path)
    
    # Tüm veri seti üzerinde çalışacağız
    total_cities = len(df_cities)
    print(f"Toplam Şehir Sayısı (Tüm Dünya): {total_cities}")
    print("Veri çekme işlemi başlıyor... (Bu işlem uzun sürebilir)\n")

    count = 0
    success_count = 0
    
    # Tüm DataFrame üzerinde döngü
    for index, row in df_cities.iterrows():
        try:
            # CSV kolon isimleri: city, lat, lng, iso2, id
            lat = row['lat']
            lng = row['lng']
            city_name = row['city']
            country_iso = row['iso2']
            city_id = row['id']

            # --- BURASI DEĞİŞTİ: Point yerine Stations().nearby() kullanılıyor ---

            # En yakın istasyonu bul
            stations = Stations()
            stations = stations.nearby(lat, lng)

            # Tek bir istasyon seç (en yakın)
            station = stations.fetch(1)

            if station.empty:
                # Hiç istasyon bulunamadıysa logla ve devam et
                log_error(row, "Yakın istasyon bulunamadı")
                count += 1
                if count % 100 == 0:
                    print(f"İlerleme: {count}/{total_cities} şehir tarandı. (Başarılı: {success_count})")
                continue

            # station DataFrame'ini location olarak kullan
            data = Monthly(station, start, end)
            data = data.fetch()

            if not data.empty:
                # İstersen istasyon ID'sini de ekleyebilirsin (index üzerinden)
                station_id = station.index[0]
                data['station_id'] = station_id

                # Meta verileri ekle
                data['city_id'] = city_id
                data['city_name'] = city_name
                data['country'] = country_iso
                data['lat'] = lat
                data['lng'] = lng
                
                # İndeksi sütuna çevir (time sütunu oluşur)
                data.reset_index(inplace=True)
                
                # İstenen sütunları seç (pointer kodundaki ile aynı yapıldı)
                # Eğer station_id'yi de CSV'de görmek istersen, aşağıdaki listeye 'station_id' ekleyebilirsin.
                selected_cols = data[
                    ['time', 'city_id', 'city_name', 'country', 'tavg', 'tmin', 'tmax', 'lat', 'lng']
                ]
                all_weather_data.append(selected_cols)
                
                success_count += 1
            else:
                # Meteostat veri döndüremedi
                log_error(row, "Meteostat verisi boş (Empty Data - station)")

        except Exception as e:
            # Beklenmeyen bir hata
            log_error(row, f"Hata: {str(e)}")
        
        count += 1
        
        # İlerleme durumunu göster (Her 100 şehirde bir yazdıralım, liste uzun olduğu için)
        if count % 100 == 0:
            print(f"İlerleme: {count}/{total_cities} şehir tarandı. (Başarılı: {success_count})")

    # ---------------------------------------------------------
    # 4. SONUCU GÖSTERME VE KAYDETME
    # ---------------------------------------------------------

    print("\n" + "="*50)
    print("İŞLEM TAMAMLANDI")
    print(f"Toplam Taranan: {count}")
    print(f"Başarılı Veri (Şehir Bazlı): {success_count}")
    print(f"Hatalar '{log_file_path}' dosyasına kaydedildi.")
    print("="*50)

    if all_weather_data:
        # Tüm verileri birleştir
        final_df = pd.concat(all_weather_data, ignore_index=True)
        
        print("\nSONUÇ DATAFRAME (İLK 20 SATIR):")
        print(final_df.head(20))
        
        print("\nDATAFRAME BİLGİSİ:")
        print(final_df.info())

        # Veriyi CSV olarak kaydet
        print(f"\nVeriler '{output_csv_path}' dosyasına kaydediliyor...")
        final_df.to_csv(output_csv_path, index=False)
        print("Kayıt işlemi başarılı.")
        
    else:
        print("Hiçbir veri çekilemedi.")

CSV okunuyor: worldcities.csv...
Toplam Şehir Sayısı (Tüm Dünya): 48059
Veri çekme işlemi başlıyor... (Bu işlem uzun sürebilir)

İlerleme: 100/48059 şehir tarandı. (Başarılı: 99)
İlerleme: 200/48059 şehir tarandı. (Başarılı: 198)
İlerleme: 300/48059 şehir tarandı. (Başarılı: 297)
İlerleme: 400/48059 şehir tarandı. (Başarılı: 397)

Warning: Cannot load monthly/67774.csv.gz from https://data.meteostat.net/

İlerleme: 500/48059 şehir tarandı. (Başarılı: 496)
İlerleme: 600/48059 şehir tarandı. (Başarılı: 596)

Warning: Cannot load monthly/96783.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40770.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/37545.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/29574.csv.gz from https://data.meteostat.net/

İlerleme: 700/48059 şehir tarandı. (Başarılı: 692)

Warning: Cannot load monthly/RKSK0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/67587.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40621.csv.gz from https://data.meteostat.net/

İlerleme: 800/48059 şehir tarandı. (Başarılı: 789)

Warning: Cannot load monthly/64076.csv.gz from https://data.meteostat.net/

İlerleme: 900/48059 şehir tarandı. (Başarılı: 888)

Warning: Cannot load monthly/13129.csv.gz from https://data.meteostat.net/

İlerleme: 1000/48059 şehir tarandı. (Başarılı: 987)

Warning: Cannot load monthly/40670.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/08161.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/87696.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/12425.csv.gz from https://data.meteostat.net/

İlerleme: 1100/48059 şehir tarandı. (Başarılı: 1083)

Warning: Cannot load monthly/HEAM0.csv.gz from https://data.meteostat.net/

İlerleme: 1200/48059 şehir tarandı. (Başarılı: 1182)

Warning: Cannot load monthly/98639.csv.gz from https://data.meteostat.net/

İlerleme: 1300/48059 şehir tarandı. (Başarılı: 1281)

Warning: Cannot load monthly/76050.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/08301.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40676.csv.gz from https://data.meteostat.net/

İlerleme: 1400/48059 şehir tarandı. (Başarılı: 1378)

Warning: Cannot load monthly/40680.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/LMMM0.csv.gz from https://data.meteostat.net/

İlerleme: 1500/48059 şehir tarandı. (Başarılı: 1476)

Warning: Cannot load monthly/03547.csv.gz from https://data.meteostat.net/

İlerleme: 1600/48059 şehir tarandı. (Başarılı: 1573)

Warning: Cannot load monthly/66305.csv.gz from https://data.meteostat.net/

İlerleme: 1700/48059 şehir tarandı. (Başarılı: 1671)
İlerleme: 1800/48059 şehir tarandı. (Başarılı: 1771)

Warning: Cannot load monthly/40672.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/98436.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RPMW0.csv.gz from https://data.meteostat.net/

İlerleme: 1900/48059 şehir tarandı. (Başarılı: 1867)

Warning: Cannot load monthly/78439.csv.gz from https://data.meteostat.net/

İlerleme: 2000/48059 şehir tarandı. (Başarılı: 1965)

Warning: Cannot load monthly/RPUN0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/VVDL0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/47192.csv.gz from https://data.meteostat.net/

İlerleme: 2100/48059 şehir tarandı. (Başarılı: 2062)

Warning: Cannot load monthly/98746.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/60128.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/MMHC0.csv.gz from https://data.meteostat.net/

İlerleme: 2200/48059 şehir tarandı. (Başarılı: 2159)
İlerleme: 2300/48059 şehir tarandı. (Başarılı: 2259)

Warning: Cannot load monthly/99854.csv.gz from https://data.meteostat.net/

İlerleme: 2400/48059 şehir tarandı. (Başarılı: 2357)
İlerleme: 2500/48059 şehir tarandı. (Başarılı: 2455)

Warning: Cannot load monthly/RKJU0.csv.gz from https://data.meteostat.net/

İlerleme: 2600/48059 şehir tarandı. (Başarılı: 2553)

Warning: Cannot load monthly/CWVZ0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/69304.csv.gz from https://data.meteostat.net/

İlerleme: 2700/48059 şehir tarandı. (Başarılı: 2650)
İlerleme: 2800/48059 şehir tarandı. (Başarılı: 2750)
İlerleme: 2900/48059 şehir tarandı. (Başarılı: 2849)

Warning: Cannot load monthly/99860.csv.gz from https://data.meteostat.net/

İlerleme: 3000/48059 şehir tarandı. (Başarılı: 2947)

Warning: Cannot load monthly/WIPK0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40674.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RKJM0.csv.gz from https://data.meteostat.net/

İlerleme: 3100/48059 şehir tarandı. (Başarılı: 3042)

Warning: Cannot load monthly/40611.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RKTV0.csv.gz from https://data.meteostat.net/

İlerleme: 3200/48059 şehir tarandı. (Başarılı: 3138)
İlerleme: 3300/48059 şehir tarandı. (Başarılı: 3235)

Warning: Cannot load monthly/99867.csv.gz from https://data.meteostat.net/

İlerleme: 3400/48059 şehir tarandı. (Başarılı: 3333)

Warning: Cannot load monthly/61891.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RPVC0.csv.gz from https://data.meteostat.net/

İlerleme: 3500/48059 şehir tarandı. (Başarılı: 3430)

Warning: Cannot load monthly/62955.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/64062.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SBGU0.csv.gz from https://data.meteostat.net/

İlerleme: 3600/48059 şehir tarandı. (Başarılı: 3527)

Warning: Cannot load monthly/23078.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/93172.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/MNLN0.csv.gz from https://data.meteostat.net/

İlerleme: 3700/48059 şehir tarandı. (Başarılı: 3623)

Warning: Cannot load monthly/FAVY0.csv.gz from https://data.meteostat.net/

İlerleme: 3800/48059 şehir tarandı. (Başarılı: 3721)
İlerleme: 3900/48059 şehir tarandı. (Başarılı: 3820)

Warning: Cannot load monthly/13334.csv.gz from https://data.meteostat.net/

İlerleme: 4000/48059 şehir tarandı. (Başarılı: 3917)
İlerleme: 4100/48059 şehir tarandı. (Başarılı: 4016)

Warning: Cannot load monthly/98329.csv.gz from https://data.meteostat.net/

İlerleme: 4200/48059 şehir tarandı. (Başarılı: 4115)

Warning: Cannot load monthly/08329.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/CWLU0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/HSMD0.csv.gz from https://data.meteostat.net/

İlerleme: 4300/48059 şehir tarandı. (Başarılı: 4210)
İlerleme: 4400/48059 şehir tarandı. (Başarılı: 4309)

Warning: Cannot load monthly/40947.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/OIIA0.csv.gz from https://data.meteostat.net/

İlerleme: 4500/48059 şehir tarandı. (Başarılı: 4407)

Warning: Cannot load monthly/78447.csv.gz from https://data.meteostat.net/

İlerleme: 4600/48059 şehir tarandı. (Başarılı: 4505)

Warning: Cannot load monthly/78652.csv.gz from https://data.meteostat.net/

İlerleme: 4700/48059 şehir tarandı. (Başarılı: 4603)

Warning: Cannot load monthly/WATL0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/OIKJ0.csv.gz from https://data.meteostat.net/

İlerleme: 4800/48059 şehir tarandı. (Başarılı: 4698)

Warning: Cannot load monthly/60492.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/84405.csv.gz from https://data.meteostat.net/

İlerleme: 4900/48059 şehir tarandı. (Başarılı: 4793)
İlerleme: 5000/48059 şehir tarandı. (Başarılı: 4893)
İlerleme: 5100/48059 şehir tarandı. (Başarılı: 4991)

Warning: Cannot load monthly/EGUH0.csv.gz from https://data.meteostat.net/

İlerleme: 5200/48059 şehir tarandı. (Başarılı: 5088)
İlerleme: 5300/48059 şehir tarandı. (Başarılı: 5187)

Warning: Cannot load monthly/80077.csv.gz from https://data.meteostat.net/

İlerleme: 5400/48059 şehir tarandı. (Başarılı: 5283)

Warning: Cannot load monthly/ESGI0.csv.gz from https://data.meteostat.net/

İlerleme: 5500/48059 şehir tarandı. (Başarılı: 5378)
İlerleme: 5600/48059 şehir tarandı. (Başarılı: 5478)
İlerleme: 5700/48059 şehir tarandı. (Başarılı: 5575)

Warning: Cannot load monthly/40564.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/KZAB0.csv.gz from https://data.meteostat.net/

İlerleme: 5800/48059 şehir tarandı. (Başarılı: 5672)

Warning: Cannot load monthly/1KBHF.csv.gz from https://data.meteostat.net/

İlerleme: 5900/48059 şehir tarandı. (Başarılı: 5769)

Warning: Cannot load monthly/64014.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/11544.csv.gz from https://data.meteostat.net/

İlerleme: 6000/48059 şehir tarandı. (Başarılı: 5865)

Warning: Cannot load monthly/DAAQ0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/94027.csv.gz from https://data.meteostat.net/

İlerleme: 6100/48059 şehir tarandı. (Başarılı: 5962)

Warning: Cannot load monthly/59362.csv.gz from https://data.meteostat.net/

İlerleme: 6200/48059 şehir tarandı. (Başarılı: 6059)

Warning: Cannot load monthly/SBCN0.csv.gz from https://data.meteostat.net/

İlerleme: 6300/48059 şehir tarandı. (Başarılı: 6157)

Warning: Cannot load monthly/83554.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/RPVN0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/63329.csv.gz from https://data.meteostat.net/

İlerleme: 6400/48059 şehir tarandı. (Başarılı: 6254)
İlerleme: 6500/48059 şehir tarandı. (Başarılı: 6352)
İlerleme: 6600/48059 şehir tarandı. (Başarılı: 6451)
İlerleme: 6700/48059 şehir tarandı. (Başarılı: 6547)

Warning: Cannot load monthly/LIQD0.csv.gz from https://data.meteostat.net/

İlerleme: 6800/48059 şehir tarandı. (Başarılı: 6641)

Warning: Cannot load monthly/47706.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/06448.csv.gz from https://data.meteostat.net/

İlerleme: 6900/48059 şehir tarandı. (Başarılı: 6735)
İlerleme: 7000/48059 şehir tarandı. (Başarılı: 6831)
İlerleme: 7100/48059 şehir tarandı. (Başarılı: 6929)

Warning: Cannot load monthly/03964.csv.gz from https://data.meteostat.net/

İlerleme: 7200/48059 şehir tarandı. (Başarılı: 7025)
İlerleme: 7300/48059 şehir tarandı. (Başarılı: 7121)
İlerleme: 7400/48059 şehir tarandı. (Başarılı: 7218)

Warning: Cannot load monthly/08539.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/MMLC0.csv.gz from https://data.meteostat.net/

İlerleme: 7500/48059 şehir tarandı. (Başarılı: 7312)

Warning: Cannot load monthly/EDWD0.csv.gz from https://data.meteostat.net/

İlerleme: 7600/48059 şehir tarandı. (Başarılı: 7410)
İlerleme: 7700/48059 şehir tarandı. (Başarılı: 7507)

Warning: Cannot load monthly/10127.csv.gz from https://data.meteostat.net/

İlerleme: 7800/48059 şehir tarandı. (Başarılı: 7606)
İlerleme: 7900/48059 şehir tarandı. (Başarılı: 7703)

Warning: Cannot load monthly/44242.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40629.csv.gz from https://data.meteostat.net/

İlerleme: 8000/48059 şehir tarandı. (Başarılı: 7801)

Warning: Cannot load monthly/80318.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/EDEF0.csv.gz from https://data.meteostat.net/

İlerleme: 8100/48059 şehir tarandı. (Başarılı: 7896)
İlerleme: 8200/48059 şehir tarandı. (Başarılı: 7995)

Warning: Cannot load monthly/40976.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/LHTL0.csv.gz from https://data.meteostat.net/

İlerleme: 8300/48059 şehir tarandı. (Başarılı: 8089)
İlerleme: 8400/48059 şehir tarandı. (Başarılı: 8186)

Warning: Cannot load monthly/SPEQ0.csv.gz from https://data.meteostat.net/

İlerleme: 8500/48059 şehir tarandı. (Başarılı: 8281)

Warning: Cannot load monthly/41443.csv.gz from https://data.meteostat.net/

İlerleme: 8600/48059 şehir tarandı. (Başarılı: 8375)

Warning: Cannot load monthly/64146.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/86296.csv.gz from https://data.meteostat.net/

İlerleme: 8700/48059 şehir tarandı. (Başarılı: 8469)

Warning: Cannot load monthly/66140.csv.gz from https://data.meteostat.net/

İlerleme: 8800/48059 şehir tarandı. (Başarılı: 8564)

Warning: Cannot load monthly/99871.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/98526.csv.gz from https://data.meteostat.net/

İlerleme: 8900/48059 şehir tarandı. (Başarılı: 8660)

Warning: Cannot load monthly/40946.csv.gz from https://data.meteostat.net/

İlerleme: 9000/48059 şehir tarandı. (Başarılı: 8759)
İlerleme: 9100/48059 şehir tarandı. (Başarılı: 8852)
İlerleme: 9200/48059 şehir tarandı. (Başarılı: 8949)
İlerleme: 9300/48059 şehir tarandı. (Başarılı: 9046)
İlerleme: 9400/48059 şehir tarandı. (Başarılı: 9144)
İlerleme: 9500/48059 şehir tarandı. (Başarılı: 9239)
İlerleme: 9600/48059 şehir tarandı. (Başarılı: 9335)

Warning: Cannot load monthly/HKMK0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/64015.csv.gz from https://data.meteostat.net/

İlerleme: 9700/48059 şehir tarandı. (Başarılı: 9431)
İlerleme: 9800/48059 şehir tarandı. (Başarılı: 9527)
İlerleme: 9900/48059 şehir tarandı. (Başarılı: 9624)
İlerleme: 10000/48059 şehir tarandı. (Başarılı: 9722)
İlerleme: 10100/48059 şehir tarandı. (Başarılı: 9822)
İlerleme: 10200/48059 şehir tarandı. (Başarılı: 9919)
İlerleme: 10300/48059 şehir tarandı. (Başarılı: 10019)

Warning: Cannot load monthly/64034.csv.gz from https://data.meteostat.net/

İlerleme: 10400/48059 şehir tarandı. (Başarılı: 10116)

Warning: Cannot load monthly/37013.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/08094.csv.gz from https://data.meteostat.net/

İlerleme: 10500/48059 şehir tarandı. (Başarılı: 10212)

Warning: Cannot load monthly/93246.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/MKJP2.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/OYAS0.csv.gz from https://data.meteostat.net/

İlerleme: 10600/48059 şehir tarandı. (Başarılı: 10308)

Warning: Cannot load monthly/07148.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/08557.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/46747.csv.gz from https://data.meteostat.net/

İlerleme: 10700/48059 şehir tarandı. (Başarılı: 10403)
İlerleme: 10800/48059 şehir tarandı. (Başarılı: 10499)
İlerleme: 10900/48059 şehir tarandı. (Başarılı: 10596)

Warning: Cannot load monthly/62940.csv.gz from https://data.meteostat.net/

İlerleme: 11000/48059 şehir tarandı. (Başarılı: 10692)

Warning: Cannot load monthly/98S13.csv.gz from https://data.meteostat.net/

İlerleme: 11100/48059 şehir tarandı. (Başarılı: 10789)

Warning: Cannot load monthly/40953.csv.gz from https://data.meteostat.net/

İlerleme: 11200/48059 şehir tarandı. (Başarılı: 10886)
İlerleme: 11300/48059 şehir tarandı. (Başarılı: 10985)
İlerleme: 11400/48059 şehir tarandı. (Başarılı: 11085)
İlerleme: 11500/48059 şehir tarandı. (Başarılı: 11184)

Warning: Cannot load monthly/13275.csv.gz from https://data.meteostat.net/

İlerleme: 11600/48059 şehir tarandı. (Başarılı: 11282)

Warning: Cannot load monthly/0FZ2W.csv.gz from https://data.meteostat.net/

İlerleme: 11700/48059 şehir tarandı. (Başarılı: 11381)

Warning: Cannot load monthly/EGSD0.csv.gz from https://data.meteostat.net/

İlerleme: 11800/48059 şehir tarandı. (Başarılı: 11479)

Warning: Cannot load monthly/EGPT0.csv.gz from https://data.meteostat.net/

İlerleme: 11900/48059 şehir tarandı. (Başarılı: 11578)
İlerleme: 12000/48059 şehir tarandı. (Başarılı: 11675)
İlerleme: 12100/48059 şehir tarandı. (Başarılı: 11772)

Warning: Cannot load monthly/66130.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/HKIS0.csv.gz from https://data.meteostat.net/

İlerleme: 12200/48059 şehir tarandı. (Başarılı: 11866)
İlerleme: 12300/48059 şehir tarandı. (Başarılı: 11965)

Warning: Cannot load monthly/23221.csv.gz from https://data.meteostat.net/

İlerleme: 12400/48059 şehir tarandı. (Başarılı: 12064)
İlerleme: 12500/48059 şehir tarandı. (Başarılı: 12163)
İlerleme: 12600/48059 şehir tarandı. (Başarılı: 12261)

Warning: Cannot load monthly/06462.csv.gz from https://data.meteostat.net/

İlerleme: 12700/48059 şehir tarandı. (Başarılı: 12357)

Warning: Cannot load monthly/28409.csv.gz from https://data.meteostat.net/

İlerleme: 12800/48059 şehir tarandı. (Başarılı: 12450)

Warning: Cannot load monthly/EGVT0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/60270.csv.gz from https://data.meteostat.net/

İlerleme: 12900/48059 şehir tarandı. (Başarılı: 12546)

Warning: Cannot load monthly/CWVE0.csv.gz from https://data.meteostat.net/

İlerleme: 13000/48059 şehir tarandı. (Başarılı: 12643)
İlerleme: 13100/48059 şehir tarandı. (Başarılı: 12741)
İlerleme: 13200/48059 şehir tarandı. (Başarılı: 12838)
İlerleme: 13300/48059 şehir tarandı. (Başarılı: 12936)
İlerleme: 13400/48059 şehir tarandı. (Başarılı: 13035)
İlerleme: 13500/48059 şehir tarandı. (Başarılı: 13134)

Warning: Cannot load monthly/03586.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/KQIW0.csv.gz from https://data.meteostat.net/

İlerleme: 13600/48059 şehir tarandı. (Başarılı: 13229)

Warning: Cannot load monthly/61873.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/08302.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/15511.csv.gz from https://data.meteostat.net/

İlerleme: 13700/48059 şehir tarandı. (Başarılı: 13322)

Warning: Cannot load monthly/KQOW0.csv.gz from https://data.meteostat.net/

İlerleme: 13800/48059 şehir tarandı. (Başarılı: 13417)

Warning: Cannot load monthly/84125.csv.gz from https://data.meteostat.net/

İlerleme: 13900/48059 şehir tarandı. (Başarılı: 13514)
İlerleme: 14000/48059 şehir tarandı. (Başarılı: 13610)

Warning: Cannot load monthly/03974.csv.gz from https://data.meteostat.net/

İlerleme: 14100/48059 şehir tarandı. (Başarılı: 13709)
İlerleme: 14200/48059 şehir tarandı. (Başarılı: 13803)
İlerleme: 14300/48059 şehir tarandı. (Başarılı: 13902)
İlerleme: 14400/48059 şehir tarandı. (Başarılı: 14002)
İlerleme: 14500/48059 şehir tarandı. (Başarılı: 14101)
İlerleme: 14600/48059 şehir tarandı. (Başarılı: 14199)
İlerleme: 14700/48059 şehir tarandı. (Başarılı: 14298)
İlerleme: 14800/48059 şehir tarandı. (Başarılı: 14396)

Warning: Cannot load monthly/EGXN0.csv.gz from https://data.meteostat.net/

İlerleme: 14900/48059 şehir tarandı. (Başarılı: 14494)

Warning: Cannot load monthly/E6BKJ.csv.gz from https://data.meteostat.net/

İlerleme: 15000/48059 şehir tarandı. (Başarılı: 14587)

Warning: Cannot load monthly/78451.csv.gz from https://data.meteostat.net/

İlerleme: 15100/48059 şehir tarandı. (Başarılı: 14682)
İlerleme: 15200/48059 şehir tarandı. (Başarılı: 14779)
İlerleme: 15300/48059 şehir tarandı. (Başarılı: 14879)
İlerleme: 15400/48059 şehir tarandı. (Başarılı: 14978)

Warning: Cannot load monthly/43413.csv.gz from https://data.meteostat.net/

İlerleme: 15500/48059 şehir tarandı. (Başarılı: 15074)

Warning: Cannot load monthly/4SKO7.csv.gz from https://data.meteostat.net/

İlerleme: 15600/48059 şehir tarandı. (Başarılı: 15171)
İlerleme: 15700/48059 şehir tarandı. (Başarılı: 15267)
İlerleme: 15800/48059 şehir tarandı. (Başarılı: 15366)
İlerleme: 15900/48059 şehir tarandı. (Başarılı: 15461)
İlerleme: 16000/48059 şehir tarandı. (Başarılı: 15558)

Warning: Cannot load monthly/SATM0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/FAMR0.csv.gz from https://data.meteostat.net/

İlerleme: 16100/48059 şehir tarandı. (Başarılı: 15653)
İlerleme: 16200/48059 şehir tarandı. (Başarılı: 15752)
İlerleme: 16300/48059 şehir tarandı. (Başarılı: 15852)

Warning: Cannot load monthly/86223.csv.gz from https://data.meteostat.net/

İlerleme: 16400/48059 şehir tarandı. (Başarılı: 15948)
İlerleme: 16500/48059 şehir tarandı. (Başarılı: 16046)
İlerleme: 16600/48059 şehir tarandı. (Başarılı: 16143)
İlerleme: 16700/48059 şehir tarandı. (Başarılı: 16242)
İlerleme: 16800/48059 şehir tarandı. (Başarılı: 16342)
İlerleme: 16900/48059 şehir tarandı. (Başarılı: 16438)
İlerleme: 17000/48059 şehir tarandı. (Başarılı: 16538)

Warning: Cannot load monthly/86135.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40604.csv.gz from https://data.meteostat.net/

İlerleme: 17100/48059 şehir tarandı. (Başarılı: 16631)
İlerleme: 17200/48059 şehir tarandı. (Başarılı: 16729)
İlerleme: 17300/48059 şehir tarandı. (Başarılı: 16827)
İlerleme: 17400/48059 şehir tarandı. (Başarılı: 16925)

Warning: Cannot load monthly/LIER0.csv.gz from https://data.meteostat.net/

İlerleme: 17500/48059 şehir tarandı. (Başarılı: 17022)
İlerleme: 17600/48059 şehir tarandı. (Başarılı: 17117)
İlerleme: 17700/48059 şehir tarandı. (Başarılı: 17215)

Warning: Cannot load monthly/CWCS0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40637.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/69542.csv.gz from https://data.meteostat.net/

İlerleme: 17800/48059 şehir tarandı. (Başarılı: 17309)

Warning: Cannot load monthly/46759.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/VLKG0.csv.gz from https://data.meteostat.net/

İlerleme: 17900/48059 şehir tarandı. (Başarılı: 17407)
İlerleme: 18000/48059 şehir tarandı. (Başarılı: 17506)
İlerleme: 18100/48059 şehir tarandı. (Başarılı: 17603)

Warning: Cannot load monthly/27196.csv.gz from https://data.meteostat.net/

İlerleme: 18200/48059 şehir tarandı. (Başarılı: 17701)
İlerleme: 18300/48059 şehir tarandı. (Başarılı: 17795)
İlerleme: 18400/48059 şehir tarandı. (Başarılı: 17895)
İlerleme: 18500/48059 şehir tarandı. (Başarılı: 17995)
İlerleme: 18600/48059 şehir tarandı. (Başarılı: 18093)
İlerleme: 18700/48059 şehir tarandı. (Başarılı: 18189)

Warning: Cannot load monthly/40642.csv.gz from https://data.meteostat.net/

İlerleme: 18800/48059 şehir tarandı. (Başarılı: 18285)
İlerleme: 18900/48059 şehir tarandı. (Başarılı: 18383)
İlerleme: 19000/48059 şehir tarandı. (Başarılı: 18482)
İlerleme: 19100/48059 şehir tarandı. (Başarılı: 18582)

Warning: Cannot load monthly/93WXE.csv.gz from https://data.meteostat.net/

İlerleme: 19200/48059 şehir tarandı. (Başarılı: 18679)
İlerleme: 19300/48059 şehir tarandı. (Başarılı: 18774)

Warning: Cannot load monthly/FMNO0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/KQVE0.csv.gz from https://data.meteostat.net/

İlerleme: 19400/48059 şehir tarandı. (Başarılı: 18870)
İlerleme: 19500/48059 şehir tarandı. (Başarılı: 18964)
İlerleme: 19600/48059 şehir tarandı. (Başarılı: 19060)

Warning: Cannot load monthly/CM649.csv.gz from https://data.meteostat.net/

İlerleme: 19700/48059 şehir tarandı. (Başarılı: 19156)
İlerleme: 19800/48059 şehir tarandı. (Başarılı: 19255)

Warning: Cannot load monthly/83033.csv.gz from https://data.meteostat.net/

İlerleme: 19900/48059 şehir tarandı. (Başarılı: 19353)

Warning: Cannot load monthly/44224.csv.gz from https://data.meteostat.net/

İlerleme: 20000/48059 şehir tarandı. (Başarılı: 19452)

Warning: Cannot load monthly/T82KX.csv.gz from https://data.meteostat.net/

İlerleme: 20100/48059 şehir tarandı. (Başarılı: 19551)
İlerleme: 20200/48059 şehir tarandı. (Başarılı: 19650)
İlerleme: 20300/48059 şehir tarandı. (Başarılı: 19749)

Warning: Cannot load monthly/97114.csv.gz from https://data.meteostat.net/

İlerleme: 20400/48059 şehir tarandı. (Başarılı: 19847)
İlerleme: 20500/48059 şehir tarandı. (Başarılı: 19942)
İlerleme: 20600/48059 şehir tarandı. (Başarılı: 20040)

Warning: Cannot load monthly/VLVV0.csv.gz from https://data.meteostat.net/

İlerleme: 20700/48059 şehir tarandı. (Başarılı: 20132)
İlerleme: 20800/48059 şehir tarandı. (Başarılı: 20231)
İlerleme: 20900/48059 şehir tarandı. (Başarılı: 20327)

Warning: Cannot load monthly/AW1DH.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/KQB70.csv.gz from https://data.meteostat.net/

İlerleme: 21000/48059 şehir tarandı. (Başarılı: 20424)
İlerleme: 21100/48059 şehir tarandı. (Başarılı: 20522)
İlerleme: 21200/48059 şehir tarandı. (Başarılı: 20619)
İlerleme: 21300/48059 şehir tarandı. (Başarılı: 20717)
İlerleme: 21400/48059 şehir tarandı. (Başarılı: 20816)

Warning: Cannot load monthly/K44N0.csv.gz from https://data.meteostat.net/

İlerleme: 21500/48059 şehir tarandı. (Başarılı: 20910)
İlerleme: 21600/48059 şehir tarandı. (Başarılı: 21008)
İlerleme: 21700/48059 şehir tarandı. (Başarılı: 21106)
İlerleme: 21800/48059 şehir tarandı. (Başarılı: 21204)

Warning: Cannot load monthly/11543.csv.gz from https://data.meteostat.net/

İlerleme: 21900/48059 şehir tarandı. (Başarılı: 21299)
İlerleme: 22000/48059 şehir tarandı. (Başarılı: 21396)

Warning: Cannot load monthly/12106.csv.gz from https://data.meteostat.net/

İlerleme: 22100/48059 şehir tarandı. (Başarılı: 21495)
İlerleme: 22200/48059 şehir tarandı. (Başarılı: 21593)
İlerleme: 22300/48059 şehir tarandı. (Başarılı: 21690)
İlerleme: 22400/48059 şehir tarandı. (Başarılı: 21788)
İlerleme: 22500/48059 şehir tarandı. (Başarılı: 21885)
İlerleme: 22600/48059 şehir tarandı. (Başarılı: 21984)
İlerleme: 22700/48059 şehir tarandı. (Başarılı: 22081)
İlerleme: 22800/48059 şehir tarandı. (Başarılı: 22179)

Warning: Cannot load monthly/17351.csv.gz from https://data.meteostat.net/

İlerleme: 22900/48059 şehir tarandı. (Başarılı: 22275)
İlerleme: 23000/48059 şehir tarandı. (Başarılı: 22374)
İlerleme: 23100/48059 şehir tarandı. (Başarılı: 22473)
İlerleme: 23200/48059 şehir tarandı. (Başarılı: 22571)
İlerleme: 23300/48059 şehir tarandı. (Başarılı: 22670)
İlerleme: 23400/48059 şehir tarandı. (Başarılı: 22767)
İlerleme: 23500/48059 şehir tarandı. (Başarılı: 22865)
İlerleme: 23600/48059 şehir tarandı. (Başarılı: 22965)
İlerleme: 23700/48059 şehir tarandı. (Başarılı: 23061)

Warning: Cannot load monthly/EEPDD.csv.gz from https://data.meteostat.net/

İlerleme: 23800/48059 şehir tarandı. (Başarılı: 23158)
İlerleme: 23900/48059 şehir tarandı. (Başarılı: 23256)

Warning: Cannot load monthly/68040.csv.gz from https://data.meteostat.net/

İlerleme: 24000/48059 şehir tarandı. (Başarılı: 23352)
İlerleme: 24100/48059 şehir tarandı. (Başarılı: 23449)
İlerleme: 24200/48059 şehir tarandı. (Başarılı: 23545)
İlerleme: 24300/48059 şehir tarandı. (Başarılı: 23641)
İlerleme: 24400/48059 şehir tarandı. (Başarılı: 23737)
İlerleme: 24500/48059 şehir tarandı. (Başarılı: 23835)
İlerleme: 24600/48059 şehir tarandı. (Başarılı: 23934)
İlerleme: 24700/48059 şehir tarandı. (Başarılı: 24034)
İlerleme: 24800/48059 şehir tarandı. (Başarılı: 24132)
İlerleme: 24900/48059 şehir tarandı. (Başarılı: 24231)

Warning: Cannot load monthly/32010.csv.gz from https://data.meteostat.net/

İlerleme: 25000/48059 şehir tarandı. (Başarılı: 24329)
İlerleme: 25100/48059 şehir tarandı. (Başarılı: 24429)

Warning: Cannot load monthly/FYOK0.csv.gz from https://data.meteostat.net/

İlerleme: 25200/48059 şehir tarandı. (Başarılı: 24526)
İlerleme: 25300/48059 şehir tarandı. (Başarılı: 24625)
İlerleme: 25400/48059 şehir tarandı. (Başarılı: 24723)
İlerleme: 25500/48059 şehir tarandı. (Başarılı: 24823)
İlerleme: 25600/48059 şehir tarandı. (Başarılı: 24920)

Warning: Cannot load monthly/QPF0R.csv.gz from https://data.meteostat.net/

İlerleme: 25700/48059 şehir tarandı. (Başarılı: 25017)

Warning: Cannot load monthly/EGBP0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/U8EGK.csv.gz from https://data.meteostat.net/

İlerleme: 25800/48059 şehir tarandı. (Başarılı: 25113)
İlerleme: 25900/48059 şehir tarandı. (Başarılı: 25212)
İlerleme: 26000/48059 şehir tarandı. (Başarılı: 25312)

Warning: Cannot load monthly/61886.csv.gz from https://data.meteostat.net/

İlerleme: 26100/48059 şehir tarandı. (Başarılı: 25411)

Warning: Cannot load monthly/31958.csv.gz from https://data.meteostat.net/

İlerleme: 26200/48059 şehir tarandı. (Başarılı: 25507)
İlerleme: 26300/48059 şehir tarandı. (Başarılı: 25606)

Warning: Cannot load monthly/SCU42.csv.gz from https://data.meteostat.net/

İlerleme: 26400/48059 şehir tarandı. (Başarılı: 25704)
İlerleme: 26500/48059 şehir tarandı. (Başarılı: 25801)
İlerleme: 26600/48059 şehir tarandı. (Başarılı: 25898)
İlerleme: 26700/48059 şehir tarandı. (Başarılı: 25996)
İlerleme: 26800/48059 şehir tarandı. (Başarılı: 26093)

Warning: Cannot load monthly/LD2IV.csv.gz from https://data.meteostat.net/

İlerleme: 26900/48059 şehir tarandı. (Başarılı: 26187)
İlerleme: 27000/48059 şehir tarandı. (Başarılı: 26282)

Warning: Cannot load monthly/SAWM0.csv.gz from https://data.meteostat.net/

İlerleme: 27100/48059 şehir tarandı. (Başarılı: 26381)

Warning: Cannot load monthly/ESQO0.csv.gz from https://data.meteostat.net/

İlerleme: 27200/48059 şehir tarandı. (Başarılı: 26480)

Warning: Cannot load monthly/03562.csv.gz from https://data.meteostat.net/

İlerleme: 27300/48059 şehir tarandı. (Başarılı: 26579)
İlerleme: 27400/48059 şehir tarandı. (Başarılı: 26677)
İlerleme: 27500/48059 şehir tarandı. (Başarılı: 26774)

Warning: Cannot load monthly/UH8VM.csv.gz from https://data.meteostat.net/

İlerleme: 27600/48059 şehir tarandı. (Başarılı: 26871)
İlerleme: 27700/48059 şehir tarandı. (Başarılı: 26970)
İlerleme: 27800/48059 şehir tarandı. (Başarılı: 27068)
İlerleme: 27900/48059 şehir tarandı. (Başarılı: 27167)

Warning: Cannot load monthly/63476.csv.gz from https://data.meteostat.net/

İlerleme: 28000/48059 şehir tarandı. (Başarılı: 27264)
İlerleme: 28100/48059 şehir tarandı. (Başarılı: 27364)

Warning: Cannot load monthly/7I3IW.csv.gz from https://data.meteostat.net/

İlerleme: 28200/48059 şehir tarandı. (Başarılı: 27463)

Warning: Cannot load monthly/93247.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/02169.csv.gz from https://data.meteostat.net/

İlerleme: 28300/48059 şehir tarandı. (Başarılı: 27558)

Warning: Cannot load monthly/41382.csv.gz from https://data.meteostat.net/

İlerleme: 28400/48059 şehir tarandı. (Başarılı: 27654)

Warning: Cannot load monthly/Y9HDL.csv.gz from https://data.meteostat.net/

İlerleme: 28500/48059 şehir tarandı. (Başarılı: 27750)
İlerleme: 28600/48059 şehir tarandı. (Başarılı: 27848)
İlerleme: 28700/48059 şehir tarandı. (Başarılı: 27945)
İlerleme: 28800/48059 şehir tarandı. (Başarılı: 28044)
İlerleme: 28900/48059 şehir tarandı. (Başarılı: 28144)
İlerleme: 29000/48059 şehir tarandı. (Başarılı: 28242)

Warning: Cannot load monthly/94784.csv.gz from https://data.meteostat.net/

İlerleme: 29100/48059 şehir tarandı. (Başarılı: 28340)
İlerleme: 29200/48059 şehir tarandı. (Başarılı: 28440)

Warning: Cannot load monthly/R0QFM.csv.gz from https://data.meteostat.net/

İlerleme: 29300/48059 şehir tarandı. (Başarılı: 28537)

Warning: Cannot load monthly/71594.csv.gz from https://data.meteostat.net/

İlerleme: 29400/48059 şehir tarandı. (Başarılı: 28636)
İlerleme: 29500/48059 şehir tarandı. (Başarılı: 28735)
İlerleme: 29600/48059 şehir tarandı. (Başarılı: 28834)
İlerleme: 29700/48059 şehir tarandı. (Başarılı: 28934)
İlerleme: 29800/48059 şehir tarandı. (Başarılı: 29031)
İlerleme: 29900/48059 şehir tarandı. (Başarılı: 29130)

Warning: Cannot load monthly/3FAHG.csv.gz from https://data.meteostat.net/

İlerleme: 30000/48059 şehir tarandı. (Başarılı: 29228)

Warning: Cannot load monthly/VTPL0.csv.gz from https://data.meteostat.net/

İlerleme: 30100/48059 şehir tarandı. (Başarılı: 29327)

Warning: Cannot load monthly/EDHX0.csv.gz from https://data.meteostat.net/

İlerleme: 30200/48059 şehir tarandı. (Başarılı: 29423)
İlerleme: 30300/48059 şehir tarandı. (Başarılı: 29521)
İlerleme: 30400/48059 şehir tarandı. (Başarılı: 29621)
İlerleme: 30500/48059 şehir tarandı. (Başarılı: 29719)
İlerleme: 30600/48059 şehir tarandı. (Başarılı: 29818)
İlerleme: 30700/48059 şehir tarandı. (Başarılı: 29917)
İlerleme: 30800/48059 şehir tarandı. (Başarılı: 30015)
İlerleme: 30900/48059 şehir tarandı. (Başarılı: 30113)
İlerleme: 31000/48059 şehir tarandı. (Başarılı: 30210)
İlerleme: 31100/48059 şehir tarandı. (Başarılı: 30309)

Warning: Cannot load monthly/FAES0.csv.gz from https://data.meteostat.net/

İlerleme: 31200/48059 şehir tarandı. (Başarılı: 30406)
İlerleme: 31300/48059 şehir tarandı. (Başarılı: 30504)

Warning: Cannot load monthly/ZMUB0.csv.gz from https://data.meteostat.net/

İlerleme: 31400/48059 şehir tarandı. (Başarılı: 30600)
İlerleme: 31500/48059 şehir tarandı. (Başarılı: 30700)

Warning: Cannot load monthly/YL10H.csv.gz from https://data.meteostat.net/

İlerleme: 31600/48059 şehir tarandı. (Başarılı: 30797)
İlerleme: 31700/48059 şehir tarandı. (Başarılı: 30895)
İlerleme: 31800/48059 şehir tarandı. (Başarılı: 30994)
İlerleme: 31900/48059 şehir tarandı. (Başarılı: 31091)

Warning: Cannot load monthly/60200.csv.gz from https://data.meteostat.net/

İlerleme: 32000/48059 şehir tarandı. (Başarılı: 31187)
İlerleme: 32100/48059 şehir tarandı. (Başarılı: 31286)
İlerleme: 32200/48059 şehir tarandı. (Başarılı: 31386)

Warning: Cannot load monthly/10764.csv.gz from https://data.meteostat.net/

İlerleme: 32300/48059 şehir tarandı. (Başarılı: 31484)

Warning: Cannot load monthly/ZQYIH.csv.gz from https://data.meteostat.net/

İlerleme: 32400/48059 şehir tarandı. (Başarılı: 31579)
İlerleme: 32500/48059 şehir tarandı. (Başarılı: 31677)
İlerleme: 32600/48059 şehir tarandı. (Başarılı: 31776)

Warning: Cannot load monthly/03952.csv.gz from https://data.meteostat.net/

İlerleme: 32700/48059 şehir tarandı. (Başarılı: 31871)
İlerleme: 32800/48059 şehir tarandı. (Başarılı: 31967)
İlerleme: 32900/48059 şehir tarandı. (Başarılı: 32066)
İlerleme: 33000/48059 şehir tarandı. (Başarılı: 32164)
İlerleme: 33100/48059 şehir tarandı. (Başarılı: 32261)

Warning: Cannot load monthly/FALC0.csv.gz from https://data.meteostat.net/

İlerleme: 33200/48059 şehir tarandı. (Başarılı: 32359)

Warning: Cannot load monthly/UL9LY.csv.gz from https://data.meteostat.net/

İlerleme: 33300/48059 şehir tarandı. (Başarılı: 32456)
İlerleme: 33400/48059 şehir tarandı. (Başarılı: 32555)
İlerleme: 33500/48059 şehir tarandı. (Başarılı: 32654)
İlerleme: 33600/48059 şehir tarandı. (Başarılı: 32754)
İlerleme: 33700/48059 şehir tarandı. (Başarılı: 32852)
İlerleme: 33800/48059 şehir tarandı. (Başarılı: 32951)
İlerleme: 33900/48059 şehir tarandı. (Başarılı: 33048)
İlerleme: 34000/48059 şehir tarandı. (Başarılı: 33148)

Warning: Cannot load monthly/03970.csv.gz from https://data.meteostat.net/

İlerleme: 34100/48059 şehir tarandı. (Başarılı: 33246)
İlerleme: 34200/48059 şehir tarandı. (Başarılı: 33346)
İlerleme: 34300/48059 şehir tarandı. (Başarılı: 33446)

Warning: Cannot load monthly/11016.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/1Z630.csv.gz from https://data.meteostat.net/

İlerleme: 34400/48059 şehir tarandı. (Başarılı: 33544)
İlerleme: 34500/48059 şehir tarandı. (Başarılı: 33644)
İlerleme: 34600/48059 şehir tarandı. (Başarılı: 33744)
İlerleme: 34700/48059 şehir tarandı. (Başarılı: 33843)
İlerleme: 34800/48059 şehir tarandı. (Başarılı: 33941)

Warning: Cannot load monthly/99870.csv.gz from https://data.meteostat.net/

İlerleme: 34900/48059 şehir tarandı. (Başarılı: 34039)

Warning: Cannot load monthly/AUV78.csv.gz from https://data.meteostat.net/

İlerleme: 35000/48059 şehir tarandı. (Başarılı: 34135)

Warning: Cannot load monthly/FABN0.csv.gz from https://data.meteostat.net/

İlerleme: 35100/48059 şehir tarandı. (Başarılı: 34232)
İlerleme: 35200/48059 şehir tarandı. (Başarılı: 34329)
İlerleme: 35300/48059 şehir tarandı. (Başarılı: 34428)

Warning: Cannot load monthly/02570.csv.gz from https://data.meteostat.net/

İlerleme: 35400/48059 şehir tarandı. (Başarılı: 34526)
İlerleme: 35500/48059 şehir tarandı. (Başarılı: 34626)

Warning: Cannot load monthly/69667.csv.gz from https://data.meteostat.net/

İlerleme: 35600/48059 şehir tarandı. (Başarılı: 34723)
İlerleme: 35700/48059 şehir tarandı. (Başarılı: 34821)

Warning: Cannot load monthly/VTCB0.csv.gz from https://data.meteostat.net/

İlerleme: 35800/48059 şehir tarandı. (Başarılı: 34920)
İlerleme: 35900/48059 şehir tarandı. (Başarılı: 35019)

Warning: Cannot load monthly/ZZQV1.csv.gz from https://data.meteostat.net/

İlerleme: 36000/48059 şehir tarandı. (Başarılı: 35116)
İlerleme: 36100/48059 şehir tarandı. (Başarılı: 35212)
İlerleme: 36200/48059 şehir tarandı. (Başarılı: 35310)

Warning: Cannot load monthly/FMMU0.csv.gz from https://data.meteostat.net/

İlerleme: 36300/48059 şehir tarandı. (Başarılı: 35406)
İlerleme: 36400/48059 şehir tarandı. (Başarılı: 35504)

Warning: Cannot load monthly/K2CB0.csv.gz from https://data.meteostat.net/

İlerleme: 36500/48059 şehir tarandı. (Başarılı: 35600)
İlerleme: 36600/48059 şehir tarandı. (Başarılı: 35700)
İlerleme: 36700/48059 şehir tarandı. (Başarılı: 35797)
İlerleme: 36800/48059 şehir tarandı. (Başarılı: 35894)

Warning: Cannot load monthly/YP4D6.csv.gz from https://data.meteostat.net/

İlerleme: 36900/48059 şehir tarandı. (Başarılı: 35990)
İlerleme: 37000/48059 şehir tarandı. (Başarılı: 36087)
İlerleme: 37100/48059 şehir tarandı. (Başarılı: 36184)
İlerleme: 37200/48059 şehir tarandı. (Başarılı: 36283)
İlerleme: 37300/48059 şehir tarandı. (Başarılı: 36381)
İlerleme: 37400/48059 şehir tarandı. (Başarılı: 36479)

Warning: Cannot load monthly/61878.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/VYTN0.csv.gz from https://data.meteostat.net/

İlerleme: 37500/48059 şehir tarandı. (Başarılı: 36576)

Warning: Cannot load monthly/PPC5W.csv.gz from https://data.meteostat.net/

İlerleme: 37600/48059 şehir tarandı. (Başarılı: 36674)
İlerleme: 37700/48059 şehir tarandı. (Başarılı: 36773)

Warning: Cannot load monthly/71268.csv.gz from https://data.meteostat.net/

İlerleme: 37800/48059 şehir tarandı. (Başarılı: 36870)

Warning: Cannot load monthly/V74W5.csv.gz from https://data.meteostat.net/

İlerleme: 37900/48059 şehir tarandı. (Başarılı: 36968)
İlerleme: 38000/48059 şehir tarandı. (Başarılı: 37065)
İlerleme: 38100/48059 şehir tarandı. (Başarılı: 37165)
İlerleme: 38200/48059 şehir tarandı. (Başarılı: 37263)

Warning: Cannot load monthly/FAKP0.csv.gz from https://data.meteostat.net/

İlerleme: 38300/48059 şehir tarandı. (Başarılı: 37361)
İlerleme: 38400/48059 şehir tarandı. (Başarılı: 37459)
İlerleme: 38500/48059 şehir tarandı. (Başarılı: 37556)

Warning: Cannot load monthly/ENHA0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/G36XH.csv.gz from https://data.meteostat.net/

İlerleme: 38600/48059 şehir tarandı. (Başarılı: 37653)
İlerleme: 38700/48059 şehir tarandı. (Başarılı: 37753)
İlerleme: 38800/48059 şehir tarandı. (Başarılı: 37849)
İlerleme: 38900/48059 şehir tarandı. (Başarılı: 37948)
İlerleme: 39000/48059 şehir tarandı. (Başarılı: 38047)

Warning: Cannot load monthly/SESC0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/81208.csv.gz from https://data.meteostat.net/

İlerleme: 39100/48059 şehir tarandı. (Başarılı: 38143)
İlerleme: 39200/48059 şehir tarandı. (Başarılı: 38242)
İlerleme: 39300/48059 şehir tarandı. (Başarılı: 38342)
İlerleme: 39400/48059 şehir tarandı. (Başarılı: 38441)
İlerleme: 39500/48059 şehir tarandı. (Başarılı: 38538)
İlerleme: 39600/48059 şehir tarandı. (Başarılı: 38638)
İlerleme: 39700/48059 şehir tarandı. (Başarılı: 38737)
İlerleme: 39800/48059 şehir tarandı. (Başarılı: 38833)
İlerleme: 39900/48059 şehir tarandı. (Başarılı: 38932)
İlerleme: 40000/48059 şehir tarandı. (Başarılı: 39030)
İlerleme: 40100/48059 şehir tarandı. (Başarılı: 39129)
İlerleme: 40200/48059 şehir tarandı. (Başarılı: 39229)
İlerleme: 40300/48059 şehir tarandı. (Başarılı: 39329)

Warning: Cannot load monthly/24753.csv.gz from https://data.meteostat.net/

İlerleme: 40400/48059 şehir tarandı. (Başarılı: 39427)

Warning: Cannot load monthly/Z8TCC.csv.gz from https://data.meteostat.net/

İlerleme: 40500/48059 şehir tarandı. (Başarılı: 39524)

Warning: Cannot load monthly/33998.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/07657.csv.gz from https://data.meteostat.net/

İlerleme: 40600/48059 şehir tarandı. (Başarılı: 39622)

Warning: Cannot load monthly/2DVS4.csv.gz from https://data.meteostat.net/

İlerleme: 40700/48059 şehir tarandı. (Başarılı: 39720)
İlerleme: 40800/48059 şehir tarandı. (Başarılı: 39820)
İlerleme: 40900/48059 şehir tarandı. (Başarılı: 39919)
İlerleme: 41000/48059 şehir tarandı. (Başarılı: 40018)
İlerleme: 41100/48059 şehir tarandı. (Başarılı: 40118)
İlerleme: 41200/48059 şehir tarandı. (Başarılı: 40217)
İlerleme: 41300/48059 şehir tarandı. (Başarılı: 40314)

Warning: Cannot load monthly/MGPC0.csv.gz from https://data.meteostat.net/

İlerleme: 41400/48059 şehir tarandı. (Başarılı: 40413)

Warning: Cannot load monthly/65937.csv.gz from https://data.meteostat.net/

İlerleme: 41500/48059 şehir tarandı. (Başarılı: 40511)
İlerleme: 41600/48059 şehir tarandı. (Başarılı: 40611)
İlerleme: 41700/48059 şehir tarandı. (Başarılı: 40709)

Warning: Cannot load monthly/11722.csv.gz from https://data.meteostat.net/

İlerleme: 41800/48059 şehir tarandı. (Başarılı: 40804)
İlerleme: 41900/48059 şehir tarandı. (Başarılı: 40902)
İlerleme: 42000/48059 şehir tarandı. (Başarılı: 41001)
İlerleme: 42100/48059 şehir tarandı. (Başarılı: 41099)
İlerleme: 42200/48059 şehir tarandı. (Başarılı: 41197)
İlerleme: 42300/48059 şehir tarandı. (Başarılı: 41295)
İlerleme: 42400/48059 şehir tarandı. (Başarılı: 41392)
İlerleme: 42500/48059 şehir tarandı. (Başarılı: 41492)
İlerleme: 42600/48059 şehir tarandı. (Başarılı: 41591)
İlerleme: 42700/48059 şehir tarandı. (Başarılı: 41688)

Warning: Cannot load monthly/P00KI.csv.gz from https://data.meteostat.net/

İlerleme: 42800/48059 şehir tarandı. (Başarılı: 41786)
İlerleme: 42900/48059 şehir tarandı. (Başarılı: 41884)
İlerleme: 43000/48059 şehir tarandı. (Başarılı: 41982)
İlerleme: 43100/48059 şehir tarandı. (Başarılı: 42082)
İlerleme: 43200/48059 şehir tarandı. (Başarılı: 42181)

Warning: Cannot load monthly/MXB8N.csv.gz from https://data.meteostat.net/

İlerleme: 43300/48059 şehir tarandı. (Başarılı: 42279)
İlerleme: 43400/48059 şehir tarandı. (Başarılı: 42375)
İlerleme: 43500/48059 şehir tarandı. (Başarılı: 42471)
İlerleme: 43600/48059 şehir tarandı. (Başarılı: 42570)
İlerleme: 43700/48059 şehir tarandı. (Başarılı: 42668)
İlerleme: 43800/48059 şehir tarandı. (Başarılı: 42766)

Warning: Cannot load monthly/MPNU0.csv.gz from https://data.meteostat.net/

İlerleme: 43900/48059 şehir tarandı. (Başarılı: 42862)

Warning: Cannot load monthly/SPVL0.csv.gz from https://data.meteostat.net/

İlerleme: 44000/48059 şehir tarandı. (Başarılı: 42960)
İlerleme: 44100/48059 şehir tarandı. (Başarılı: 43059)
İlerleme: 44200/48059 şehir tarandı. (Başarılı: 43157)
İlerleme: 44300/48059 şehir tarandı. (Başarılı: 43254)
İlerleme: 44400/48059 şehir tarandı. (Başarılı: 43352)
İlerleme: 44500/48059 şehir tarandı. (Başarılı: 43449)
İlerleme: 44600/48059 şehir tarandı. (Başarılı: 43547)
İlerleme: 44700/48059 şehir tarandı. (Başarılı: 43643)
İlerleme: 44800/48059 şehir tarandı. (Başarılı: 43740)
İlerleme: 44900/48059 şehir tarandı. (Başarılı: 43839)
İlerleme: 45000/48059 şehir tarandı. (Başarılı: 43936)
İlerleme: 45100/48059 şehir tarandı. (Başarılı: 44034)
İlerleme: 45200/48059 şehir tarandı. (Başarılı: 44134)
İlerleme: 45300/48059 şehir tarandı. (Başarılı: 44233)
İlerleme: 45400/48059 şehir tarandı. (Başarılı: 44332)
İlerleme: 45500/48059 şehir tarandı. (Başarılı: 44431)

Warning: Cannot load monthly/06467.csv.gz from https://data.meteostat.net/

İlerleme: 45600/48059 şehir tarandı. (Başarılı: 44529)
İlerleme: 45700/48059 şehir tarandı. (Başarılı: 44628)

Warning: Cannot load monthly/SCSR0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/40480.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/K5T60.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/72784.csv.gz from https://data.meteostat.net/

İlerleme: 45800/48059 şehir tarandı. (Başarılı: 44721)
İlerleme: 45900/48059 şehir tarandı. (Başarılı: 44820)
İlerleme: 46000/48059 şehir tarandı. (Başarılı: 44916)

Warning: Cannot load monthly/M8L9N.csv.gz from https://data.meteostat.net/

İlerleme: 46100/48059 şehir tarandı. (Başarılı: 45013)
İlerleme: 46200/48059 şehir tarandı. (Başarılı: 45109)
İlerleme: 46300/48059 şehir tarandı. (Başarılı: 45204)

Warning: Cannot load monthly/XGHYQ.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/11195.csv.gz from https://data.meteostat.net/

İlerleme: 46400/48059 şehir tarandı. (Başarılı: 45300)
İlerleme: 46500/48059 şehir tarandı. (Başarılı: 45400)
İlerleme: 46600/48059 şehir tarandı. (Başarılı: 45497)

Warning: Cannot load monthly/94527.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/94085.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/68038.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/13015.csv.gz from https://data.meteostat.net/

İlerleme: 46700/48059 şehir tarandı. (Başarılı: 45590)

Warning: Cannot load monthly/24644.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/FTTZ0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/94869.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/FYMH0.csv.gz from https://data.meteostat.net/

İlerleme: 46800/48059 şehir tarandı. (Başarılı: 45684)

Warning: Cannot load monthly/M5SP7.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/5H5ZH.csv.gz from https://data.meteostat.net/

İlerleme: 46900/48059 şehir tarandı. (Başarılı: 45780)

Warning: Cannot load monthly/24263.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SAVD0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/FYAS0.csv.gz from https://data.meteostat.net/

İlerleme: 47000/48059 şehir tarandı. (Başarılı: 45871)

Warning: Cannot load monthly/38401.csv.gz from https://data.meteostat.net/

İlerleme: 47100/48059 şehir tarandı. (Başarılı: 45968)
İlerleme: 47200/48059 şehir tarandı. (Başarılı: 46059)

Warning: Cannot load monthly/91742.csv.gz from https://data.meteostat.net/

İlerleme: 47300/48059 şehir tarandı. (Başarılı: 46153)

Warning: Cannot load monthly/HSNA0.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/13005.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SAVR0.csv.gz from https://data.meteostat.net/

İlerleme: 47400/48059 şehir tarandı. (Başarılı: 46245)

Warning: Cannot load monthly/91740.csv.gz from https://data.meteostat.net/

İlerleme: 47500/48059 şehir tarandı. (Başarılı: 46342)

Warning: Cannot load monthly/91739.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/81010.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/25744.csv.gz from https://data.meteostat.net/

İlerleme: 47600/48059 şehir tarandı. (Başarılı: 46438)

Warning: Cannot load monthly/24219.csv.gz from https://data.meteostat.net/

İlerleme: 47700/48059 şehir tarandı. (Başarılı: 46535)

Warning: Cannot load monthly/94482.csv.gz from https://data.meteostat.net/
Warning: Cannot load monthly/SPAS0.csv.gz from https://data.meteostat.net/

İlerleme: 47800/48059 şehir tarandı. (Başarılı: 46629)

Warning: Cannot load monthly/KQCQ0.csv.gz from https://data.meteostat.net/

İlerleme: 47900/48059 şehir tarandı. (Başarılı: 46727)

Warning: Cannot load monthly/25017.csv.gz from https://data.meteostat.net/

İlerleme: 48000/48059 şehir tarandı. (Başarılı: 46823)

==================================================
İŞLEM TAMAMLANDI
Toplam Taranan: 48059
Başarılı Veri (Şehir Bazlı): 46881
Hatalar 'hatali_sehirler_log.txt' dosyasına kaydedildi.
==================================================

SONUÇ DATAFRAME (İLK 20 SATIR):
         time     city_id city_name country  tavg  tmin  tmax     lat  \
0  1951-01-01  1392685764     Tokyo      JP   3.3  -1.0   8.6  35.687
1  1951-02-01  1392685764     Tokyo      JP   4.5   0.4   9.7  35.687
2  1951-03-01  1392685764     Tokyo      JP   8.8   4.1  14.2  35.687
3  1951-04-01  1392685764     Tokyo      JP  13.3   9.0  18.3  35.687
4  1951-05-01  1392685764     Tokyo      JP  18.0  13.9  23.3  35.687
5  1951-06-01  1392685764     Tokyo      JP  21.2  17.3  25.9  35.687
6  1951-07-01  1392685764     Tokyo      JP  24.3  21.2  28.3  35.687
7  1951-08-01  1392685764     Tokyo      JP  26.7  23.5  31.6  35.687
8  1951-09-01  1392685764     Tokyo      JP  20.7  17.4  24.7  35.687
9  1951-10-01  1392685764     Tokyo      JP  17.3  13.9  21.7  35.687
10 1951-11-01  1392685764     Tokyo      JP  11.4   6.8  16.8  35.687
11 1951-12-01  1392685764     Tokyo      JP   7.3   2.2  13.4  35.687
12 1952-01-01  1392685764     Tokyo      JP   4.3  -0.1   9.7  35.687
13 1952-02-01  1392685764     Tokyo      JP   2.6  -0.6   6.8  35.687
14 1952-03-01  1392685764     Tokyo      JP   7.4   3.7  12.1  35.687
15 1952-04-01  1392685764     Tokyo      JP  13.3   9.0  18.3  35.687
16 1952-05-01  1392685764     Tokyo      JP  18.1  13.8  23.2  35.687
17 1952-06-01  1392685764     Tokyo      JP  21.3  17.9  25.5  35.687
18 1952-07-01  1392685764     Tokyo      JP  24.3  21.5  28.2  35.687
19 1952-08-01  1392685764     Tokyo      JP  26.8  23.7  31.4  35.687

         lng
0   139.7495
1   139.7495
2   139.7495
3   139.7495
4   139.7495
5   139.7495
6   139.7495
7   139.7495
8   139.7495
9   139.7495
10  139.7495
11  139.7495
12  139.7495
13  139.7495
14  139.7495
15  139.7495
16  139.7495
17  139.7495
18  139.7495
19  139.7495

DATAFRAME BİLGİSİ:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17389097 entries, 0 to 17389096
Data columns (total 9 columns):
 #   Column     Dtype
---  ------     -----
 0   time       datetime64[ns]
 1   city_id    int64
 2   city_name  object
 3   country    object
 4   tavg       Float64
 5   tmin       Float64
 6   tmax       Float64
 7   lat        float64
 8   lng        float64
dtypes: Float64(3), datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 1.2+ GB
None

Veriler 'tum_dunya_hava_verileri.csv' dosyasına kaydediliyor...
Kayıt işlemi başarılı.

In [6]:
final_df

,time,city_id,city_name,country,tavg,tmin,tmax,lat,lng
0,1951-01-01,1392685764,Tokyo,JP,3.3,-1.0,8.6,35.687,139.7495
1,1951-02-01,1392685764,Tokyo,JP,4.5,0.4,9.7,35.687,139.7495
2,1951-03-01,1392685764,Tokyo,JP,8.8,4.1,14.2,35.687,139.7495
3,1951-04-01,1392685764,Tokyo,JP,13.3,9.0,18.3,35.687,139.7495
4,1951-05-01,1392685764,Tokyo,JP,18.0,13.9,23.3,35.687,139.7495
...,...,...,...,...,...,...,...,...,...
17389092,2025-06-01,1850037473,Charlotte Amalie,VI,29.0,26.6,32.4,18.342,-64.9331
17389093,2025-07-01,1850037473,Charlotte Amalie,VI,29.1,26.5,32.6,18.342,-64.9331
17389094,2025-08-01,1850037473,Charlotte Amalie,VI,29.9,27.5,33.0,18.342,-64.9331
17389095,2025-09-01,1850037473,Charlotte Amalie,VI,29.5,27.3,32.3,18.342,-64.9331
17389096,2025-10-01,1850037473,Charlotte Amalie,VI,29.2,27.1,31.9,18.342,-64.9331